### ISSUE TITLE
Manage search synonyms 

### ISSUE THREAD

**Issue by metalogique** [SharePoint/sp-dev-solutions#100]
#### Category
- [ ] Question
- [ ] Bug
- [X] Enhancement

#### Expected or Desired Behavior
As there is no way to import a thesaurus for synonyms in SPO, it would be great to add that functionality to the roadmap using a component-centric or a global list of synonyms. 
Possibly something similar to: https://www.eliostruyf.com/a-better-way-for-search-synonyms-in-sharepoint-online-2013-2016/

**Comment by wobba** [comment]
I've had this on my mind - just haven't had a need just yet to port it over.

**Comment by metalogique** [comment]
I will take a look at it in the next few days as I have a bit of time on my hands.

**Comment by wobba** [comment]
@metalogique I suggest a separate solution below the `ModernSearch` folder which will provision the needed list list to the site where you add the app/SPFx solution, as well as implement a provider like the NLP one we have.

This way the install should be pretty easy, and docs on how to manage synonyms can easily be added to the readme.

What do you think?

**Comment by aboredman** [comment]
(I am the same person as @metalogique , I just realized I was using my generic work account)

@wobba My current idea was to avoid having a SharePoint list to store synonyms. I was leaning toward using a string property in SPFx SearchResult WP with a JSON syntax to define the synonyms as this seems inline with how the selectedproprties and styles are managed for the WP. What's your take on that?

**Comment by FranckyC** [comment]
Hi @aboredman so you want to add a new 'synonyms' property and build the query dynamically? Should work with a PropertyFieldCollectionData + QueryTemplate. Just be careful of the final query length.

**Comment by aboredman** [comment]
@FranckyC after a quick search the max query length seems to be 4096 characters. Is that the correct limit?
If so I'll keep that in mind.

**Comment by wobba** [comment]
Query length is no concern. I'll teach you guys a trick - just add them as FQL in the refinement param 😁 I do this in several posts I have.

JSON is fine but crap for user management of adding/removing synonyms imo. We could easily provide different solutions for this though as they tie into the result wp.

**Comment by aboredman** [comment]
> 
> 
> Query length is no concern. I'll teach you guys a trick - just add them as FQL in the refinement param 😁 I do this in several posts I have.
> 
> JSON is fine but crap for user management of adding/removing synonyms imo. We could easily provide different solutions for this though as they tie into the result wp.

Nice, the refinement filter approach adds a minimal amount of complexity but more than makes up for it in reliability.

For the synonyms I'll start with the json approach as it seems easier to implement (and as a poweruser I would prefer to manage synonyms in JSON) but I totally get that less technical users would probably prefer something more user friendly.

**Comment by FranckyC** [comment]
@aboredman Can it be a property pane control (PropertyFieldCollectionData) + external file option like the templates?
