### ISSUE TITLE
[ModernSearch] Cannot Find module "readline"

### ISSUE THREAD

**Issue by tibgcv** [SharePoint/sp-dev-solutions#103]
#### Category
- [ ] Question
- [ X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Added the Search Box, Search Filters and Search Results webpart, using default settings. 
When searching for a file on the current site collection, it should show the results.

#### Observed Behavior
Getting an error:
[SharePointDataProvider.search()]: Error: Error: Cannot find module "readline"
[SearchContainer._componentWillReceiveProps()]: Error: Error: Cannot find module "readline"
Failed to load resource: the server responded with a status of 403 (All records were throttled.)

#### Steps to Reproduce
Adding the modern search latest version to a modern sharepoint home.aspx

**Comment by tibgcv** [comment]
without the Search Filters webpart I'm getting: Uncaught (in promise) TypeError: e is not a function

**Comment by FranckyC** [comment]
Hi @tibgcv what version are you using?

**Comment by tibgcv** [comment]
version: 3.0.5.0

**Comment by wobba** [comment]
@tibgcv I pulled down the latest `3.1.1.0` now which builds fine. Try `npm dedupe` after `npm i` and then `gulp`.
