### ISSUE TITLE
Thumbnail picture of is not coming using search refiner

### ISSUE THREAD

**Issue by Rajrup-net** [SharePoint/sp-dev-solutions#108]
I have created one news article page and there I have added one Thumbnail picture. Now when i am trying to fetch the the news post in other page using search refiner everything is coming except that thumbnail pictute. 

I have added PublishingImage as managed propoerty.
Here is the code:
```html
<div class="template_result">
                               // <img height="60" width="70" style="padding-right:10px" src="{{PublishingImage}}">
                               <div class="template_contentContainer">
                                <span class=""><a href="{{getUrl item}}">{{Title}}</a></span>
                                <span class="">{{getSummary HitHighlightedSummary}}</span>
                                <span class=""><span>{{getDate Created "LL"}}</span></span>   
                                <div class="tags_736e27a1">
```
But the picture is not coming. I did inspect element.. I am getting picture url  but still picture is not appearing.
this is the inspect element scenario :

```
<img height="60" width="70" style="padding-right:10px" src="<img alt=""<src="/news/PublishingImages/Chaand-Nagpaul.jpg" style="BORDER&amp;0px solid;" />
```

Can you please tell me what i am missing here. Thanks in advance.

**Comment by wobba** [comment]
This is unrelated to the search web part. You have an absolute link to `/news/PublishingImages/Chaand-Nagpaul.jpg` which resolves to `https://tenant.sharepoint.com/news/PublishingImages/Chaand-Nagpaul.jpg`. If your image is not at this location, then not much the search web part can do.

**Comment by Rajrup-net** [comment]
@wobba Thumbnail picture along with post dynamically has to come. I cannot give absolute url there

**Comment by okms** [comment]
Just to push you gently in the right direction.... 

@Rajrup-net PublishingImage is raw html, not just an url. If you want to render it as-is in a handlebars template, you must use {{{ }}} (triple curly braces), like so

```
<div class="template_result">
    {{{PublishingImage}}}
    <div class="template_contentContainer">
        <span class=""><a href="{{getUrl item}}">{{Title}}</a></span>
        <span class="">{{getSummary HitHighlightedSummary}}</span>
        <span class=""><span>{{getDate Created "LL"}}</span></span>
        <div class="tags_736e27a1">
    <!-- the following closes the tags from your partial code -->
        </div>
    </div>
</div>
```

if you need to do anything else with PublishingImage, parse the html into a DOM element (does not need to be actually injected into the document).

**Comment by Rajrup-net** [comment]
@okms Thanks Man.. Thanks a lot.. I didnt know that before. Thanks again. Just a small query as I am little bit inquisitive how to add css for this {{{PublishingImage}}} as the picture is coming very big. I have to resize it. I am very knew into this that's why i get stuck.
