### ISSUE TITLE
Enhancement: Office UI Persona and PersonaCard Layout

### ISSUE THREAD

**Issue by PerIngeH** [SharePoint/sp-dev-solutions#109]
#### Category
- [x ] Enhancement

I am trying to build a organizational search. See that available Office UI items are those of List and Label. 
Is it possible to include the Office UI Persona and PersonaCard:
https://developer.microsoft.com/en-us/fabric-js/components/personacard/personacard

**Comment by wobba** [comment]
If you manage to accomplish the markup it could be possible. Also take a look at the persona renderer at https://github.com/SharePoint/sp-dev-solutions/tree/master/solutions/ModernSearch/react-search-refiners-renderer

**Comment by PerIngeH** [comment]
The persona render works fine :-)
