### ISSUE TITLE
Refiner web part does not translate terms

### ISSUE THREAD

**Issue by coupalm** [SharePoint/sp-dev-solutions#114]
#### Category
- [ ] Question
- [ X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Refiner web part should translate terms as with the search results web part

#### Observed Behavior
Terms are not translated, in the refiner web parrt, using translation in the terms store.

#### Steps to Reproduce
- Have terms that are translated.
- Put search results and refiner web part on the screen.
- Log with user configured with a language different from the site default language and where terms have been translated in the user language and the site default language.
- User will see terms values in the refiner with the site default language and terms in the search results with is the user default language.

#### Submission Guidelines
Probably using the same technique as in the search result web part.

**Comment by FranckyC** [comment]
Hi @coupalm. Have you configured your search managed properties as explained in the documentation (README)? You need to use ows_taxId_xxx crawled properties to get the translation work. Also don't forget to enable the localization flag in the WP property pane as well.

**Comment by coupalm** [comment]
Ok, I had a brain freeze... Did not use, in the refiner web part, the taxId managed property. 
Just for my info, in the search result web part result template, I'm using the theme primary color but it does not work. In my theme the primary color is orange and in the web part it is blue. There is no blue in my theme ...

<div class="ms-bgColor-themePrimary">

Thanks

**Comment by wobba** [comment]
@coupalm can you paste the template you are using?

**Comment by wobba** [comment]
@coupalm think I found the error. Someone updated microsoft/sp-office-ui-fabric-core to the latest version. It has to stay on a 1.6.0 to work. I'll edit package.json for this.

**Comment by wobba** [comment]
Pull down the dev branch and retry.

**Comment by coupalm** [comment]
> @coupalm think I found the error. Someone updated microsoft/sp-office-ui-fabric-core to the latest version. It has to stay on a 1.6.0 to work. I'll edit package.json for this.

Ok thanks for the quick fix!
