### ISSUE TITLE
Modern Search: Refiner WebPart - Refiners expanded by default 

### ISSUE THREAD

**Issue by coupalm** [SharePoint/sp-dev-solutions#120]
#### Category
- [ ] Question
- [ ] Bug
- [X] Enhancement

#### Expected or Desired Behavior
It would be useful to be able to specify if we want the refiners expanded or not in the search refiners web part config.

#### Observed Behavior
Refiners are always collapsed by default.

Thanks.

**Comment by YannickRe** [comment]
Would you like an all or nothing switch, or a setting per refiner?

**Comment by coupalm** [comment]
In my use case, the option could be applied to all refiners. Normally I will use this option when there is one or two refiners with short lists of values.  If it is not a lot more effort, per refiner would be great otherwise all refiners will be good for me.

Thanks.

**Comment by FranckyC** [comment]
@coupalm this could be something doable. I will add it to the roadmap.
