### ISSUE TITLE
Would it work with SharePoint 2019

### ISSUE THREAD

**Issue by schneika** [SharePoint/sp-dev-solutions#121]
Anybody experiences with SPFx Build in SharePoint 2019 or not possible?

#### Category
- [x] Question
- [ ] Bug
- [x] Enhancement

Thanks for your contribution! Sharing is caring.

**Comment by wobba** [comment]
@schneika which solution are you thinking about? In general the solutions will only work on SPO if they are using SPFx > 1.4.1.

* 2016 support SPFx v1.1
* 2019 support SPFx v1.4.1

If you can downgrade the solution to either of those, you can in theory make them work - if they use features introduced after 1.5.1, then it's a bit harder.

**Comment by wobba** [comment]
I'll close this as no feedback has been provided regarding which project you are referring to.
