### ISSUE TITLE
[ModernSearch] Ability to redirect standard search box to this solution

### ISSUE THREAD

**Issue by frankok** [SharePoint/sp-dev-solutions#122]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Bug
- [x] Enhancement

#### Expected or Desired Behavior
The standard search box in the upper left corner on all pages allows users to search for content on the site, hub, or list/library. When redirected, the new Modern Search Results page appears. 
It would be nice if this solution [ModernSearch] could have a feature for overriding where the user is sent when hitting the Enter button. Preferrably to a Search Results page using this solution.

**Comment by wobba** [comment]
Hi,
I have to close this as redirecting the oob search box is outside of our control. Sure it can be DOM hacked, but we're better off waiting for a proper solution from Microsoft. I can say as much as it's something many want, so follow public news going forward from Microsoft.

**Comment by frankok** [comment]
OK, fair enough Mikael,
Thank you for the information and swift feedback! :-)
