### ISSUE TITLE
React Search Refiners Renderers JavaScript heap out of memory after adding new extension

### ISSUE THREAD

**Issue by RuneHanssens** [SharePoint/sp-dev-solutions#124]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
I'm trying to add a new extension to the solution so I can make my own custom coderenderer. I use the yeoman sharepoint generator and expect a dialog with a message to be printed out.

#### Observed Behavior
I can start the solution just fine and after I add a new extension using the yeoman sharepoint generator I get the following error. The personarenderer and the coderenderer work fine. But I do not get a dialog with a message.

Error - [tslint] FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
[11:35:32] Error - [tslint] 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewUninitializedFixedArray
 5: v8::internal::WasmDebugInfo::SetupForTesting
 6: v8::internal::interpreter::BytecodeArrayRandomIterator::UpdateOffsetFromIndex
 7: 000002C71E2843C1

package.json file:
{
  "name": "react-search-refiners-renderer",
  "version": "1.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/decorators": "~1.7",
    "@microsoft/generator-sharepoint": "~1.7",
    "@microsoft/sp-application-base": "^1.7.1",
    "@microsoft/sp-core-library": "~1.7",
    "@microsoft/sp-dialog": "~1.7",
    "@types/es6-promise": "0.0.33",
    "@types/react": "16.4.2",
    "@types/react-dom": "16.0.5",
    "@types/webpack-env": "1.13.1",
    "custom-event-polyfill": "^1.0.6",
    "install": "^0.12.2",
    "moment": "^2.23.0",
    "office-ui-fabric-react": "^5.133.0",
    "react": "16.3.2",
    "react-dom": "16.3.2"
  },
  "resolutions": {
    "@types/react": "16.4.2"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "^1.7",
    "@microsoft/sp-tslint-rules": "^1.7",
    "@microsoft/sp-module-interfaces": "^1.7",
    "@microsoft/sp-webpart-workbench": "^1.7",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "@microsoft/rush-stack-compiler-2.7": "0.4.0"
  }
}

#### Steps to Reproduce
Just add a new helloworld extension to the solution using yo @microsoft/sharepoint and then start the solution using gulp serve.

**Comment by YannickRe** [comment]
@RuneHanssens I just tried this by adding a new Application Customizer extension to the existing solution, and running `gulp serve --config=helloWorld`. I didn't encounter any issues.

From your package.json file, I suspect you have SharePoint Framework Yeoman Generator v1.8.0 installed. The following line is new since v1.8:
`"@microsoft/rush-stack-compiler-2.7": "0.4.0"`
Currently, due to issues with 1.8 itself and related dependencies we decided to not yet upgrade to v1.8 and stick with 1.7.1. (see also #99 )
Can you possibly try adding an extension with v1.7.1 of SPFx Yeoman generator?

**Comment by wobba** [comment]
We've seen memory issues with other larger SPFx projects and I've encountered this myself once with this project running 1.7.1. I'll find details on a workaround later when I'm on my pc.

**Comment by wobba** [comment]
For 1.8 add this or similar in package.json:
 
"bundle:dev": "cross-env NODE_OPTIONS=--max_old_space_size=8192 gulp bundle",
"bundle:prod": "cross-env NODE_OPTIONS=--max_old_space_size=8192 gulp bundle --ship",
 
this will allocate more memory for building.

**Comment by RuneHanssens** [comment]
Indeed I have the yeoman 1.8 generator... I will try out a previous version. Thanks!

**Comment by wobba** [comment]
@RuneHanssens can we close this one? And feel free to try my suggestion as well.

**Comment by RuneHanssens** [comment]
The other solution didn't work for me and yes you can close this one. Thanks!

**Comment by wobba** [comment]
@RuneHanssens Take a look at https://github.com/SharePoint/sp-starter-kit/blob/dev/solution/package.json and also the readme file. You have to use `npm run...` to execute those.

**Comment by RuneHanssens** [comment]
@wobba forgot to mention that the issue was indeed the yeoman version and it has been resolved now.
