### ISSUE TITLE
Add Hub/Subscriber Scoping Capability

### ISSUE THREAD

**Issue by quarterhorse** [SharePoint/sp-dev-solutions#136]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Bug
- [X] Enhancement

#### Expected or Desired Behavior
Please add a new custom query variable to represent the hub scope and some means to search the current hub and subscribers, then "back out" to an enterprise-level search (configurable to turn on/off, presumably).  Hubs and hub relationships are an important topological concept and the modern search experience supports searching within the hub scope (meaning the hub and associated subscribers).  Information in the <hub site collection id>.json file found in the /_catalogs/hubsite folder might be helpful in expanding the variable to an appropriate clause.

**Comment by wobba** [comment]
On the hub itself you should be able to use `{Site.ID}` as the hub id is the hubs site id. On an associated site we'll look into it.

**Comment by quarterhorse** [comment]
Much appreciated - Yes, you can use site.id, but it won't search the hub and subscribers.  The big idea for search with the hub stuff is they create a pseudo "search scope" consisting of the hub and all subscribers.  Additionally, a site collection can change the hub it's subscribed to in which case the "search scope" is supposed to change.   Same thing if additional site collections subscribe to the hub - those would be included in the search.

To see this stuff in action, create two modern site collections, define one as a hub and the other as a subscriber, dope the site collections with some dummy files, wait for the indexing to occur, then perform searches both at the hub and subscriber.  You can click on the Organization in the search breadcrumb to widen the search to everything.

**Comment by wobba** [comment]
@quarterhorse I know well how hubs works and org wide search. I have some info at https://www.techmikael.com/2018/04/working-with-hub-sites-and-search-api.html.

So, at the hubsite filter on `DepartmentId:{Site.ID}` and you get results from the hub and associated sites. On the subscriber sites we need a variable to get the site id from the hub. So a good enhancement indeed.

**Comment by quarterhorse** [comment]
@wobba You're absolutely right.  Your last sentence in your first response was what I was clumsily trying to point out - the subscribers - which is what you already pointed out but I missed somehow.  I should probably not to post after a long day.

**Comment by wobba** [comment]
Np 😁

**Comment by YannickRe** [comment]
I submitted a PR that will allow you to solve this use case, but with a broader approach. It introduces a PageContext search token, that allows you to extract/inject information from the legacyPageContext object into your query template. In your case, that would mean using: `DepartmentId:{{PageContext.hubSiteId}}`

**Comment by sympmarc** [comment]
I'm trying to use the `DepartmentId:{Site.ID}` trick in a page in the Hub Site, and I can't seem to get it to work. I must be doing something stupid, but is that the exact syntax? I get no results with that phrase in the Query template. Without it, everything works as expected.

What I'd like to use is:
`{searchTerms} PromotedState=2 DepartmentId:{Site.ID}`
So, all news in the Hub Site scope.

**Comment by YannickRe** [comment]
Try double parenthesis, as the hubSiteId is stored in the index with the parenthesis. You can also try the PageContext token, it works in the hubsite and in the hubsite joined sites.

**Comment by sympmarc** [comment]
Do you mean `DepartmentId:{{Site.ID}}`? That doesn't seem to work, either. Note that I think I took my copy before your pull request.

**Comment by YannickRe** [comment]
Yes, that’s what I meant. On my phone, and I can’t seem to find the backticks for markdown code...

If you aren’t using the latest version from dev branch, the PageContext token won’t be there obviously.
The Site.ID token should work, but if your site is just recently promoted to a hubsite it might need some time to reindex with the correct id.

I’ll check tomorrow, in the mean time maybe you can try troubleshooting with a hardcoded site id or on a older hub site?

**Comment by sympmarc** [comment]
Thanks, @YannickRe. It's a Hub site which has existed for more than a week, so I don't think it's timing. Like I said, I feel like I'm doing something dumb. I'll see if a hard-coded site GUID will work in the meantime.

**Comment by wobba** [comment]
@sympmarc Can you check the network trace of the_api/search call and see if the returned result resolves the Site.ID token when used in the query template? Look for the modified query part.

**Comment by sympmarc** [comment]
It does indeed resolve the Site.ID token.

`https://tenant.sharepoint.com/sites/Inside/_api/search/query?QueryText=%27((DepartmentId:dcd5de48-594f-4cb7-88ee-2793fbdb6deb)%20OR%20(DepartmentId:{dcd5de48-594f-4cb7-88ee-2793fbdb6deb}))%27&QueryTemplate=%27{searchterms}%20(contentclass=STS_Site%20OR%20contentclass=STS_Web)%27&SelectProperties=%27SiteId,WebId,Path,DepartmentId,Title,IsHubSite%27&EnableQueryRules=false&RowLimit=1000&Properties=%27EnableDynamicGroups:true,EnableMultiGeoSearch:true%27&sortlist=%27QLogClicks:Descending%27&ClientType=%27SpClient%27`

```
3: {Key: "QueryModification",…} 
Key: "QueryModification"
Value: "((DepartmentId:dcd5de48-594f-4cb7-88ee-2793fbdb6deb) OR (DepartmentId:{dcd5de48-594f-4cb7-88ee-2793fbdb6deb})) (contentclass=STS_Site OR contentclass=STS_Web) -ContentClass=urn:content-class:SPSPeople"
ValueType: "Edm.String"
```
The info above is from the query (_api/search/query)

With `DepartmentId:{Site.ID}` I get 0 results in the postquery (_api/search/postquery). Without it, I get 10 results out of 30.

**Comment by YannickRe** [comment]
I did some investigation with the search query tool, and I'm thinking it's a new bug in SPO but I'll leave it up to @wobba to verify ;)

All the items in my HubSite have:
- `DepartmentId: {02a133ae-b17a-40e7-9cbd-a8f07fa02868}`
- `SiteId: 02a133ae-b17a-40e7-9cbd-a8f07fa02868`
- `WebId: d9bc8cd4-2502-443b-9f99-e1c22ed0febf`

Using the search query tool, I submitted:
- `searchTerms: *`
- `QueryTemplate: {searchTerms} DepartmentId:{Site.ID} or DepartmentId:{Web.ID} or DepartmentId:{SiteCollection.ID}`
The resulting QueryModification was `* DepartmentId:d9bc8cd4-2502-443b-9f99-e1c22ed0febf or DepartmentId:d9bc8cd4-2502-443b-9f99-e1c22ed0febf or DepartmentId:d9bc8cd4-2502-443b-9f99-e1c22ed0febf -ContentClass=urn:content-class:SPSPeople`

The resulting QueryModification shows two things:
- You'll need to add the double parenthesis to make sure that the value is recognized. The server side token returns the id without parentheses, but DepartementId stores the value with parentheses.
- All three tokens (Site.ID, Web.ID & SiteCollection.ID) return the value of my web id. **I think this is a regression/bug on the SPO side.**

**Comment by sympmarc** [comment]
Note that the or'ed part of the query was not because of my KQL. I'm using this as my default query:

`PromotedState=2 DepartmentId:{Site.ID}`

That seems to be expanded to:

`((DepartmentId:dcd5de48-594f-4cb7-88ee-2793fbdb6deb) OR (DepartmentId:{dcd5de48-594f-4cb7-88ee-2793fbdb6deb}))`

**Comment by YannickRe** [comment]
I think something got mixed up when you copy pasted (and trying out some hardcoded values), because `DepartmentId: {Site.ID}` doesn't normally expand to the or'ed statement.

The query you posted doesn't contain any tokens:
```https://tenant.sharepoint.com/sites/Inside/_api/search/query?QueryText=%27((DepartmentId:dcd5de48-594f-4cb7-88ee-2793fbdb6deb)%20OR%20(DepartmentId:{dcd5de48-594f-4cb7-88ee-2793fbdb6deb}))%27&QueryTemplate=%27{searchterms}%20(contentclass=STS_Site%20OR%20contentclass=STS_Web)%27&SelectProperties=%27SiteId,WebId,Path,DepartmentId,Title,IsHubSite%27&EnableQueryRules=false&RowLimit=1000&Properties=%27EnableDynamicGroups:true,EnableMultiGeoSearch:true%27&sortlist=%27QLogClicks:Descending%27&ClientType=%27SpClient%27
```
Decoded this shows:
- QueryText: `((DepartmentId:dcd5de48-594f-4cb7-88ee-2793fbdb6deb) OR (DepartmentId:{dcd5de48-594f-4cb7-88ee-2793fbdb6deb}))`
- QueryTemplate: `{searchterms} (contentclass=STS_Site OR contentclass=STS_Web)`

Query variables/tokens only expand when added to the QueryTemplate property.

**Comment by sympmarc** [comment]
I wonder if the properties aren't being fully flushed when I make changes? Or it could be a caching problem.

 I'm trying to use the DepartmentId:{Site.ID} in both the **Default search query** (property page 1) and the **Query template** (property page 2). This may be where I'm doing something stupid.

In words, what I want to do is allow the user to search for News pages within sites associated with the Hub Site. The page is within that Hub Site itself. On page load (before searching), I'd like to display all the News pages.

**Comment by YannickRe** [comment]
It’s a valid scenario:
- you’ll need both the Search Box and the Search Results webpart
- in Search results you connect to Search box, and optionally set a default query (page 1)
- in Search results you set `{searchTerms} PromotedState=2 DepartmentId:{{SiteCollection.ID}}`

That should be enough, but because of the issue I described, all tokens currently return the web id instead of site id. This is an SPO issue, not this webpart.

**Comment by sympmarc** [comment]
I've got it all wired up just fine, with a search box, refiners, and pagination. It all works a charm until I add the DepartmentId filter. I know it's @wobba's fault somehow.

**Comment by wobba** [comment]
@sympmarc see that second departmentid filter you have..it still has {} around it. Can you try the same query in the query tool?

I simplified away the implicit OR's and AND, and changed contentclass to use : and not = as I've seen this fail at times (not knowing why)

```
(DepartmentId:dcd5de48-594f-4cb7-88ee-2793fbdb6deb DepartmentId:dcd5de48-594f-4cb7-88ee-2793fbdb6deb) (contentclass:STS_Site contentclass:STS_Web)
```

**Comment by wobba** [comment]
@sympmarc Issue is that all of these resolve to the web id, not the sc id :( Tried in the query tool just now. 

` {Site.ID} {SiteCollection.ID} {Web.ID}`

This is clearly a bug, and someone should file it with Microsoft. If it had resolved correctly the following template should be working:

`DepartmentId:"{{SiteCollection.ID}}"` <- double braces due to the managed property containing them - weird shit.

The workaround as @YannickRe mentions is to use the PageContext variable, and both of these works fine when testing in my dev tenant at least.

```
{searchTerms} DepartmentId:{{PageContext.hubSiteId}} 
```
or on the hubsite itself:

```
{searchTerms} DepartmentId:{{PageContext.siteId}} 
```

**Comment by YannickRe** [comment]
Hmm, so you are seeing the same behavior as I wrote in https://github.com/SharePoint/sp-dev-solutions/issues/136#issuecomment-488121865

I’ll try to do a write up on the SP-dev-docs github later today.

**Comment by sympmarc** [comment]
Thanks, guys. i'll try the PageContext instead. If the wrong GUID is coming back, then it sorta makes sense I couldn't get it working.

I'll update to the latest, as I'm not sure I got @YannickRe's latest PR in my copy.

**Comment by wobba** [comment]
@sympmarc go with the dev branch to be sure :)

**Comment by sympmarc** [comment]
With the latest code, this works!
`{searchTerms} DepartmentId:{{PageContext.hubSiteId}} `
(dev branch)
