### ISSUE TITLE
Hash in URL when using Search box web part

### ISSUE THREAD

**Issue by mag210** [SharePoint/sp-dev-solutions#138]
#### Category
- [ ] Question
- [x ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

It should be possible to use the Searchbox webpart to send a user query to the existing SharePoint Modern Search Results page. To do this, the webpart is configured to send a query to a new page and the following URL is used:
https://[mytenant.sharepoint.com]/sites/[mySite]/_layouts/15/search.aspx/siteall?q=

Using previous versions of the webpart, the user typed query was successfully passed to the Results Page which shows the relevant search results. This enabled site admins to create a more prominent Search Box but to send users to the existing modern search results page. 

#### Observed Behavior
Using the latest release of this webpart (3.1.0.0) the search box injects a hash between the URL and the query text. This looks to be by design and may have another purpose, however, it does seem to prevent a search against the existing search results page from working. (Line 310 in existing repo): const url = `${this.props.pageUrl}#${encodeURIComponent(queryText)}`;

The url becomes like: _layouts/15/search.aspx/siteall?q=#test and as such SharePoint can't resolve the query 'test'. 

Removing the hash from the above line resolves the immediate issue and allows you to use the search box to search against the modern results page. However, does this prevent something else from working?

**Comment by FranckyC** [comment]
Hi @mag210. With latest version, the hash '#' is used instead the 'q' parameter by default. You can connect your target search results Web Part or search box to the Page Environment->Query String-> URL Fragment data source to grab the keywords. Then. in the other search box, use the page URL without query string parameters (ex: https://<site>/SitePages/Search-Page.aspx). The query text will be sent to the page with a hash.

**Comment by YannickRe** [comment]
@FranckyC that’s the case when you use “our” Search Results webpart, but it seems @mag210 wants to send queries to the default Search results page of SharePoint.m (which is hardcoded to use q parameter).
Correct @mag210?

**Comment by wobba** [comment]
That's how I read it as well, how to use pnp searchbox and have the query be sent with `q=<terms>` to an oob page.

**Comment by mag210** [comment]
@yannickRe that's correct yes. So it's a use case where we use the pnp Search box and have it point to the out of the box (modern) Search Results page. We were doing this with an older version of the webpart at the company I work for. The reason was to leverage the people search that out of the box handles quite nicely but have our own custom search box where we can control style, query suggestions etc.
It's a great feature that you can send results to another pnp search results web part and I will try this, but perhaps we need a toggle or option in the search box property pane to support both?

**Comment by YannickRe** [comment]
It has been on my radar to improve on this, allowing a choice between hash or querystring parameter (and giving the choice of parameter).
You are welcome to submit a pull request, otherwise I’ll look into it when time permits!

**Comment by FranckyC** [comment]
My bad, I just misunderstood ;). @YannickRe you're right, an option in the search box would be a good solution.

**Comment by YannickRe** [comment]
I’ll make the hash default 😉

**Comment by mag210** [comment]
Sounds good to me, will hopefully have some to look at a PR this evening. Agree hash should be default!

**Comment by YannickRe** [comment]
@mag210 I submitted a Pull Request that should give you the choice!

**Comment by mag210** [comment]
Thanks @YannickRe , I didn't get a chance to do this, so thanks for picking it up! I think a useful addition that adds to the flexibility of the webpart and means we can use it in conjunction with the out the box search results. This could be important if / when MS improve their modern search centre...

**Comment by wobba** [comment]
Now merged into dev.
