### ISSUE TITLE
Multilingual Pages: Cannot read property 'length' of undefined - MultilingualPanel

### ISSUE THREAD

**Issue by ChrPed** [SharePoint/sp-dev-solutions#144]
#### Category
- [ ] Question
- [x ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
When clicking the button "Language Details" the "Multilingual Page Details" should be shown

#### Observed Behavior
Nothing happens and the following error is logged in the console:
Message: TypeError: Cannot read property 'length' of undefined - MultilingualPanel

#### Steps to Reproduce
1. gulp bundle --ship
2. gulp package-solution --ship
3. add sppkg to AppCatalog
4. Add app to new Team site collection and wait for folders to be created
5. Create new page and move it to "English (United States)"
6. Edit page and click "Language Details"

Edit: I just noticed that the 4 site columns are not added to the content type

**Comment by h3nn3** [comment]
Thanks @ChrPed. This helped me to move on testing

**Comment by wobba** [comment]
Is this still an issue?

**Comment by ChrPed** [comment]
I just tried the latest build and it works now.
I'll close the issue.
