### ISSUE TITLE
"Expand filter by default" does not "take"

### ISSUE THREAD

**Issue by sympmarc** [SharePoint/sp-dev-solutions#145]
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
When the "Expand filter by default" checkbox is checked for a specific refiner, I expect it to be expanded on page load

#### Observed Behavior
Only the last refiner in the list seems to have the correct behavior (assuming all my refiners have the box checked).

#### Steps to Reproduce
Add a refiner Web Part, set all the refiners to expand, and view the results.

**Comment by FranckyC** [comment]
Hi @sympmarc. You're right, I was able to reproduce this issue. I'll try to fix this asap. Thanks for reporting!

**Comment by FranckyC** [comment]
@sympmarc should be fixed by now. You can pull my branch to test it out right now or wait for the merge in the modern-search-dev branch. cc @wobba. Thanks!
