### ISSUE TITLE
Help Please!!! Modern Search WebPart Not working on SharePoint on-premise 2019

### ISSUE THREAD

**Issue by RMcode** [SharePoint/sp-dev-solutions#147]
I am trying to use the Modern Search WebPart this to an on-premise SharePoint 2019 

I have created a new project for SharePoint 2019 on-prem which give me the 1.4.1 spfx version
I have also downgraded the React packages to react 15 from react 16 
as react 16 didn't work for me 

#### Category
- [ ] Bug

#### Expected or Desired Behavior
To be able to use this on SharePoint on-premise 2019 

#### Observed Behavior
it fails gulp serve, multiple errors due to downgrading packages 

#### Steps to Reproduce

git clone 
downgrade from @microsoft packages 1.7.1 to 1.4.1
downgrade 
 "dependencies": {
    "react": "16.3.2",
    "react-dom": "16.3.2",
    "@types/react": "16.4.2",
    "@types/react-dom": "16.0.5",

to

    "react": "15.4.2",
    "react-dom": "15.4.2",
    "@types/react": "0.14.46",
    "@types/react-dom": "0.14.18",

npm i 
gulp serve 

Please Help

**Comment by wobba** [comment]
For one, calm down.

Secondly we use features of SPFx which is not present in SPFx v1.4.1 which is the version SP2019 uses. Feel free to grab/fork the code and make it work for SPFx v1.4.1, as this will not be a focus for this project going forward.

**Comment by FranckyC** [comment]
@RMcode This Web Part relies heavily on the SPFx dynamic data feature which is not available in the 1.4.1 version unfortunately. Making this work for SharePoint on-prem would be a consequent work and not relevant for now. All we can do is wait for an SPFx version upgrade for On-Prem :(

**Comment by wobba** [comment]
(My gut feeling is that the likelihood of SPFx being updated for on-premises is probably slim unless there is a huge demand)

**Comment by digbar** [comment]
Hi @wobba and @FranckyC.

What would it be - if there are any - the best approach for creating 1.4.1 version?
As far as I can see, the only option would be to create a one big webpart with all of them.
At the moment I only need 'search-parts' solution, therefore, only Search box, Search result, so on...

Cheers

**Comment by wobba** [comment]
You can create your own custom logic to communicate between web parts as well. Probably some effort needed, but certainly doable if you think it's worth it.

**Comment by FranckyC** [comment]
The best option would be to keep individual Web Parts but with a custom connection mechanism. For instance using a Pub/Sub pattern. FYI, a new version is coming soon with a new base so I recommend you to wait before digging into this.

**Comment by digbar** [comment]
Thanks @wobba and @FranckyC. 
Good to know. Will wait then.
Cheers

**Comment by ypcode** [comment]
From a very high perspective, a pub/sub mechanism should be fairly easy to implement... I’ll give it a try! :)

**Comment by wobba** [comment]
@ypcode probably not as we don't want to support two bindings in the code. We're too far away from 1.4.1 imo, so I'd rather propose someone create a fork/new version for onprem specifically. The market is too small imo to invest in. (Personal opinion, not by any means Microsoft 🙂)

**Comment by ypcode** [comment]
That is mainly what I meant by guys :p some of you who might want to have a fork working without dynamic data :)

However, having the shared data logic layer abstract from the original code would help :D and  would require a bit of refactoring without probably changing any the core feature. But I don’t know the code base enough to firmly confirm :D

**Comment by Matej4386** [comment]
Hello everyone ;-) If you don't mind, I just want to share working solution for on-premise 2019 - https://github.com/Matej4386/SP2019-search
