### ISSUE TITLE
Deploying App into Sharepoint

### ISSUE THREAD

**Issue by dpc80111** [SharePoint/sp-dev-solutions#149]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ X] Question
- [ ] Bug
- [ ] Enhancement

#### Question

Where can I find step by step directions to deploy the app into our tenant for use.  I am not a developer and would like instructions to deploy or provision app.

Thanks

I wish it could be found and provisioned through https://provisioning.sharepointpnp.com/

Thanks for your contribution! Sharing is caring.

**Comment by wobba** [comment]
@dpc80111 which solution are you referring to in this repository?

**Comment by dpc80111** [comment]
My sincere apologies for not including that, its the Modern Search; react search refiners repository

**Comment by FranckyC** [comment]
@dpc80111 You can refer to the official SPFx documentation to generate the package:
- [Setup tenant](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-developer-tenant)
- [Setup dev env](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)

Basically you will need to bundle and generate the package using `gulp bundle --ship` and `gulp package-solution --ship`. Then upload the .sppkg to your tenant or site collection app catalog.

**Comment by wobba** [comment]
We're also planning to package up a release for download soon, which simplifies it a bit.

**Comment by dpc80111** [comment]
Thanks FranckyC but remember I am not a developer:)   Wobba, when you say soon, do you have an actual ETA on delivery?

**Comment by wobba** [comment]
Maybe tomorrow actually.

**Comment by wobba** [comment]
Release published https://github.com/SharePoint/sp-dev-solutions/releases/tag/v3.3.2

**Comment by dpc80111** [comment]
Morning, was a package file ever created for download?

**Comment by wobba** [comment]
@dpc80111 https://github.com/SharePoint/sp-dev-solutions/releases

**Comment by dpc80111** [comment]
The Pagination Web part is not rendering as it does in the video. How can we update that?

**Comment by FranckyC** [comment]
@dpc80111 What's the behavior right now? Can you elaborate?

**Comment by FranckyC** [comment]
You new to connect both ways (Search -> Pagination + Pagination -> Search).

**Comment by dpc80111** [comment]
![paginationimage](https://user-images.githubusercontent.com/48605275/57808745-3fd41300-7721-11e9-91cb-fb5f62945845.png)


No icon prior to number and weird character after numbers.  Search -> Pagination + Pagination -> Search is set.

**Comment by dpc80111** [comment]
PS: This is from the Packaged solution

**Comment by FranckyC** [comment]
Do other components work as expected (icons, etc.)? Can you try in a private window also? It seems to be a Office UI Fabric icons issue.

**Comment by dpc80111** [comment]
I cleared my browsers and it looks correct now. Thank you

**Comment by FranckyC** [comment]
@wobba Can close this one I guess.
