### ISSUE TITLE
Add User Profile Properties to Modern Search

### ISSUE THREAD

**Issue by sympmarc** [SharePoint/sp-dev-solutions#150]
#### Category
- [ ] Question
- [ ] Bug
- [x] Enhancement

#### Desired Behavior
In the Modern Search Web Part, we can specify KQL with tokens for the current user. However, those tokens are limited to what is already in the page (User.Email, User.Name, etc.) There are many use cases where we would like to filter based on the user's Department or Location - data in the User Profile.

The goal would be to extend the User tokens to allow User Profile properties. If one of those tokens was used, the Web Part would fetch the User Profile, parse out the property value(s) and replace it in the query. 

We are planning to build this for a client project, but if it showed up first... :)

**Comment by FranckyC** [comment]
Good suggestion @sympmarc. Put it on the roadmap. Feel free to make a PR if you have something already ;)

**Comment by wobba** [comment]
This should already work as it is part of the oob query variable functionality. If this fails for some reason, then a support ticket might be the better way(?) instead of reimplementing this client side.

**Comment by sympmarc** [comment]
Could you explain how it should work or point me to something in the docs?

**Comment by sympmarc** [comment]
Duh. This:

{User.property} | Any property from the user profile of the user who issued the query — for example, SPS-Interests, including custom properties.
-- | --

Will test it out.

**Comment by FranckyC** [comment]
Didn't know it actually already supported. Good to know then ;)

**Comment by wobba** [comment]
All in
https://www.techmikael.com/2014/05/s15e03-query-variables-constant-trouble.html
;)

tor. 9. mai 2019 kl. 21:43 skrev Franck Cornu <notifications@github.com>:

**Comment by YannickRe** [comment]
I tested all I tested all the [out of the box search query variables](https://docs.microsoft.com/en-us/sharepoint/technical-reference/query-variables) in PR https://github.com/SharePoint/sp-dev-solutions/pull/85 . Note that not ALL the tokens from on-premises work, but those in the readme are all tested!

**Comment by FranckyC** [comment]
@sympmarc can we close this one or you still have issues?

**Comment by sympmarc** [comment]
It works just fine, including with custom properties. Thanks for the help!
