### ISSUE TITLE
[ModernSearch] Norweigan text in CodeRenderer

### ISSUE THREAD

**Issue by Kristofferkirk** [SharePoint/sp-dev-solutions#153]
#### Category
- [ ] Question
- [ ] Bug
- [X] Enhancement

#### Expected or Desired Behavior
Noticed that in react-search-refiners-renderer/src/extensions/codeRenderer/SearchResults/SearchResults.tsx  on line 25, that it renders 'Updated X days ago' in Norweigan : 'Oppdatert for X days ago'. I suppose it would be better for non-norweigans that it's in english instead. 😄

**Comment by wobba** [comment]
Thank you and fixed :)
