### ISSUE TITLE
[ModernSearch] Webpart crashes when results (site titles) contains special characters error 400

### ISSUE THREAD

**Issue by Niekoesj** [SharePoint/sp-dev-solutions#158]
#### Category
- [x] Bug

#### Expected or Desired Behavior
When the results contains sites with special characters in the site title, the webparts shouldn't crash.

#### Observed Behavior
When the results of the query contains a sitecollection (with a special character in the title), the webpart crashes with an error. Error 400
"A potentially dangerous request.path value was detected from the client."
https://i.imgur.com/oNzk9ql.png

#### Steps to Reproduce
Create a sitecollection with the title: ABC -> 123
The arrow -> are the special characters...  Then try to display this site in the filter query. It will end up with an error: https://i.imgur.com/oNzk9ql.png

**Comment by FranckyC** [comment]
Hi @Niekoesj Unfortunately, I'm not able to reproduce this issue

![image](https://user-images.githubusercontent.com/5659122/57872335-7705fb00-77d9-11e9-8acb-3558841920f6.png)

Do you use the default templates (List/Tiles)? Can you debug the REST call in the browser network tab to see what happens?

**Comment by FranckyC** [comment]
@Niekoesj Any news about this?
