### ISSUE TITLE
Using apostrophe in search box not working

### ISSUE THREAD

**Issue by coupalm** [SharePoint/sp-dev-solutions#159]
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Being able to search for a term containing an apostrophe

#### Observed Behavior
If I search something like: Prud'homme, it returns nothing.

#### Steps to Reproduce
Nothing special

The way to solved this issue was to set the search query language preference in classic search:
https://blogs.msdn.microsoft.com/opal/2010/06/28/multilingual-search-in-sharepoint-server-2010-and-fast-search-server-2010/

**Comment by FranckyC** [comment]
Hi @coupalm . Quickly, can you open the network tab and see the transformed query in the REST call to see what it looks like?

**Comment by FranckyC** [comment]
Hi @coupalm I'm working on it. I'll add a query language parameter

**Comment by FranckyC** [comment]
@coupalm it will be resolved in the june release.

**Comment by coupalm** [comment]
@FranckyC , sorry for late response.. ok, thanks!
Bonne journée!
