### ISSUE TITLE
 Modern Search v3.3.2 package

### ISSUE THREAD

**Issue by dpc80111** [SharePoint/sp-dev-solutions#160]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
-[x] Question
- [ ] Bug
- [ ] Enhancement

Thank you for the Modern Search v3.3.2 package!  Will that package be updated with each code version release?

**Comment by FranckyC** [comment]
@dpc80111 We have now monthly releases so yes. You'll get a new version June 10th.

**Comment by FranckyC** [comment]
@wobba you can close this one
