### ISSUE TITLE
Modern Search - Query Rules for result block dont seem to render

### ISSUE THREAD

**Issue by dpc80111** [SharePoint/sp-dev-solutions#161]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [X ] Question
- [X ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Show result blocks from Query Rule in search result section of the web part

#### Observed Behavior
Not showing
![Queryresults](https://user-images.githubusercontent.com/48605275/57884882-efbf8400-77e6-11e9-98b9-e8f3a289dd51.png)

#### Steps to Reproduce
Add and redo Query Rule in SharePoint tenant admin query rule section

Thanks for your contribution! Sharing is caring.

**Comment by FranckyC** [comment]
Hi @dpc80111 For now, only promoted results are supported, not result blocks. This is an expected behavior. Sorry.

**Comment by dpc80111** [comment]
Ok, ty. Are you looking to add that functionality in the near future?

**Comment by FranckyC** [comment]
Not in the roadmap yet. Don't think we will tackle this soon unfortunately.
