### ISSUE TITLE
Reduce Results

### ISSUE THREAD

**Issue by dpc80111** [SharePoint/sp-dev-solutions#164]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ X] Question
- [ ] Bug
- [ ] Enhancement

#### Expected 
Is there any way to either reduce refiner (filetype) to x,y,z,a,b or not showing specific result like apsx pages, etc...

**Comment by wobba** [comment]
@dpc80111 You can exclude the filetypes you don't want in the initial query via the query template for example.

`-FileType:aspx -FileType:docx` or similar.
