### ISSUE TITLE
[Modern Search] Translation issue (week days)

### ISSUE THREAD

**Issue by BraunJonathan** [SharePoint/sp-dev-solutions#171]
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
First leters for week days should be D, L, M, M, J, V, S

#### Observed Behavior
These are : D, M, M, J, V, V, S

#### Steps to Reproduce
just look at the calendar ;-)

I dont have a connected environnement right now otherwise i would have submitted a PR for this.
It's located in the fr-fr.js file in searchRefiners subdirectory

**Comment by FranckyC** [comment]
Thanks for reporting @BraunJonathan. I will take a look. You can also submit a PR to fix this ;)

**Comment by FranckyC** [comment]
Should be resolved in the next release.
