### ISSUE TITLE
query string passed as # when configuring search box for Send query for to a new page., while navigating to other pages i.e when navigating with search vertical the query string passed as ?q=.

### ISSUE THREAD

**Issue by Ashutosh2019** [SharePoint/sp-dev-solutions#173]
- [ ] Bug

#### Expected or Desired Behavior
Ideal scenario- Configuring Search box for home page. Redirecting the key word to be shown in next page. Search vertical to navigate next search category.

When redirecting search from homepage to next page, the query string passed as #, while navigating to other pages i.e when navigating with search vertical the query string passed as ?q=.

This difference with query sting miss the uniformity and search data loss when navigating backward. 

#### Observed Behavior
When redirecting search from homepage to next page, the query string passed as #, while other pages i.e when navigating with search vertical the query string passed as ?q=.

This difference misses the uniformity and search data loss when navigating backward. 

#### Steps to Reproduce
Configure search box in one page. Configure for Send query for to a new page. Next page configures search box, search navigation, search result, filter, paging. In search navigation configure another search page. 

When redirecting search from homepage to next page, the query string passed as #, while navigating to other pages i.e when navigating with search vertical the query string passed as ?q=.

Thanks for your contribution! Sharing is caring.

**Comment by YannickRe** [comment]
In the modern-Search-dev branch I added the opportunity to choose how the query as passed: as hash or with a query string parameter of your choice.

Does that solve your issue?

**Comment by Ashutosh2019** [comment]
Excellent, Thank you. 
Yes it does solve my issue. Do I have to get the latest code ?

**Comment by YannickRe** [comment]
You can get the latest code from the modern-Search-dev branch and build & package it yourself. You can also wait a couple of days until all code is merged to master and we make a new package available!
