### ISSUE TITLE
Latest Code shows managed metadata tags ID's along with name in search refiners

### ISSUE THREAD

**Issue by Ashutosh2019** [SharePoint/sp-dev-solutions#174]
#### Category

- [ ] Bug

#### Expected or Desired Behavior
When showing search refiner for all owstaxidmetadataalltagsinfo (Managed Metadata) it should render the name of the column values.

#### Observed Behavior

When showing search refiner for all owstaxidmetadataalltagsinfo (Managed Metadata) it shows ID along with name. For ex- L0|#04e801f7d-b242-4518-acf4-dafe2fd0f46e|Hello Check (1)
It could have rendered as Hello Check(1) . But it is getting rendered with unexpected L0|#04e801f7d-b242-4518-acf4-dafe2fd0f46e.

#### Steps to Reproduce
Create New term set, new term. Create a library column out the the managed metadata column. Configure the search web parts along with search refiner. Where the refiner show all Tags. Check the values which renders is like - L0|#04e801f7d-b242-4518-acf4-dafe2fd0f46e|Hello Check (1) in the new version.

It was all working as expected in previous versions. 

Thanks for your contribution! Sharing is caring.

**Comment by FranckyC** [comment]
Hi @Ashutosh2019. Is the localization flag enabled in the WP settings?

**Comment by Ashutosh2019** [comment]
Checking one more time with the old verion (3.0.4.0), if it has same issue.

**Comment by Ashutosh2019** [comment]
Yes, it's localization flag configuration issue. Thank you for the help.
