### ISSUE TITLE
Changing "owstaxidmetadataalltagsinfo" to "RefinableString" in the Display template, the crawled property which are mapped not reflecting.

### ISSUE THREAD

**Issue by Ashutosh2019** [SharePoint/sp-dev-solutions#176]
#### Category
- [ ] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Trying to show custom metadata in place of "owstaxidmetadataalltagsinfo". Mapped all the custom column crawled property to RefinableString managed property and trying to show the values for the Search item. Changed "owstaxidmetadataalltagsinfo" to "RefinableString" in the Display template but the values are not reflecting.

#### Observed Behavior
When trying to show custom metadata in place of "owstaxidmetadataalltagsinfo". Mapped all the custom column crawled property to RefinableString managed property and trying to show the values for the Search item. Changed "owstaxidmetadataalltagsinfo" to "RefinableString" in the Display template but the values are not reflecting.

#### Steps to Reproduce
Create custom columns, map the custom column crawled property to "RefinableString" managed property. Changed "owstaxidmetadataalltagsinfo" to "RefinableString" in the Display template but the values are not reflecting.

Thanks for your contribution! Sharing is caring.

**Comment by wobba** [comment]
Can you verify that the data in `RefinableString` are equal to that of `owstaxidmetadataalltagsinfo`, or do they look different?

**Comment by FranckyC** [comment]
Hi @Ashutosh2019, so you want aggregate multiple crawled properties to a single RefinableString managed property, is that right? In this case, the issue could be a format issue. As pointed out by @wobba , compare the MP content to see if it is the same as `owstaxidmetadataalltagsinfo`. Honestly, I didn't test this scenario with multiple values. Why you can't use the `owstaxidmetadataalltagsinfo` MP directly or use one ows_taxid crawled property by MP ?

**Comment by Ashutosh2019** [comment]
Hi @wobba and @FranckyC ,  I am trying to aggregate multiple custom columns (not managed metadata column) crawled propertied  to a single RefinableString managed property. 

I have checked RefinableString managed property with owstaxidmetadataalltagsinfo, there is no difference. But only thing I suspect, owstaxidmetadataalltagsinfo is a default MP where all your managed metadata columns crawled property gets associated by default. Is there anything in code which renders the default template for out of box MP and need to customize if adding a new MP?

**Comment by wobba** [comment]
@Ashutosh2019 can you verify you are loading the `RefinableStringXX` property in the webpart configuration? And you already verified that the  `RefinableStringXX` property has a value using for example the search query tool(?) as I understand it.

**Comment by Ashutosh2019** [comment]
@wobba, Thank you so much. You guys are awesome. I am still scratching my head, how I missed this configuration. 

This works absolutely fine.
