### ISSUE TITLE
Default search query not working when specifying multiple paths ( or more conditions)

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-solutions#177]
I want to get data from multiple sites in one search query, but it is not working. It was working earlier. After i updated the solution to latest , it stopped working.
**Default search query**
path:https://dev.sharepoint.com/teams/Sales* OR path:https://dev.sharepoint.com/sites/Sales*

**Comment by wobba** [comment]
@harshdamaniahd you can skip the `OR`, also can you inspect the JSON being returned and see what the transformed query coming back is?

**Comment by FranckyC** [comment]
Hi @harshdamaniahd, can you check the query template in the settings so ensure the default Path{Site} is not present? Also, you can use the [Search Query Tool](https://github.com/SharePoint/PnP-Tools/tree/master/Solutions/SharePoint.Search.QueryTool) utility to compare your query and see if it actually returns results wih the same settings.

**Comment by harshdamaniahd** [comment]
Got it i had this query variable that was causing the trouble {Site}
![image](https://user-images.githubusercontent.com/11780473/58960998-97a5ed00-87a8-11e9-923e-a8c800084e8a.png)
Closing it ..thanks.
