### ISSUE TITLE
Localization query

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-solutions#180]
I had currently configured mapping using ows_Columname as shown below:
![image](https://user-images.githubusercontent.com/11780473/59098297-2ab56300-8920-11e9-8de7-6777df7bf85e.png)
to support localization, i will have to change it to
![image](https://user-images.githubusercontent.com/11780473/59098363-589aa780-8920-11e9-935f-164d079f9f17.png)
If i am making this change, after changing it to ows_taxid_country, i will have to reindex the site by going into site settings
![image](https://user-images.githubusercontent.com/11780473/59098471-add6b900-8920-11e9-9608-f90743829b6d.png)

Is there anything else i need to take care of

**Comment by FranckyC** [comment]
Hi @harshdamaniahd, you should be ok. Don't forget to turn on the localization flag in the WP settings afterwards.

**Comment by harshdamaniahd** [comment]
Yep. I checked this today. I just had to reindex the site.
