### ISSUE TITLE
Release notes 3.4.0

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-solutions#181]
The may release was v3.3.2. Anything I'm missing in the change log for v.3.4.0.0?

Changes: 
* Updated to SPFx v1.8.2
* Added query language setting

Fixes:
* Translations
* Improved loading placeholders
* Improved hash paramater change handling

@FranckyC @YannickRe

**Comment by YannickRe** [comment]
Seems like you’ve got it all.
