### ISSUE TITLE
Tags in Search Results not displaying correctly when Sorting is applied

### ISSUE THREAD

**Issue by murphym215** [SharePoint/sp-dev-solutions#182]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [X ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
I want to add Sorting functionality to my search results.  When a user selects a sorting option, their results should sort and any Tags associated with the items should remain readable.

#### Observed Behavior
When I select a field to sort on from the "Select a field" menu in the results webpart, the results will sort, however, the Tags will no longer be readable, instead they are showing the full id like this:  L0|#05184cf56-d646-4a03-8283-8cbcae9d44aa|Educator Pay;L0|#02974b50e-ac88-472c-b092-82ff4a1c0999|Higher Education;L0|#044807cbf-b3ba-4a21-9856-f2eceda48c51|Higher Ed Faculty.  See Attached screenshots.

#### Steps to Reproduce
Add a Search Results webpart and Refiners webpart to a page.  Map crawled properties to RefinableStrings, use them in the Sortable fields section.  Select a field to sort on.

![searchError1](https://user-images.githubusercontent.com/29923417/59229139-99f0b880-8ba7-11e9-8f50-4b090a373087.PNG)
![searchError2](https://user-images.githubusercontent.com/29923417/59229141-9d843f80-8ba7-11e9-9559-aa1c32813a88.PNG)

**Comment by FranckyC** [comment]
Hi @murphym215, good catch! I was able to reproduce this issue. I'll fix this ASAP. Thanks.

**Comment by murphym215** [comment]
Thanks for the update.  I deployed the latest version 3.4.0.0 and used Update-PnPApp PowerShell cmdlet to update.  However, managed metadata tags are still showing full id when a sort is applied.  I am mapping a managed metadata column named Topic to RefinableString00 using ows_Topic.  I have also tried mapping ows_taxid_Topic. Additionally, I have tried using Created.  Either way, the initial results render fine, but are still showing full id when sort is applied. Perhaps I am doing something wrong?  Any suggestions and/help please?  I can provide more screen shots if needed.

**Comment by FranckyC** [comment]
@murphym215 did you build the package from the latest modern-search-dev branch?

**Comment by murphym215** [comment]
I actually got it from master.  When I built it, it was showing 3.4.0.0 as the version.  I just got it from dev branch and it seems to be working now.  thanks.
