### ISSUE TITLE
Is it possible to get library name in search template

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-solutions#183]
Is it possible to get library name like here "QuotationandPrice"
![image](https://user-images.githubusercontent.com/11780473/59281230-30d07a00-8c67-11e9-8edb-faaba8808896.png)

**Comment by harshdamaniahd** [comment]
Actually i got the path using "Path" attribute
https://*.sharepoint.com/teams/Sales/QuotationAndPrice/Fremsendingskalkulator.xlsx

**Comment by FranckyC** [comment]
Hi @harshdamaniahd , unfortunately, I don't hink there is a managed property available in the search schema to get this information directly. All you can get is the ListID or the path. If your library URL is the same as the display name, you could implement something in the template using Handlebars helpers to extract and format the token correctly.
