### ISSUE TITLE
Can i use theme color in custom html (handler)

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-solutions#184]
@FranckyC  if yes, how can i do that

**Comment by wobba** [comment]
In theory you should be able to use `ms-fontColor-themePrimary` etc, but I see we again have updated `@microsoft/sp-office-ui-fabric-core` to the latest version. If you downgrade to 1.6.0 it will work.

Not sure if downgrading again has any other implications, or if we should try to create a better solution.  We could either re-implement those classes or add support for using something like below which is used in the sass files:

`"[theme: themePrimary, default: #0078d7]"`

**Comment by harshdamaniahd** [comment]
Ok tried ms-[location]-[color]

and here are my observations
It takes the default blue color and not the actual theme color.

**Comment by wobba** [comment]
I know :) It's a bug. Revert to 1.6.0, rebuild and it works - just not sure if it has other implications.

**Comment by harshdamaniahd** [comment]
okay :-) no worries
