### ISSUE TITLE
Search Results Web Part Title Not Displaying

### ISSUE THREAD

**Issue by demowry** [SharePoint/sp-dev-solutions#185]
#### Category
- [ ] Question
- [ X ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Display the webpart title based on the entry put into the properties of the results web part.

#### Observed Behavior
The Title doesn't get displayed.

#### Steps to Reproduce
Add a title to the results web part, publish the page.

**Comment by FranckyC** [comment]
Hi @demowry, will be fixed in the next release. Thanks!
