### ISSUE TITLE
Can i expand User.<customproperty> to get all child terms in search query

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-solutions#186]
I have a custom property called business unit.
Each business unit has departments has child terms.
For eg :
Sales: Level 1
-->Department 1 : Level 2
-->Department 2 : Level 2

Now my business unit is set to Sales, so when i use {User.BusinessUnit} in search query it should get all items that belong to department 1 and department 2 and sales.
Like we can do here : 
GP0|#<term id> | Returns all items tagged with that term
GPP|#<term id> | Returns all items tagged with all childs of the term
GTSet|#<term set id> | Returns all items tagged with a term from the term set

**Comment by wobba** [comment]
You can use `{User.<Property>.ID}` or `{User.<Property>.IDWithChildren}` as mentioned in my post https://www.techmikael.com/2014/05/s15e03-query-variables-constant-trouble.html. Which means you can get the current tag with children, or the current tag only. You cannot scope to parent terms.

**Comment by harshdamaniahd** [comment]
I tried the below query, but they all return same result
{User.<Property>.ID}  : Returns all items tagged with that term
{User.<Property>.IDWithChildren} : Returns all items tagged with that term
{User.<Property>} : Returns all items tagged with that term

I can verify that in search schema, I have mapped it to ows_taxId_Property

**Comment by harshdamaniahd** [comment]
I think that GPP|# is not working

**Comment by FranckyC** [comment]
Hi @harshdamaniahd, could it be related https://twitter.com/eliostruyf/status/1139123339354619910? Can you check the value of the managed property in the search index (using search query tool for instance)?

**Comment by harshdamaniahd** [comment]
@FranckyC I do have the search query tool, but did not understand what you need. Can you please tell me where to look in search query tool. 
![image](https://user-images.githubusercontent.com/11780473/59432544-df9bc400-8de7-11e9-9506-890e1973c83c.png)

**Comment by FranckyC** [comment]
Ok I see the value of RefinableString04 seems OK. Now can you inspect the search query in the REST call by opening the browser network tab?

**Comment by harshdamaniahd** [comment]
Do you mean the request payload ?
![image](https://user-images.githubusercontent.com/11780473/59434468-e593a400-8deb-11e9-9c0a-df579fbbb9bd.png)

**Comment by FranckyC** [comment]
OK and if you go with direct GPP|#<id> or GP0|#<id> tokens in the query, do you get correct results?

**Comment by harshdamaniahd** [comment]
GP0|# is working , GPP|# is not working

**Comment by harshdamaniahd** [comment]
One more thing when I put the query in search tool, i get 0 results for `{User.<Property>.IDWithChildren}`
![image](https://user-images.githubusercontent.com/11780473/59436578-31484c80-8df0-11e9-9208-0c03dc2f2c3b.png)


But when i put the same query in search webpart i get same result as below query
```

{User.<Property>.ID}  : Returns all items tagged with that term
{User.<Property>} : Returns all items tagged with that term
```
So in search wp there is no difference in any condition

**Comment by wobba** [comment]
@harshdamaniahd you need to put the query in the query template field, not the query text. Query variables expand from the the template field, not from the keyword field.

**Comment by RajputDeepak** [comment]
@wobba Can you please elaborate when you say "You cannot scope to parent terms." in above comment

**Comment by FranckyC** [comment]
@harshdamaniahd if you inspect items tagged with lower taxnomy levels like "Department 1", etc. in the search index, is the GPP token present for these items?

**Comment by wobba** [comment]
@RajputDeepak In a hierarchical termset

Parent
   Child 1
       Sub 1
   Child 2

If term "Child 1" is a tag used in a profile, you cannot get results for tags Child1+Sub1, not Parent and below.

**Comment by harshdamaniahd** [comment]
> @harshdamaniahd you need to put the query in the query template field, not the query text. Query variables expand from the the template field, not from the keyword field.

@wobba  I tried this as well , but still doesnt work
![image](https://user-images.githubusercontent.com/11780473/59439920-648dda00-8df6-11e9-8ef9-4035c1e39d90.png)

**Comment by harshdamaniahd** [comment]
> @harshdamaniahd if you inspect items tagged with lower taxnomy levels like "Department 1", etc. in the search index, is the GPP token present for these items?
I can see GPP
What i understood is this ? 
![image](https://user-images.githubusercontent.com/11780473/59440428-3e1c6e80-8df7-11e9-84ef-57fe5aca974b.png)

**Comment by FranckyC** [comment]
So in items tagged with lower taxonomy levels, you see the GPP token is set but when you query for  GPP|#<term_id> you don't get any result? Seems strange.

**Comment by harshdamaniahd** [comment]
Yes, GPP is not working
![image](https://user-images.githubusercontent.com/11780473/59441335-b59ecd80-8df8-11e9-977f-3e062ca5f572.png)

**Comment by FranckyC** [comment]
What if you do RefinableString04:GPP|#<term_id>?

**Comment by harshdamaniahd** [comment]
Thank you indeed, it worked

> What if you do RefinableString04:GPP|#<term_id>?

Yeh..finally it worked. Thank you very much :-) @FranckyC  & @wobba .
RefinableString04:{User.BusinessUnit.IdWithChildren} and this also works : RefinableString04:GPP|#<term_id

**Comment by FranckyC** [comment]
RefinableStringXXX managed properties are not 'Searchable' by default so it means their content is **not** included in the full-text index.

**Comment by harshdamaniahd** [comment]
Got it 👍

**Comment by FranckyC** [comment]
@wobba can close this one
