### ISSUE TITLE
Search results not working on classic page

### ISSUE THREAD

**Issue by colonelclaypoo** [SharePoint/sp-dev-solutions#189]
First of all, thank you for these awesome webparts.
I'm trying to add the search results webpart to a classic webpart or wiki page. Unfortunately, no results are displayed. It keeps on loading stating "Search results are being loaded":
![2019-06-17_12-44-10](https://user-images.githubusercontent.com/29123261/59599007-c6ec2080-90fd-11e9-9a93-f6226f02090d.png)

This behaviour is the same for either a classic webpart or wiki page.
However, once I enter the classic webpart configuration menu to configure the webpart it works just fine.

Any idea why it's only working in edit mode?

Thanks a lot.

**Comment by wobba** [comment]
Have to say I've never tried on a classic site before. If you open the browser debug console, any error message which sticks out?

**Comment by colonelclaypoo** [comment]
Good call!
I just checked. I compared inserting the search results webpart to inserting the modern highlighted content ootb webpart. What sticks out in the Chrome Dev Tools is this bit:

![1](https://user-images.githubusercontent.com/29123261/59603182-066c3a00-9109-11e9-84a4-c0e467c1a07c.png)

This error is not present with the highlighted content webpart. Unfortunately, my coding skills are near non-existant so I'm not able to interpret the error.

Thanks for your help.

**Comment by FranckyC** [comment]
Hi @colonelclaypoo, never tried in classic pages also :(. Quickly, this issue seems related to dynamic data. @wobba, does this feature supported in this mode?

**Comment by FranckyC** [comment]
Ok I have the answer https://github.com/SharePoint/sp-dev-docs/issues/2515. Unfortunately @colonelclaypoom this WP can't be used in classic pages (at least with a search box connected). You can try to use the 'Search Results' WP only.

**Comment by colonelclaypoo** [comment]
@FranckyC & @wobba, thank you for your help. Unfortunately, the search results webpart only also does exhibit the same behaviour. But that's okay, I will try a modern page with the SingleWebPartAppPage-layout to kind of resemble the classic experience we're still using. We appreciate this solution nonetheless, it's one of the best things I've come across in recent years. Keep up the good work.

**Comment by FranckyC** [comment]
Thanks @colonelclaypoo !
