### ISSUE TITLE
Search Results Web Part - Web Part Title Doesn't Display

### ISSUE THREAD

**Issue by sympmarc** [SharePoint/sp-dev-solutions#190]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
When I add a Web Part Title to the Search Results Web Part, I expect to see it in the UI.

#### Observed Behavior
No Title. :( I'm using the latest version: 3.4.0

#### Steps to Reproduce
Add a Web Part Title, save. No title.

**Comment by FranckyC** [comment]
Already resolved via #185. You can pull the latest modern-search-dev branch.

**Comment by sympmarc** [comment]
Sorry. I looked for another issue on this, but missed it. Thanks!
