### ISSUE TITLE
Searching any existing SharePoint document which has no Title (though same document can be searched with accuracy from OOTB Modern search)-  The search result is inconsistent

### ISSUE THREAD

**Issue by Ashutosh2019** [SharePoint/sp-dev-solutions#191]
#### Category

- [ ] Bug

#### Expected or Desired Behavior

Searching any existing SharePoint document with "Name" or "Title" it should return the result.

#### Observed Behavior

When Searching for Document which has no Title it didn't return the exact or related searched result. Even it doesn’t show the item in all the result as well. The search result is inconsistent.

#### Steps to Reproduce

I migrated a .xls file from a classic site with name "0415 Anthem Scorecard.xls". The file migrated with Name and without Title, When Searching with keyword "0415 Anthem Scorecard" it doesn't return any value.

Whereas I have other documents in the migrated to library, some documents show result, and some doesn’t return in search result. The search result is inconsistent.

The same key word when searched from out of box modern doc library it gives the exact result. Even in the default Modern search also it gives the exact result.

For your reference below are two different queries in the network tab to see what is going on:

Your search query: 

https://xxxxxx.sharepoint.com/sites/Collaborationportal/_api/search/suggest?querytext=%270415%20Anthem%20Scorecard%27&inumberofquerysuggestions=10&fprequerysuggestions=true&fhithighlighting=true&culture=1033&fprefixmatchallterms=true

Out of box Modern Search query: 

https://xxxxxx.sharepoint.com/sites/Collaborationportal/_api/search/query?querytext=%27(0415%20Anthem%20Scorecard)%27&querytemplate=%27{searchTerms}%20siteId:{e0fda583-0ebd-43a5-9381-18282a888bb4}%20(webId:{018a6b37-4333-4508-a207-aaba7f86e6cd}%20OR%20webId:018a6b37-4333-4508-a207-aaba7f86e6cd)%20path:%22https%3A%2F%2Fthinkwgroup.sharepoint.com%2Fsites%2FSPUATCollaborationportal%2FShared%2520Documents%2FGeneral%22%20ContentTypeId:0x0*%27&selectproperties=%27editorowsuser,authorowsuser,Filename,SPSiteURL,Title,ParentLink,ListItemID,ListID,contentclass,IsDocument,IsContainer,FileExtension,SecondaryFileExtension,OriginalPath,DefaultEncodingURL,ServerRedirectedURL,ServerRedirectedPreviewURL,LastModifiedTime,SharedWithUsersOWSUser,HitHighlightedSummary%27&SummaryLength=100&RowLimit=6&culture=1033&BypassResultTypes=true&EnableQueryRules=false&ProcessBestBets=false&ProcessPersonalFavorites=false&clienttype=%27SPListInline%27

Thanks for your contribution! Sharing is caring.

**Comment by FranckyC** [comment]
Hi @Ashutosh2019, not sure I understand. What searches do you compare? Modern Search WP search vs Library builtin search? The query you mentionned don't use the same endpoint (/suggest vs /query) so I guess this is normal they are not giving the same results.

**Comment by Ashutosh2019** [comment]
Hi @FranckyC, 
I am comparing custom Modern Search WP search and build in Modern search. 

I understand the endpoint (/suggest vs /query) varies in case of searching inside library and search custom Modern Search WP search.

Couldn't able to trace the Search query at that point, below are the two different queries:

Custom Modern Search WP search query:

https://xxxxxx.sharepoint.com/sites/Collaborationportal/_api/search/suggest?querytext=%270415%20Anthem%20Scorecard%27&inumberofquerysuggestions=10&fprequerysuggestions=true&fhithighlighting=true&culture=1033&fprefixmatchallterms=true


Build in Modern search query: 

https://xxxxx.sharepoint.com/search/_api/search/suggest?querytext=%270415%20Anthem%20Scorecard%27&inumberofquerysuggestions=3&culture=1033&inumberofresultsuggestions=0&fprequerysuggestions=true&fhithighlighting=true&fcapitalizefirstletters=false&fprefixmatchallterms=false&showpeoplenamesuggestions=false

I can find my results in Build in Modern search but not in Custom Modern Search WP search.

**Comment by wobba** [comment]
@Ashutosh2019 we are correct, oob is wrong if you execute both from the root sc(?) Suggestions are per spec scoped to the sc where you execute the query against. We could perhaps add a toggle to query suggestions from the root or any other arbitrary sc......

For the oob search, what URL are you searching from, and which search box are you using?

**Comment by FranckyC** [comment]
@Ashutosh2019  From where did you monitor the search calls? The 'suggest' api endpoint is only used when suggestions are turned on for the Modern Search WP and it actually does not return results but only phrases in a predefined list you configured (see [https://docs.microsoft.com/en-us/sharepoint/search/manage-query-suggestions](url)). Suggestions **are not built automatically** with this WP so the list always remains the same.

**Comment by Ashutosh2019** [comment]
@FranckyC , For the oob search, I am searching from both current SC and from Organization path, both the cases I am getting the search result. The search uses the default search box.

But in Modern Search WP, I am using the Modern Search WP search box and Modern Search WP search result web part.

The difference I observe some documents are not giving any result in Modern Search WP where as with the same key word it gives result in oob search.

**Comment by wobba** [comment]
@Ashutosh2019 are you talking about the search box in the suite header? Feel free to post a screenshot of which oob feature you are talking about.

**Comment by FranckyC** [comment]
Yep I think screenshots could help ;)

**Comment by Ashutosh2019** [comment]
![Search_Modern Search WP](https://user-images.githubusercontent.com/48927183/59625390-c92e9900-9156-11e9-9ff6-498d7823cacb.jpg)
![Search_OOTB](https://user-images.githubusercontent.com/48927183/59625398-cd5ab680-9156-11e9-8273-15ad908fd81c.jpg)

The Same key word giving different results.

**Comment by Ashutosh2019** [comment]
I did deep dive with the setup, it might be interfering "query rules".
When the query rules are enabled to exclude few sites from search either from the Modern Search WP or from the site collection, in both the cases the results shows very weird way.

**Comment by FranckyC** [comment]
@Ashutosh2019 By default the search is scoped to the current site in the Modern Search WP (Path:{Site}). You could check the query template to see if anything could interfer.

**Comment by Ashutosh2019** [comment]
@FranckyC , I have made it Query template scoped for {searchTerms}, which give me result of all data from local shareppoint result. 

If Create a site collection Query Rule, the Modern Search WP doesn't gives me exact result.

**Comment by wobba** [comment]
@Ashutosh2019 in theory they should be the same for the same scope. Would be interesting if you tried the search query tool or `Submit-PnPSearchQuery` and see what the result is.

You cannot really look at the REST calls as the oob page now uses a different API to search thru, not the SharePoint search API. Which makes it all the harder to troubleshoot.

**Comment by Ashutosh2019** [comment]
@wobba , you are correct. I finally found it's problem with query rules and got it fixed with a minor tweak. 
Thank you @FranckyC and @wobba, you guys real Savior.
