### ISSUE TITLE
Modern Search - time zones?

### ISSUE THREAD

**Issue by sympmarc** [SharePoint/sp-dev-solutions#192]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

I'm wondering if you have any suggestions on how to handle time zone offsets in the Handlebars templates. For example, if I get this value back from a query:
```
{Key: "EventDateOWSDATE", Value: "2019-06-10T00:00:00.0000000Z", ValueType: "Edm.DateTime"}
```
and then use getDate:
`{{getDate EventDateOWSDATE "ddd, MMM DD"}}`

I'll get the value of EventDateOWSDATE, but the time offset means it may show the wrong date. In this case, I may see "Sun, Jun 09" when it should be "Mon, Jun 10".

How do you guys handle this? I know getDate lets format dates the way we want them, but what about time zone offsets?

**Comment by wobba** [comment]
Good question. Would you want it adjusted to the web's time zone or the users time zone, or maybe a parameter that you pass to `getDate`?

**Comment by sympmarc** [comment]
I don't remember what classic search display templates did. Anything?

Time zones are always a mess to work with. I think most of the time, we want to see the user's time zone. I can't figure out if getDate gives me any options already or not.

**Comment by wobba** [comment]
@sympmarc Tested now and the date for one item for me is 1pm, and shows as 3pm by default in our webpart. Debugging I see that it does a `new Date()` which for me in my browser returns `Tue Jun 18 2019 08:23:01 GMT+0200 (Central European Summer Time)` and uses that to adjust the timezone. So should be ok then?

**Comment by sympmarc** [comment]
Here's what I get with getDate when it's around the date boundary. I'm working in GMT-0400 (Eastern Daylight Time.

Snippet from the template I submitted in the other issue:
``` Javascript
 {{EventDateOWSDATE}}::
 {{getDate EventDateOWSDATE "ddd, MMM DD hh:mm"}}, All Day
```
yields:
  2019-06-10T00:00:00.0000000Z:: Sun, Jun 09 08:00, All Day

So the offset pushes the formatted date back into the previous day. 

Doing it manually in the console:
``` Javascript
new Date("2019-06-10T00:00:00.0000000Z")
Sun Jun 09 2019 20:00:00 GMT-0400 (Eastern Daylight Time)
```
Maybe I'm doing something dumb?

**Comment by wobba** [comment]
@sympmarc what is the timezone setting on your site? If you enter event date X, what i the mp value?

Maybe we should add an option to `getDate` which just displays the Z date as is with no adjustment?

**Comment by sympmarc** [comment]
GMT-0400 (Eastern Daylight Time)

I think adding that option would be useful. Basically, it's like a split on the T and formatting the date to look pretty - without adjusting for time zone. Whenever we have a Date/Time column set to Date only, we have this problem.

**Comment by wobba** [comment]
@sympmarc Added an int as 0/1/2 for time handling. Do you think this is sufficient?

* 0 = default
* 1 = ignore Z and format as browsers time zone
* 2 = set time as 00:00:00 and handle as browsers time zone

**Comment by sympmarc** [comment]
I'm not sure what the differences are. 2 seems to address my use case, though with **Date Only** columns, we get a value like `2019-06-10T00:00:00.0000000Z` anyway.

For clarity, what would happen to that value in each of the scenarios? Let's say I'm in EDT ( GMT-0400 (Eastern Daylight Time) - as I am). I think you're saying:
* 0 = default `Sun Jun 09 2019 20:00:00`
* 1 = ignore Z and format as browsers time zone `Mon Jun 10 2019 00:00:00`
* 2 = set time as 00:00:00 and handle as browsers time zone `Mon Jun 10 2019 00:00:00`

**Comment by wobba** [comment]
Say you have 1am zero time defined

2019-06-10T01:00:00.0000000Z

If browser is GMT-0400

* 0 = 2019-06-09 9pm
* 1 = 2019-06-10 1am
* 2 = 2019-06-10 12am

**Comment by wobba** [comment]
@sympmarc if you're happy with this and cannot thing of another scenario I should add, I'll close this. One could be to format as the sites timezone, or as the users profile timezone perhaps, if those are easy lookups(?).

**Comment by wobba** [comment]
@sympmarc wasn't too hard, and noticed you have a post on timezone data as well :) Option 3 and 4 added.
