### ISSUE TITLE
File without Title shows with 1st line of text in the file instated of File name 

### ISSUE THREAD

**Issue by Ashutosh2019** [SharePoint/sp-dev-solutions#194]
#### Category

- [ ] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

When searching for a document which doesn't have a title. It should display with the filename, it is default behavior of OOTB search. But same is not applicable in Modern Search Web Part.

#### Observed Behavior

When you search for a document without having Title, it shows in the search result with title of 1st line text in the document.

#### Steps to Reproduce
Create a word document put same text in the 1st line, give it some name and save it without providing Title . Search the document, you will find the document with title having 1st line of text instead of file name.

Thanks for your contribution! Sharing is caring.

**Comment by wobba** [comment]
If you use the Title managed property, we display the value of that. Any other value you want to use or remap the cp order for Title is up to you. We don't do anything special with any mp in the web part.
