### ISSUE TITLE
Search Box WebPart with "Send Query to a new page" behave different on clicking "X" (Clear).

### ISSUE THREAD

**Issue by Ashutosh2019** [SharePoint/sp-dev-solutions#198]
#### Category

- [ ] Bug

#### Expected or Desired Behavior
Configuring Search Box web part with "Send Query to a new page". When entering some values in search box and click on Clear button, instead of clearing the text, it redirects to other page.

#### Observed Behavior
Configuring Search Box web part with "Send Query to a new page". When entering some values in search box and click on Clear button, instead of clearing the text, it redirects to other page.

#### Steps to Reproduce
1) Configuring Search Box web part with "Send Query to a new page".
2) Enter search text the "X" button will appear to clear the text.
3) When you click on "X", instead of clearing the text it redirects to other page.

Thanks for your contribution! Sharing is caring.

**Comment by mag210** [comment]
@Ashutosh2019  I've also been able to re-produce this. The behavior only happens when Search web part is configured to send results to a new page. If it's not, then clear works as expected.

**Comment by YannickRe** [comment]
@Ashutosh2019 @mag210 Thanks for reporting, you are totally right. I have submitted a pull request to fix this in a future release.

**Comment by Ashutosh2019** [comment]
I have taken the latest and build it, I feel the issue still persists.

**Comment by YannickRe** [comment]
Did you use the modern-Search-dev branch? It’s not merged into master yet.

**Comment by Ashutosh2019** [comment]
@YannickRe ...no I have taken from master. I will take it from dev branch, Thank you.
