### ISSUE TITLE
Using search term with multiple pages and hops

### ISSUE THREAD

**Issue by dpc80111** [SharePoint/sp-dev-solutions#200]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [X ] Question
- [ ] Bug
- [ ] Enhancement

Is it possible to set up 3 hops using the same search term in the following manner?

Hope 1:  Search box parameters set to (send query to new page"
Hope 2:  Page Search box parameters set with (Page Environment, Query String, URL Fragment)
Hope 3:  Search Navigation  parameter set to ( Search Query) URL send to new Search page with Search box and  2 Search Result sets  

I tried to use different combinations of parameters under  (Page Environment, Query String, URL Fragment) but no luck.  

An help would be appreciated.

**Comment by YannickRe** [comment]
@dpc80111 I'm not completely sure what you are trying to achieve... Are you trying the following:
**Page1.aspx**: contains a Search Box Web Part, which sends the query to Page2.aspx (using URL Fragment)
**Page2.aspx**: contains a Search Box Web Part which takes the URL Fragment value as input (dynamic data). There is also a Search Navigation Web Part with a link to Page3.aspx to send the query (using URL Fragment)
**Page3.aspx": contains a Search Box Web Part which takes the value from URL Fragment (received from Page2.aspx) as input (dynamic data). You have two Search Result Web Parts which take the value from the Search Box Web Part as input.

Is my analysis correct?
If so, what is the issue you are experiencing?

**Comment by dpc80111** [comment]
Yes you have the analysis correct.  Screen shots on document.

Thanks you for the help
[ModernSearch3Hops.docx](https://github.com/SharePoint/sp-dev-solutions/files/3341025/ModernSearch3Hops.docx)

**Comment by YannickRe** [comment]
Problem is that the Search Navigation Web Part doesn’t have the ability to use URL Hash. It will always (it’s hardcoded) use querystring ?q= and append your query.

You can change the Search box on Page3 to read from QueryString instead of URL hash.
Other solution would be to change SearchBox on Page1 to send with QueryString “q”, adjust SearchBox on Page2 and Page3 to read from QueryString “q”. Your whole flow would then consistently use querystring.

**Comment by dpc80111** [comment]
Perfect that worked!

Another question if may.   

How do I show the URL field of the item, not url of the item ID.   The URL field is in the Resource Identifier (Result Source from a SharePoint list which has a Hyperlink firld.) 

Thank you

**Comment by wobba** [comment]
If your column is a URL site column you can use the auto mp for the column and one of the helper methods in the Readme to display the title or Url of the column value.

**Comment by dpc80111** [comment]
And would this be the correct entry since I didn't use a Site column

 <ul class="ms-List template_defaultList">
            {{#each items as |item|}}
                <li class="template_listItem" tabindex="0">
                    {{#> resultTypes}}
                        {{!-- The block below will be used as default item template if no result types matched --}}
                        <div class="template_result">
                                <img class="template_icon" src="{{IconSrc}}"/>
                                <div class="template_contentContainer">
                                    <span class="">{{getUrlField RefinableString102 "URL/Title"}}</span>
                                    <span class="">{{getSummary HitHighlightedSummary}}</span>

**Comment by wobba** [comment]
@dpc80111 Right now `getUrlField ` works with the automatic managed properties as they have both Title and URL stored in the property. When mapping manually I believe only the url is stored(?). Either way, you would use:

`{{getUrlField prop "URL"}}`

or

`{{getUrlField prop "Title"}}`

depending on if you wanted to display the title or the URL.

**Comment by dpc80111** [comment]
Thank I greatly appreciate all the help.
