### ISSUE TITLE
Pagination Issue?

### ISSUE THREAD

**Issue by gristy58** [SharePoint/sp-dev-solutions#203]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Pagination Webpart to progress Search Results

#### Observed Behavior
I have a search box webpart connected to search results webpart which has a pagination webpart connected to it.

The pagination webpart displays the correct number of pages. But nothing happens when changing page.

Is there extra configuration that is required?

#### Steps to Reproduce
Produce a search with more than 10 results. Click Page 2.

**Comment by colonelclaypoo** [comment]
gristy58, what was your fix? I'm experiencing the same issue currently. Thanks.

**Comment by gristy58** [comment]
Link it from both web parts not just the one

**Comment by colonelclaypoo** [comment]
> Link it from both web parts not just the one

Duh, obviously. Thanks, missed that for one search vertical.
