### ISSUE TITLE
react-search-refiners solution package

### ISSUE THREAD

**Issue by dpc80111** [SharePoint/sp-dev-solutions#204]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [x ] Question
- [ ] Bug
- [ x] Enhancement

Is there a solution package created for react-search-refiners solution?

**Comment by wobba** [comment]
Check out https://github.com/SharePoint/sp-dev-solutions/releases or clone the repo and ignore the other projects for source code. Is that what you are after?
