### ISSUE TITLE
Search Results - Refiner tags not rendered when applying sorting

### ISSUE THREAD

**Issue by colonelclaypoo** [SharePoint/sp-dev-solutions#205]
- [x] Bug?

Hello,
I noticed that applying a sort order when displaying *owstaxidmetadataalltagsinfo* to be available as a URL fragment / as refiner will break the translation - at least with my current configuration. Here's a screenshot of the result source/config.

![image](https://user-images.githubusercontent.com/29123261/60509477-47e61300-9ccd-11e9-936e-8773bf9e3cb1.png)

As soon as I choose a property from the sort box the tag *INSIDE Tipps & Tricks* will take the form as shown. So far I couldn't fingure out what's causing this to happen. However, changing the site collection language from German to English does not exhibit this issue.

Here's the config of the search box (switched to English to show settings):

![image](https://user-images.githubusercontent.com/29123261/60509928-6bf62400-9cce-11e9-80c7-3635ff820164.png)

I also tried mapping *ows_taxId_MetadataAllTagsInfo* to a RefinableString because I though enabling localization had something to do with it but it doesn't seem that way.

Ayn idea how to troubleshoot further

Thanks!

**Comment by FranckyC** [comment]
Hi, this issue has already been flagged twice and resolve since. See #202 and #182. Please take a look at closed issues first ;)

**Comment by wobba** [comment]
Does it only happen with this one term only? And could you provide the term(s) in both languages for testing? Also, what is the primary language of the termset?

**Comment by wobba** [comment]
Closing this as it's resolved in the dev branch.

**Comment by colonelclaypoo** [comment]
Sorry, I didn't mean to create a duplicate. I had started a search but must have used the wrong search term:
![image](https://user-images.githubusercontent.com/29123261/60512416-c8f4d880-9cd4-11e9-8aef-7e156a82bae5.png)

**Comment by FranckyC** [comment]
No worries ;)
