### ISSUE TITLE
Page Refresh Required to show results

### ISSUE THREAD

**Issue by dpc80111** [SharePoint/sp-dev-solutions#208]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [x ] Question
- [x ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Results show by search term from search box settings: Page Environ, Q String>Q Para and q properties from Search navigation from previous page

#### Observed Behavior
Requires me to refresh page in order to see the results by search term.

#### Steps to Reproduce
_If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._

![searchSites1](https://user-images.githubusercontent.com/48605275/60546882-897dba80-9cdb-11e9-9a6e-62d281280e3c.png)
![searchSites](https://user-images.githubusercontent.com/48605275/60546883-897dba80-9cdb-11e9-9f7a-d64914fe8930.png)

**Comment by wobba** [comment]
I have a feeling this is due to smart loading. How are you navigating to your result page? What kind of page takes you there, and what logic is used for navigation?

**Comment by FranckyC** [comment]
Yeap I also think something is not wired correctly. What are your search results and search box connection parameters?

**Comment by dpc80111** [comment]
Thanks guys, The set up info is in word attachment.
[ModernSearch-dpc80111.docx](https://github.com/SharePoint/sp-dev-solutions/files/3355356/ModernSearch-dpc80111.docx)
  


PS: Can you put in a plug to start allowing video files to be uploaded

**Comment by wobba** [comment]
@dpc80111 If you set top open i a new tab instead of the same current tab, do you see the issue still?

**Comment by dpc80111** [comment]
I am assuming that wouldt be to open a new tab on page 1 to page 2 as I can do that from page 2 search nav to page 3.   

That produces no results  on pages 2 with ONLY open in new tab set.
![searchSites2](https://user-images.githubusercontent.com/48605275/60669906-ac6bb400-9e2c-11e9-8109-4b7c2f3f25b1.png)

**Comment by dpc80111** [comment]
I do believe this is due to a\the refiner on a page.  I tested the issues both  in IE 11 and chrome and they had the same result. I had to refresh page.  Removed refiner and 3rd page rendered results. No refresh needed.

**Comment by marcoschmucker** [comment]
I do have the same error on the search result page: The search box gets the url parameter set when user comes from homepage (q). Results are listed in results webpart. 
When the user enters a new term in the box on the results page (open in new tab, send to new page = itself), the url gets the term, the box shows the new term, too.
Results still have the old term. Only if user refreshes page, the results are updated.

**Comment by marcoschmucker** [comment]
Different to your screens on my environment: Search always adds a # to the query.
Is that maybe a misconfiguration?
Thanks so much!

**Comment by dpc80111** [comment]
Work around - remove the default search term and the 3rd page results are correctly shown WITHOOUT page refresh

**Comment by marcoschmucker** [comment]
Thanks, but there is no "default search results" value if you use the source "Page environment - query string - url fragment".

![image](https://user-images.githubusercontent.com/27192929/61227809-500a6d80-a725-11e9-87c6-573d2d9c0114.png)

![image](https://user-images.githubusercontent.com/27192929/61227833-5c8ec600-a725-11e9-88bc-e5809fd4143d.png)

![image](https://user-images.githubusercontent.com/27192929/61227858-67495b00-a725-11e9-8e50-2673e130730f.png)

**Comment by marcoschmucker** [comment]
Sorry. You are right. I just re-configured search results as requested.
I do not have to send results to a new page. 

Thanks so much. Absolutely great work, keep on with that!

![image](https://user-images.githubusercontent.com/27192929/61228535-bfcd2800-a726-11e9-8366-70ff1f40fa03.png)

![image](https://user-images.githubusercontent.com/27192929/61228557-c6f43600-a726-11e9-8c6d-f7b1fdf2b5fb.png)
