### ISSUE TITLE
Results are not displayed

### ISSUE THREAD

**Issue by SaraKlein** [SharePoint/sp-dev-solutions#209]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [*] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
added a search box and search results web part.
expected to see results - I know it got results because the pagination webpart shows 5 pages.

#### Observed Behavior
I don't see the results.
get this error on the console:
component is not a function BaseTemplateService.ts:36
![image](https://user-images.githubusercontent.com/49513250/60667676-c29c6300-9e72-11e9-9ec0-a290f8ce1de6.png)

#### Steps to Reproduce
I downloaded the package today, built it and deployed it to my server.

**Comment by FranckyC** [comment]
Hi @SaraKlein. Does this issue appear with the default WP configuration (templates ,etc)?

**Comment by SaraKlein** [comment]
Yes, the only change i made is on the search results - it takes the query
from the search box.

**Comment by FranckyC** [comment]
What browser are you using? Also, did you take the .spkg file or you built from the master/modern-search-dev branch?

**Comment by SaraKlein** [comment]
i'm using chrome.
I built from the  master/modern-search-dev branch

**Comment by FranckyC** [comment]
Ok which one did you take? master or dev?

**Comment by wobba** [comment]
The error seems related to `LoadHandlebarsHelpers` according to the line number. If you remove the search box, still the same error? Tested the `modern-search-dev` branch just now adding a search box, pagination and result web part and don't see any issues.

**Comment by SaraKlein** [comment]
At first i tried the master.
now I tried the dev and when i try running gulp package-solution after
building I get 3 errors:
 Error - Error: The webparts manifests list is empty. Please ensure you
have done a build and that your config file is pointed at the correct
folder.

Error - Error: The webparts manifests list is empty. Please ensure you have
done a build and that your config file is pointed at the correct folder.
 Error - 'package-solution' sub task errored after 47 ms
 No manifests were found in '*.json'. Ensure a build has completed
successfully and that paths.manifestsMatch is correct
[12:53:14] 'package-solution' errored after 79 ms

Am I doing something wrong?

**Comment by wobba** [comment]
@SaraKlein Try this when standing in the spfx folder of the project:
```
npm i
npm dedupe
gulp
gulp package-solution
```

**Comment by SaraKlein** [comment]
That worked.
Thank you very much!
