### ISSUE TITLE
Modern Search Custom Renderer v1.0.1.0 deployment failure

### ISSUE THREAD

**Issue by dpc80111** [SharePoint/sp-dev-solutions#210]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [x ] Question
- [ x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Install and be able to use app

#### Observed Behavior
Deployment step fails
![refinderrenderFails](https://user-images.githubusercontent.com/48605275/60729868-f2924780-9f00-11e9-9a5c-45b980ea95a3.png)

#### Steps to Reproduce
Tried multiple times on IE11 and Edge

**Comment by wobba** [comment]
@dpc80111 I see the same error and will try to figure out what happens.

**Comment by wobba** [comment]
@dpc80111 I have updated the sppkg in releases. Seemed to happen with the 1.8.2 upgrade. I have downgraded to 1.7.0 and will try to figure out what causes this.

**Comment by wobba** [comment]
Found the issue and fixed it. Package updated.
