### ISSUE TITLE
MultilingualPages: ampersand (&) in page title leads to endless error loop in console

### ISSUE THREAD

**Issue by heinrich-ulbricht** [SharePoint/sp-dev-solutions#213]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Ampersand (&) in page title should be handle correctly.

#### Observed Behavior
Ampersand (&) in page title leads to errors and endless loop (visible in JavaScript console).

#### Steps to Reproduce
* have multilingual pages solution installed and set up
* create new page with title _test1 & test2_
* choose **Publish**
* move page to master language folder
* activate more languages for the page and choose **Apply language changes**

--> endless error loop in console:
![image](https://user-images.githubusercontent.com/3469970/60812279-6ea2be80-a191-11e9-9f2d-a206f71acea9.png)

Versions:
* Solution v1.6.3
* Chrome canary latest

**Comment by wobba** [comment]
@juliemturner
