### ISSUE TITLE
Display Organizational News / Site Name Option

### ISSUE THREAD

**Issue by mwsaunders** [SharePoint/sp-dev-solutions#215]
#### Category
- [ ] Question
- [ ] Bug
- [X] Enhancement

Hi , I am working on this for display of News items.
Mainly as it provides a way to filter across multiple sites using a NewExpiryDate property.
But the additional customization abilities are great.

Is there a way to have the Organizational News Banner Displayed?
Get-SPOOrgNewsSite - 
I am guessing this would be done in the display template similar to the below.
<span class="ms-ListItem-secondaryText">{{getSummary HitHighlightedSummary}}</span>

Maybe Organizational news is not even needed... though that distinction would be nice.
I see {{Path}} returns the full URL to the Item. 
Any way to just get the Site Name?

Regards,

**Comment by FranckyC** [comment]
Hi @mwsaunders, Did you try to use the 'SiteTitle' MP to get the site name only? You will have to add it to the selected properties first and them use it in your template

**Comment by mwsaunders** [comment]
Thanks, yes that gets me the site name. Good enough for now.
