### ISSUE TITLE
How to get modern .url link data

### ISSUE THREAD

**Issue by coupalm** [SharePoint/sp-dev-solutions#223]
#### Category
- [X] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
When a search result is a .url link of a document library, I would like to be able to customize the search result to provide the link stored in the url file type.

#### Observed Behavior
I'm not able to find or create a managed properties for this info. The field is __ShortcutUrl is hidden and I'm not able to create a managed property with it...

Any suggestion?

**Comment by wobba** [comment]
@coupalm I don't think this is possible as the link is stored inside the .url file, and not included as managed property. You would need a special UI handler which opens the file, and then uses the link inside to open.

**Comment by MattSyntaxError** [comment]
I would create a custom content type for your Link instead of using the out of the box version. I used the Link to Item column in my document library and I was able to store the URL in a column and access it with some schema manipulation.
