### ISSUE TITLE
Modern Search Web Parts v3.5.0.0 Release email

### ISSUE THREAD

**Issue by dpc80111** [SharePoint/sp-dev-solutions#224]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [X ] Bug
- [ ] Enhancement

The URL in the release email gives you a 404 error

https://github.com/SharePoint/sp-dev-solutions/releases/tag/2019-07-012

**Comment by wobba** [comment]
@dpc80111 I was renaming the tags, and deleting the wrong ones. Use https://github.com/SharePoint/sp-dev-solutions/releases/latest and you are good
