### ISSUE TITLE
Search Vertical sorting always alphabetical

### ISSUE THREAD

**Issue by marcoschmucker** [SharePoint/sp-dev-solutions#225]
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
When several vertical refiner properties are added, and they are set to "by number of results", they should be sorted that way.

#### Observed Behavior
Refiners are always sorted alphabetically, not "by number of results  (descending)".

![image](https://user-images.githubusercontent.com/27192929/61229481-8c8b9880-a728-11e9-8c93-112acedb714a.png)

![image](https://user-images.githubusercontent.com/27192929/61229535-a88f3a00-a728-11e9-9f0f-a86d3f56e70d.png)

#### Steps to Reproduce

See picture of Search Refiner config.

**Comment by mwsaunders** [comment]
@marcoschmucker 
Hi,  I am not seeing the results you are.  I am on 3.5 developer branch code.
My Screen Shots.

![SharePointRefiner1](https://user-images.githubusercontent.com/52049381/61383153-1d26bd80-a87c-11e9-9029-4328a338dad1.png)
![SharePointRefiner1a](https://user-images.githubusercontent.com/52049381/61383165-23b53500-a87c-11e9-9c68-2714ff9491b4.png)

**Comment by marcoschmucker** [comment]
Hi @mwsaunders , I will very it. Looks perfect in your screenshot! Thanks for that hint.

**Comment by wobba** [comment]
Latest release package is equal to dev branch right now btw :)
