### ISSUE TITLE
Modern Search Web Parts Handlebars helper submission 

### ISSUE THREAD

**Issue by navarrorc** [SharePoint/sp-dev-solutions#227]
#### Category
- [x] Question

#### Expected or Desired Behavior
I would like to add a new Handlebars helper to the ***Modern Search Web Parts*** solution. I can create the pull request, just need to know what version to bump it up to.

This helper allowed me to get the unique values in the collection of News Posts based on a  custom Managed Property (RefinableString108 aliased NewsCategory in my tenant). 

I a can provide screenshots of a real world use case upon request. This helper is a slight modification of the getUniqueCount helper that is defined in the BaseTemplateService.ts file.

Helper code is below: 

```typescript
    // Return the unique values as a new array based on an array or property of an object in the array
    // <p>{{getUnique items "NewsCategory"}}</p>
    Handlebars.registerHelper("getUnique", (array: any[], property: string) => {
      if (!Array.isArray(array)) return 0;
      if (array.length === 0) return 0;

      let result;
      if (property) {
        result = uniqBy(array, property);
      } else {
        result = uniq(array);
      }
      return result;
    });
```

Thanks.

**Comment by wobba** [comment]
Hi,
Appreciate this one. Could you turn it into a PR and also update the readme with the setup and usecase  in the PR?

**Comment by navarrorc** [comment]
Will work on the PR. I assume you will increase the version number? Thanks.

**Comment by navarrorc** [comment]
Have a look at this quick demo of what I was able to achieve https://www.youtube.com/watch?v=QA6CALgMJik&feature=youtu.be
Thoughts?

**Comment by wobba** [comment]
Nice. Ideally you would have gotten thoses values as a refiner instead right? Which will automatically aggregate and give you unique values. And then use a custom template for refiners - which we have not implemented yet.

We will bump the version number for each release, so don't think about that :)

**Comment by wobba** [comment]
Added it.
