### ISSUE TITLE
owstaxidmetadataalltagsinfo refiner shows 0 values and duplicates

### ISSUE THREAD

**Issue by colonelclaypoo** [SharePoint/sp-dev-solutions#230]
Version: 3.5.0

Hi, 
regarding refiners I was wondering if two behaviors I observed are "by design" and I'd like to discuss if the default behavior should be changed.

![2019-07-22_09-52-16](https://user-images.githubusercontent.com/29123261/61615902-6eadbe80-ac67-11e9-864d-845ee4d18ac0.png)

(1) - Why are 0 values shown?
(2) - Why are duplicates displayed?

Now, is this related to a config issue on my side? For the "Tags" refinder I mapped 

ows_taxId_MetadataAllTagsInfo to refinablestring111 as illustrated here:

![2019-07-22_10-03-13](https://user-images.githubusercontent.com/29123261/61616121-f267ab00-ac67-11e9-8d50-ee47fda1e5b9.png)

Thanks for your input.

Edit: Regarding (1) I noticed that I don't get 0 values if, instead of mapping 
ows_taxId_MetadataAllTagsInfo to a RefinableString, I use the ootb owstaxidmetadataalltagsinfo managed property. Therefore, the issue with RefinableString111 might be index related. I have not waited 24+ hours yet.

**Comment by wobba** [comment]
The 0 is text, meaning the refiner name is "0". For the others I suspect the source actually contains a space or no break space at the end for one of the values which unfortunately is not trimmed when indexing.

**Comment by colonelclaypoo** [comment]
> The 0 is text, meaning the refiner name is "0". For the others I suspect the source actually contains a space or no break space at the end for one of the values which unfortunately is not trimmed when indexing.

Thanks for your input, as always.

I can comprehend that 0 are indeed text values. However, how they get there I have no idea. But as I mentioned, using the managed property owstaxidmetadataalltagsinfo does not exhibit this problem, only where I mapped ows_taxId_MetadataAllTagsInfo to a refinable string.

Regarding the duplicates, I couldn't find any non-breaking spaces or commas. I think there must be something wrong in the index or the managed property.

For example, I identified a file that is shown for both refiners i.e. apparently having the same metadata.
However, I verified that the file exists on two different site collections - it could have been copied.
File A has the metadata term that exists twice as a refiner but file B doesn't, it has a different value. Therefore, file B should not be shown funder the duplicate, second refiner.

I've just executed your "trigger re-index" script from way back. Let's see if it helps with the next crawl.

I will report back.

**Comment by FranckyC** [comment]
@colonelclaypoo The best way to check if this is a WebPart issue or a data issue is either to check the REST call response and refinement filters or use a tool like Search Query Tool with the same query to see what happens.

**Comment by colonelclaypoo** [comment]
> @colonelclaypoo The best way to check if this is a WebPart issue or a data issue is either to check the REST call response and refinement filters or use a tool like Search Query Tool with the same query to see what happens.

Yes, here's the SearchQuery Tool output:
![2019-07-22_13-36-10](https://user-images.githubusercontent.com/29123261/61629649-c529f580-ac85-11e9-98b1-a429b8ba8390.png)

As you can see both files have different taxonomy values and are stored on different site collections. However, the owstaxidmetadataalltagsinfo refiner shows two entries for "Accounting & Controlling".

It's weird.

**Comment by FranckyC** [comment]
OK it's weird because this is the same term ID for both but not the same label. Can you check the term with this id in the term store to see if it actually exists and has correct labels?

**Comment by FranckyC** [comment]
You could also turn off the 'Localization enabled flag in the WP settings to see the raw value and match with the search query tool results.

**Comment by colonelclaypoo** [comment]
@FranckyC, thanks for your suggestions. I verified that the first term, 'Accounting & Controlling' is present in the term store. The other one however is not.
Secondly, disabling the localization will only show one refiner:
![2019-07-22_15-34-40](https://user-images.githubusercontent.com/29123261/61636798-a6802a80-ac96-11e9-89fa-01abe243018d.png)

With the localization enabled it will show twice:
![chrome_2019-07-22_15-37-59](https://user-images.githubusercontent.com/29123261/61636864-cfa0bb00-ac96-11e9-982d-322ec285e736.png)

I tried to enter the query `* owstaxidmetadataalltagsinfo="L0|#0e82d25d1-0f4e-4f9f-ac52-d3142ea7f2be|Accounting ＆ Controlling"` into the search box and it returns 125 items.

Could it be some kind of translation issue?

Thanks!

**Comment by FranckyC** [comment]
@colonelclaypoo Do you see this issue again after reindexing?

**Comment by colonelclaypoo** [comment]
Reporting back. So I deleted the faulty tax value "Subject Matter Expertise" from one file and the count for one of the refiners dropped which is from the one that had 105 results. It now shows 104. Therefore

**Comment by colonelclaypoo** [comment]
@FranckyC, unfortunately not but I've just made the decision to remove the terms "Subject Matter Expertise" which are almost certainly wrong as they don't exist in the term store. I will report back soon. Thanks.

**Comment by wobba** [comment]
@colonelclaypoo can this be closed?

**Comment by colonelclaypoo** [comment]
Hi, sorry, was not able to check any earlier. Just seeing that yes, the removal of the wrong term fixed the issue. Therefore, this issue lay on our side, could oin it on this solution. Thanks for your support.
