### ISSUE TITLE
Reference list item property in template

### ISSUE THREAD

**Issue by WuWei42** [SharePoint/sp-dev-solutions#231]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
First of all: Thanks for the greate Modern Search Webpart - good job!

To my problem: 
I want to show an image in the search sesult webpart and the url of the image is stored in a "Hyperlink or Picture"-column named "Produkt Bild" (formatted as image, to show them in the list). 
I add this the property name "ProduktBild" to the "selected property"-Listbox of the  search result webpart and edit the result template to get the image url with {{ProduktBild}}.
**Unfortunatly the template does not show the image url.**

After I requested the data structure of the listitem via postman I got the following result:
...    
_"WssId": 1
    },
    "ProduktID": "10A",
    "ProduktBild": {
        "Description": "https://xxx.sharepoint.com/A4rker.jpg?csf=1&e=m4nIzo",
        "**Url": "https://xxx.sharepoint.com/A4rker.jpg?csf=1&e=m4nIzo"**
    },_
...
So I try to reference the url with {{ProduktBild.Url}}. But again without any success.

What is my mistake? 
Can you please give me an advice how to get the url of this column. 

Cheers
wuwei

**EDIT**
I have found an workaround to get the picture:
It is quite easy to get the picture url when I use a sharepoint picture library instead of a generic list.
thx for helping.

**Comment by FranckyC** [comment]
Hi @WuWei42. Can we consider this as resolved? Also did you use the `getUrlField` Handlebars helper? (ex `{{getUrlField MyLinkOWSURLH "Title"}}`)

**Comment by WuWei42** [comment]
Hi @FranckyC. Thanks for your help. The problem seems to be the missing managed properties of the contentclass: "STS_ListItem_GenericList". The strange thing is that the SPO REST API lists the picture references in a correct hirarchical manner. (request testet in postman)
I am not familiar with the proper configuration of the SPO search (eg. Result Source, Managed Properties, ....) May be there is a way to tell SPO which field (=column) in which type an request (query) should be returned.
How ever. The workaround with the picture library works for me.
So I close the issue.
