### ISSUE TITLE
Created filter object count not matching results returned

### ISSUE THREAD

**Issue by mwsaunders** [SharePoint/sp-dev-solutions#232]
#### Category
- [X] Question
- [ ] Bug
- [ ] Enhancement

@wobba 
Thanks,
I think I know now what is going on with item count being returned by the Created Filter not matching the results returned number.
Not All Objects have a Created Date.
Mainly looking like the Views (.aspx pages) created for Lists.
Not sure these should or should not be filtered out - I am thinking yes and looking for a good way to do so.
Any suggestions?  

![Created Filter count mismatch](https://user-images.githubusercontent.com/52049381/61646672-ef28eb00-ac78-11e9-92ac-1e4d0df0a81b.png)

![Not all have Created Date](https://user-images.githubusercontent.com/52049381/61646675-f223db80-ac78-11e9-9da1-58853f30c2d1.png)

**Comment by mwsaunders** [comment]
Ugly solution I have found is to add FileName exclusions in the Search Template.
-Filename:/Forms -Filename:/Allitems -Filename:/Byauthor -Filename:/Calendar
I realize is not a practical solution in a production environment.

**Comment by FranckyC** [comment]
@mwsaunders This is actually the expected behavior and nothing wrong here in my opinion. Refinement values and results doesn't have to match count every time. This is a god example. It is user responsability to exclude results that are not relevant. We can't assume or filter anything automatically in the search query.

**Comment by mwsaunders** [comment]
@FranckyC 
Thanks, that is what I was thinking.  It never occurred to be that some items would not have a created date and I needed to understand the results I was seeing.
