### ISSUE TITLE
Search Results Repeatedly Refreshing After Entering Search Term in Search Box

### ISSUE THREAD

**Issue by sympmarc** [SharePoint/sp-dev-solutions#235]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Version
3.4.0.0

#### Expected or Desired Behavior
We have a pretty classic setup: Search Box, Search Refiners, Search Results, Search Pagination. Everything has been set up for a while and working fine.

We expect the Search Results Web Part to grey out and refresh when we change the search term, but not after the first refresh when we no longer touch the page.

#### Observed Behavior
Recently (though maybe this has been there and we simply didn't notice), when we type a term in the search box, the search results are correct, but the Web Part continues refreshing ad infinitum.

#### Steps to Reproduce
Again, pretty normal set up. We're wondering if we have some setting incorrect, though I'm not spotting anything. Anything fixed in more recent builds? I'm not seeing anything when I look at the issues list. 

@dcashpeterson

**Comment by nboltman** [comment]
I had the same issue after deploying the new release. I ended up removing the results webpart from the page and adding it back. This resolved the infinite refresh.

**Comment by FranckyC** [comment]
Hi @sympmarc, would it be possible for you to record this behavior? I'm not sure to fully understand this issue. Thanks!

**Comment by sympmarc** [comment]
Sure thing. I hope you don't mind, but I'm going to email you the recording, as it's got client stuff visible.

**Comment by FranckyC** [comment]
Sure you can send it to franck.cornu@aequos.ca.

**Comment by FranckyC** [comment]
Ok I can see the problem, thanks. If you check the network tab, do you get multiple call with 'postquery' every time it refreshes? Also, is the searchbox connected to something from context?

**Comment by sympmarc** [comment]
Yes, there is a postquery every time the refresh happens. Here are the Search Box settings:
![SearchBoxProperties](https://user-images.githubusercontent.com/1295627/61909960-62dd2900-af01-11e9-8aed-d18274f9db2a.png)

**Comment by FranckyC** [comment]
Hmm it seems you created and endless loop with this setting 😉

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by sympmarc** [comment]
Which setting is the issue? Happy to change it!

**Comment by FranckyC** [comment]
You don't need to connect the search box to the search results (this is not a 2 ways connection). The search box dynamic value is only intended to get a default value from the environment (ex: a query string parameter coming from an other page). If you are not in this situation, no need to use this setting.

**Comment by sympmarc** [comment]
That's fixed it: removing the **Search query's properties** on the Search Box properties panel.

**Comment by wobba** [comment]
@FranckyC any way we can prevent these issues? Filter on the available connections for search only or similar.

**Comment by FranckyC** [comment]
@wobba yes we coud, but in the case of the search box, we use the default SPFx connection control which gives you all environment variables by default. You may also use your own Web Part as data source so filtering is not really an option since you can use any value you want here.
