### ISSUE TITLE
Description is improperly named "Name"

### ISSUE THREAD

**Issue by itsknob** [SharePoint/sp-dev-solutions#24]
https://github.com/SharePoint/sp-dev-solutions/blob/604dbf7557e92e833b09f4d522473b5a654f4762/solutions/SiteDesignsStudio/schemas/schema.20180602.json#L397

There are currently two fields named Name. The Name field and the Description field. The Description field needs to be renamed to "Description"

**Comment by ypcode** [comment]
Indeed, thanks Stephen for letting me know, I’ll fix that ASAP

KRs
Yannick
________________________________
De : Stephen Reilly <notifications@github.com>
Envoyé : mardi, juin 26, 2018 8:08 PM
À : SharePoint/sp-dev-solutions
Cc : Subscribed
Objet : [SharePoint/sp-dev-solutions] Description is improperly named "Name" (#24)


https://github.com/SharePoint/sp-dev-solutions/blob/604dbf7557e92e833b09f4d522473b5a654f4762/solutions/SiteDesignsStudio/schemas/schema.20180602.json#L397

There are currently two fields named Name. The Name field and the Description field. The Description field needs to be renamed to "Description"
