### ISSUE TITLE
Search-Results: Regular Expressions in result templates

### ISSUE THREAD

**Issue by WuWei42** [SharePoint/sp-dev-solutions#240]
#### Category
- [ ] Question
- [ ] Bug
- [ x] Enhancement

#### Expected or Desired Behavior
It would be nice to have a handlebars helper to use regular expressions within templates.
A proposal for BaseTemplateService.ts could be: 
```
Handlebars.registerHelper("regex", (regx:string, str:string) => {
          let rx = new RegExp(regx);
          let i = rx.exec(str);
          if(!!!i || i.length === 0) return "-";
          let ret: string = i[0];
          return ret;
        });

```
Unfortunatly the [toRegex-Helper](https://www.npmjs.com/package/handlebars-helpers#regex) gives me an error : _...Message: "Missing helper: "toRegex"", name: "Error"..._ 
This was my first aproach.

Thanks and happy coding.

**Comment by wobba** [comment]
@WuWei42 Feel free to submit a PR against the modern-search branch :)
