### ISSUE TITLE
Search for tasks assigned to currently logged in user

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-solutions#243]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [x ] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
I want to user the modern search webparts to find all tasks assigned to the current user

#### Observed Behavior
I cant figure out how to filter the AssignedTo  property to be  equal to the currently logged in user. Is there a keyword for that. Any examples somewhere?

**Comment by wobba** [comment]
Out of scope for the web part project. I suggest you ask at https://techcommunity.microsoft.com/t5/SharePoint/bd-p/SharePoint_General

**Comment by russgove** [comment]
Nah It's in there, just found it!
AssignedTo:{User.Name} works.
