### ISSUE TITLE
Search not seeing updated Title metadata fields

### ISSUE THREAD

**Issue by jimbul** [SharePoint/sp-dev-solutions#244]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [-] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Search results to display updated title metadata fields for powerpoint files within a reasonable timeframe.

#### Observed Behavior

When using sharepoint modern search to, it does not seem to show updated title metadata field information when returning results. The title metadata field is the text that the hyperlink is set on when  you get your search results back. So if we update the title metadata of a powerpoint file from the default of "PowerPoint Presentation" to "Important presentation" we will still see "PowerPoint Presentation" as the title of the document in the search results - even two weeks later. If we use SharePoint native search the updated title metadata field is displayed immediately in the search results. I would expect the same with sp-modernsearch?

#### Steps to Reproduce

Create a powerpoint file, save it with the default title information. Run a search using the sp-modernsearch webpart, observe that it is listed in the search results as "PowerPoint Presentation".

Update the title metadata field either in the (i) dialogue in the sharepoint document library OR in the file properties dialogue in desktop PowerPoint.

Run another search and see if results show the updated title metadata field as the hyperlink to said document.

**Comment by wobba** [comment]
This is not a webpart issue as the webpart merely render what is returned from the search api. I suggest you log a support ticket instead.

**Comment by jimbul** [comment]
ok thanks Mikael.
