### ISSUE TITLE
Search Result fails with "Error making HttpClient request in queryable [403] Forbidden ::> {"error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to perform this action or access this resource."}}}"

### ISSUE THREAD

**Issue by alejandroaldana** [SharePoint/sp-dev-solutions#245]
#### Category

- [x] Bug

#### Expected or Desired Behavior
The expected behavior is that I can search with refiners in a library.

#### Observed Behavior
I am trying to use modern search Web Part, but this error is throwed when I make a query:

Error making HttpClient request in queryable [403] Forbidden ::> {"error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to perform this action or access this resource."}}}

![image](https://user-images.githubusercontent.com/6736510/62363405-8f0b3200-b51f-11e9-8703-369050e29e3a.png)

**Comment by FranckyC** [comment]
Hi @alejandroaldana , could you open the network tab in your browser and see what call fails? A screenshot would be great also. Thanks

**Comment by alejandroaldana** [comment]
It fails calling https://mysharepoint.sharepoint.com/sites/mysite/_api/contextinfo

![image](https://user-images.githubusercontent.com/6736510/62365969-d4caf900-b525-11e9-9fdd-cedd9e41e8f2.png)

**Comment by FranckyC** [comment]
It is the latest WP version? Is it a regular page or the workbench?

**Comment by alejandroaldana** [comment]
The version is v3.4.0.0 and is a modern regular page

**Comment by FranckyC** [comment]
Can you try with the latest 3.5 from the master branch? https://github.com/SharePoint/sp-dev-solutions/releases/tag/ms-2019-07-12

**Comment by alejandroaldana** [comment]
The problem is that I do not have full permissions to install an app, and it would take too much time to ask for the change. But it should work with this version,I had two months ago the 3.3 version and I uploaded to 3.4 but it did not resolve the problem

**Comment by FranckyC** [comment]
is this specific to this site collection or does it happen everywhere? Also, can you try with a administrator account to see if there any difference?

**Comment by alejandroaldana** [comment]
I have just tried in this site, because I do not have access to all sites. Also, I do not an administrator account to verify it.

**Comment by FranckyC** [comment]
It seems there is something wrong with your permissions like something is missing. I can't do anything here unfortunately :(.

**Comment by wobba** [comment]
So you are a site collection admin with a site collection app catalog in your scenario?

**Comment by alejandroaldana** [comment]
Exactly

**Comment by alejandroaldana** [comment]
Finally I made it work! I disabled "Enable taxonomy values licalization for refiners and results and it works:
![image](https://user-images.githubusercontent.com/6736510/62535544-f55bc180-b84b-11e9-870b-04c2416e3ebc.png)

**Comment by wobba** [comment]
Could it be that you don't have permissions to read the termstore?

**Comment by alejandroaldana** [comment]
I can see terms under Term Store Management Tool and I can edit the site collection terms.

**Comment by wobba** [comment]
I cannot really figure this one out or reproduce it. Could be a digest issue in the term store call. Are you ok to close this for now, unless you can provide steps to set up a repro in any environment for testing.
