### ISSUE TITLE
Issue with pagination navigation button "<<"

### ISSUE THREAD

**Issue by vtikam** [SharePoint/sp-dev-solutions#252]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Search with word in search box or for that case any other word. The total results should be in multiple of 10.
2> This is occurring when the search result is an even number, like 20, 30, 40...100 etc. We cannot reproduce the issue if results are like 25, 46, 208, etc
3> Click on the last page number of the result in the pagination section.
4> Now click on "<<"
5>"Click on "<<" icon when user is on 1st page of searched result

#### Observed Behavior

"No results to display" shows where as it should move to the first page. If the page count was 10 we will get this issue, if the count is say 14, we will properly get to see results on 1st page.

**Comment by wobba** [comment]
I have set my page to 10 results with the code in the dev branch, and cannot reproduce this.

**Comment by wobba** [comment]
@vtikam can you provide more information when using the latest version? If not I'll close the issue.

**Comment by vtikam** [comment]
I am not able to reproduce the issue. It happened for once immediately after deployment. You can close the issue. Thanks for looking into it.
