### ISSUE TITLE
Search navigation hard-codes "q" query string

### ISSUE THREAD

**Issue by glapointe** [SharePoint/sp-dev-solutions#258]
#### Category
- [ ] Question
- [ ] Bug
- [x] Enhancement

#### Expected or Desired Behavior
I marked this as an enhancement but I do think it's technically a bug as the behavior is not what you'd expect. If I need to use a query string parameter other than "q", such as when coming from a classic site which uses "k" (with no way to alter that) then I can easily configure the search box to use "k" as the parameter but the search navigation does not honor that setting or otherwise allow me to specify the parameter to use (it simply hard-codes it as "q"). This means that clicking to go to a different search page effectively loses the search term which is confusing to the user. The search navigation control should either use the value provided to the search box or simply allow the parameter to be specified so that it's consistent with the other controls. 

#### Observed Behavior

Should be able to specify a query string parameter such as "k" for the search navigation control so that it will match what the search box expects.

#### Steps to Reproduce

Simply add a search box control and configure it to use "k" as the query string parameter and then add a search navigation control (you can just have it point to the same page) - clicking the navigation link will result in "q" being used instead of "k" which causes the search box to lose the search term.

**Comment by YannickRe** [comment]
Thank you for making this an official issue, it’s been bothering me for a while but just not enough to fix 😉.
I’ll put some time in to make this configurable!

**Comment by YannickRe** [comment]
PR done, you can probably expect this in next months release ;)

**Comment by glapointe** [comment]
Fantastic! Thank you so much for jumping on this!
