### ISSUE TITLE
Modern Search Version 3.6.1 - Access denied errors in IE11

### ISSUE THREAD

**Issue by dpc80111** [SharePoint/sp-dev-solutions#259]
>After installing 3.6.1 IE 11 pages are not rendering. Works in Chrome and Edge.

![MS361issues_IE11](https://user-images.githubusercontent.com/48605275/62958933-e2e60880-bdb4-11e9-84c3-e98cbb64d259.png)

SCRIPT5: Access is Denieed
Access Denied error on search-results-web-part_d471d8585e83ed85c44c1df3ae2d237e.js (80,46766)

**Comment by FranckyC** [comment]
Did you check in and publish the package?

**Comment by dpc80111** [comment]
Yes
![MS361issues](https://user-images.githubusercontent.com/48605275/62960099-35c0bf80-bdb7-11e9-9d6b-7c050af8f23b.png)

**Comment by FranckyC** [comment]
Did you try to clear the cache?

**Comment by dpc80111** [comment]
No, but its NOW working. Must a lag time to populate through the tenant.   Thank you for looking into this

**Comment by dpc80111** [comment]
Sorry we reverted back to 3.5, that's why it works now.  3.6.1 is still an issue with IE 11

**Comment by FranckyC** [comment]
If you are on an isolated site collection you can still clear yur manifests and start over:
https://www.techmikael.com/2018/02/alternative-way-to-solve-issue-where.html
BTW a fixed has been pushed for the enums, should be available soon as a new package

**Comment by dpc80111** [comment]
cleared cache on IE on diff PC ,
diff tenant, same reslts. F12 error messages attachd 


[361IE11_2.txt](https://github.com/SharePoint/sp-dev-solutions/files/3498378/361IE11_2.txt)

**Comment by FranckyC** [comment]
Weird, did you clear the manifests?

**Comment by dpc80111** [comment]
didnt need to brand new install of 3.6.1

**Comment by FranckyC** [comment]
Ok that's weird I can't reproduce it on my tenant

**Comment by dpc80111** [comment]
dont know what to tell ya, 2 of us where getting the same results with E11 on 3.6.1

**Comment by FranckyC** [comment]
Does it happen only with the search results or other Web Parts?

**Comment by FranckyC** [comment]
Also are you able to edit the page and go to the WP options?

**Comment by FranckyC** [comment]
Ok I think I found the issue. Related to a missing Polyfill for IE11. Weird because I've got the error but my results appear anyway.

**Comment by wobba** [comment]
New release with the IE11 fix. Console still throws errors, but at least it works :)

**Comment by FranckyC** [comment]
If you can confirm your results render @dpc80111, would be appreciated ;)
