### ISSUE TITLE
Modern Search 3.6.1 - Results Layout changed

### ISSUE THREAD

**Issue by dpc80111** [SharePoint/sp-dev-solutions#260]
After the upgrade to 3.6.1 all our Results layouts are NOW tiles, where they were list prior to upgrade.  Yes switching them back to list does work and saves, but the upgrade DID reset the layout.

Shows Tiles layout in Chrome and Edge, unsure about IE 11 as its not rendering.

![MS361issues_tiles](https://user-images.githubusercontent.com/48605275/62959341-cb5b4f80-bdb5-11e9-9732-043ea94f5dda.png)

**Comment by FranckyC** [comment]
@dpc80111 the layouts changed a lot in this release and we cannot guarantee all previous layouts will work as is. Was your template custom? If so you can still revert to a previous version of the page to get the previous template content. When making a upgrade, it always a good thing to try it first is an isolated env.

**Comment by dpc80111** [comment]
Ok as long as i now know layouts aren't guaranteed to still render from a previous layout i can deal with that.  Should they keep the same layout, yes i do an hope you incorporate that into your code.

FYI: This is being tested in isolated env.

**Comment by FranckyC** [comment]
Probably it has to do with the layout enum. I'll see if I can reuse the same values as before.

**Comment by wobba** [comment]
@dpc80111 We'll update the release in a little bit.

**Comment by wobba** [comment]
@dpc80111 The release is updated to fix the layout issue.
