### ISSUE TITLE
Support for Search Results to Look at Query String and Search Box On Same Page

### ISSUE THREAD

**Issue by tseward** [SharePoint/sp-dev-solutions#263]
#### Category
- [x ] Question
- [ ] Bug
- [] Enhancement

#### Expected or Desired Behavior

In classic Search, I'm able to configure the Search Results webpart to both support query strings in the URL (#k=) as well as a Search Box residing on the same page as the Search Results webpart.

With modern search webparts, this doesn't appear to be possible. The Search Results webpart can either be configured for one scenario or the other. This is needed to support being able to start a new query on the same page as the results when coming from a different page for the initial query.

From a brief experiment, if the Search Box on the same page as the Result webpart is using the option to 'Send to another page' and points to the same page the webparts are on, that doesn't work _unless_ the page is in Edit mode, then it does appear to work.

#### Steps to Reproduce

Create a page with a Search Box. Configure it to pass a query parameter to another page.
On the page the above Search Box points to, add a Search Box and Search Results webparts. Configure the Search Results webpart to consume query parameters.

Start a query on the page with the first Search Box webpart which will pass you to the new page and the Search Results will show as expected. On the same page as the Search Results webpart, enter a new query term in the Search Box. The query will not be passed to the Search Results webpart.

**Comment by YannickRe** [comment]
On the second page:
- configure your Search box to consume from query string
- configure your Search results to consume from Search box

This will give you the intended behavior.

**Comment by tseward** [comment]
Awesome, works great!
