### ISSUE TITLE
Not able to filter category using search refiner

### ISSUE THREAD

**Issue by Mike05-921** [SharePoint/sp-dev-solutions#266]
I’ve a blog site where 20+ categories are there.Now my requirement is using React search refiner webpart I have to fetch some specific categories post using search query in New Experience Sharepoint.

I have mapped ows_PostCategory to Refinablestring and applied in search query.

Now all categories results are coming..

categories link like: /blogs/demo/Lists/Categories/Category.aspx?CategoryId=3

I want to exclude one specific category from result.. Any ideas on how to add refinable managed property to exclude the specific category using react search refiner.

Thanks in Advance

**Comment by FranckyC** [comment]
Hi @Mike05-921 Why not using a KQL condition to exclude the content you don't need? For instance `Path<>"/blogs/demo/Lists/Categories/Category.aspx?CategoryId=3"`

**Comment by Mike05-921** [comment]
Hi @FranckyC I didnt understand.. Can you please share a screenshot with me??

**Comment by FranckyC** [comment]
Something like this

![image](https://user-images.githubusercontent.com/5659122/63349918-6a3df980-c32a-11e9-90b2-ee02d2294853.png)

**Comment by Mike05-921** [comment]
It's not working @FranckyC ..My default search query is like--- path:"https://abc/blogs"  ContentTypeId:0x0110* -Title:"Welcome to my blog/" and then I put---  {searchTerms} Path<>https://abc/blogs/InTheLoop/Lists/Categories/Category.aspx?CategoryId=3"

what i am missing??

**Comment by FranckyC** [comment]
You can try by excluding categories using your created managed property like:
`Refinablestring<>"Category you want to exclude"` or `NOT(Refinablestring:"Category you want to exclude")`

**Comment by Mike05-921** [comment]
In query template only ??

**Comment by Mike05-921** [comment]
@FranckyC no luck.. tried like this :  
1.  {searchTerms} NOT(RefinableString03:"Events")
2. {searchTerms} RefinableString03<>"Events"

Do i need to add anything in default search query??

**Comment by FranckyC** [comment]
Are you sure this managed property is not empty? You can ensure this by switching to the debug view and adding RefinableString03 to the selected property list.

**Comment by Mike05-921** [comment]
![image](https://user-images.githubusercontent.com/54269871/63355510-e0227f00-c383-11e9-9ddb-bc02f52b4e21.png)

**Comment by FranckyC** [comment]
@Mike05-921  I mean the content of the managed property. You can inspect values for each item using either the debug view or Search Query Tool.

**Comment by Mike05-921** [comment]
@FranckyC Thanks a lot for you help. I really appreciate.. It was indexing issue.. Index the list and it started working.. Just a small question.. For a single category I wrote RefinableString03<>"Events"..
If I need to exclude multiple categories..  I alredy did like 
i) RefinableString03<>"Events"
  RefinableString03<>"Writing and language"


ii)RefinableString03<>"Events", "Writing and language"

Itried both way but its not working..

and If I need to add Multiple refiner How to add..

**Comment by wobba** [comment]
To exclude multiple you are doing it correct, except I prefer another syntax, and for SharePoint Online you can also abbreviate with a newly added functionality (https://docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference#grouping-property-restrictions-within-a-kql-query)

`-RefinableString03=("Events" "Writing and language" "Category Three")`

So `RefinableString03<>"Events" RefinableString03<>"Writing and language"` should have worked afaik, but I like `-RefinableString03="Events" -RefinableString03="Writing and language"` better.

**Comment by Ranjan131** [comment]
I have blog site and it has 5 blog groups list. each list consists of some categories with same name and different name as well. 
Example: Abc and Xyz are 2 of the blog lists among 5.
 In Abc blog list one of the category name called Weekly updates and same name category is available in Xyz list and it has other categories as well.
Here i need to pull(display) weekly updates category from Abc list and other 10+ categories posts from Xyz list.

Can any one suggest me that how to fetch some particular categories posts from multiple list and exclude other categories using react search refiner.

Thanks in advance

**Comment by wobba** [comment]
@Ranjan131 First off, please don't ask questions on other closed issues. Secondly your question is KQL related, not directly web part related, as you can do the exact same in classic web parts.

That said, if you use content types on your lists you can aggregate across sites using the content type id/name (SPContentType managed property for example), and exclude and include as you see fit. Take a look at https://docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference

**Comment by Ranjan131** [comment]
@wobba This issue is raised my colleague and since it is same i raised my question here and sorry for that.
Please see the below screen shot for Query template and Default search query
![image](https://user-images.githubusercontent.com/55277316/67071705-ddd07b80-f1a0-11e9-87a9-ecc7d290c069.png)

![image](https://user-images.githubusercontent.com/55277316/67072320-36544880-f1a2-11e9-9768-4d14f93c08a2.png)

its not working for me. i need to include some 15+ categories. Can you suggest me how to do this?

**Comment by wobba** [comment]
@Ranjan131 as I don't know your data structure setup and I don't have time to do consulting I suggest you try posting on techcommunity.
