### ISSUE TITLE
Feature request: group by handlebars helper

### ISSUE THREAD

**Issue by mschaaks** [SharePoint/sp-dev-solutions#268]
#### Category
- [ ] Question
- [ ] Bug
- [x] Enhancement

#### Expected or Desired Behavior

I would like to register an additional "group by" handlebars helper that let's me group search results by search result property. something like shown over here: https://github.com/shannonmoeller/handlebars-group-by. I tried to incorporate the mentioned code in the basetemplateservice, but i am not sure how to do this exactly. Do you have any suggestions how to register a group by helper and how to apply it within the template (preferably against a custom property (RefineableStringXXX). Thanks for the help!

**Comment by wobba** [comment]
Good suggestion and shouldn't be too hard.

**Comment by mschaaks** [comment]
Hi, would be great to have this one in there asap. Any idea when you are able to put this one in or how to approach it ? thx!

**Comment by wobba** [comment]
@mschaaks as this is a community project we need someone with spare time to get this in. If you can find a developer to do a PR I'll review it.

I'll keep this issue open until someone finds the time to implement it.

**Comment by FranckyC** [comment]
@mschaaks I've submitted a PR for this. Just a reminder this is a community project and we all do this on our free time so words like 'ASAP' should never be used here. I invite you to read this [article ](http://thecollaborationcorner.com/2019/08/26/open-source-is-so-cool-for-consumers-for-sure-not-the-same-for-maintainers/).

**Comment by mschaaks** [comment]
@FranckyC apologies for the used words. I have read your article, and you are completely right. this is one of the, probably the most, useful piece of community work that i have used recently, your doing fantastic work here!
