### ISSUE TITLE
Results filtering

### ISSUE THREAD

**Issue by DanielSanIT** [SharePoint/sp-dev-solutions#270]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

Hello.
Is it possible to restrict search results by file type or by document library?
For example I need to search among site pages every time by default (no any other file types).

Thank you!

**Comment by wobba** [comment]
Yes it's possible :) This is not really a web part related question, but a KQL one.

There is a managed property called `FileType` you can restrict by. Add it as a refiner to inspect possible values.

To restrict by a library use: `path:https://tenant-sharepoint.com/sites/my site/Shared Documents/` or similar.

**Comment by DanielSanIT** [comment]
Thank you Mikael!

Will be great if manual will have more examples.
I found only in closed issues that I should write something like that "FileType:aspx" to search only in aspx filetype or like that "-FileType:aspx" for exclude filetype from results.

**Comment by wobba** [comment]
Maybe I'll add those as samples to the book I'm planning on search troubleshooting. Include some tips. I do have some samples in https://www.techmikael.com/2014/03/s15e01-kql-basics.html which is the same as my book (link on that post). And there are some samples on the official KQL page. Weird that no one has `path` as sample queries as it's so common ;)

**Comment by DanielSanIT** [comment]
I just faced with it first time in my life here. I am not sure how it working at all. And I am looking around to find any examples how to use Search web part.
Thank you again. Also thanks for the solution.
