### ISSUE TITLE
External Users

### ISSUE THREAD

**Issue by frankok** [SharePoint/sp-dev-solutions#273]
#### Category
- [X] Question
- [ ] Bug
- [ ] Enhancement

Hi,
Just need to ask the question:
ModernSearch is not available for external users?

**Comment by wobba** [comment]
Are you asking due to an issue? Start by reading this post from @LauraKokkarinen https://laurakokkarinen.com/sharepoint-online-guest-user-troubles-and-how-to-get-past-them/ which might help you out.

**Comment by frankok** [comment]
Hi Mikael,
I will check these tips from Laura, and see if it helps. Looks like use of Communication Site might be the reason why external users don't get any content.
