### ISSUE TITLE
Newly Added refiner not getting displayed

### ISSUE THREAD

**Issue by Harshagracy** [SharePoint/sp-dev-solutions#276]
#77  Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior

When added new refiners from the refiners property pane, it should appear in the UI

## Observed Behavior

I have added a AUTHOR in the refiners properypane. Also it is available in the selected properties.

## Steps to Reproduce
Selected 'Author' in the selected properties from search result webpart's propery pane. 
Edited the refiners and Added Author as one of the property. 

I could still see only created and size refiner, not the author refiner.

Please note: my search result webpart is working as expected

Please find the screenshots.
![Edit refiners](https://user-images.githubusercontent.com/14230498/63930545-2c9b4800-ca71-11e9-8565-ff1d4cba196c.PNG)
![refiner result](https://user-images.githubusercontent.com/14230498/63930547-2c9b4800-ca71-11e9-88a0-26baa308cc8b.PNG)
![selected properties](https://user-images.githubusercontent.com/14230498/63930548-2c9b4800-ca71-11e9-8553-d27f362d2226.PNG)

Please let me know if I am missing something.

**Comment by wobba** [comment]
Neither of those managed properties are refinable (by default). You need to make sure you are using a refinable managed property as a refiner. Not sure if we can filter the list on the query we are currently using.

![image](https://user-images.githubusercontent.com/51104/63934822-7e85a300-ca5c-11e9-97a8-580354853a90.png)

**Comment by Harshagracy** [comment]
In my tenant, I could see them as refinable. 
![Capture](https://user-images.githubusercontent.com/14230498/63939076-fdda9d00-ca83-11e9-8dee-6b114441042f.PNG)

**Comment by wobba** [comment]
No...nothing in the refine column which means not refinable.

**Comment by wobba** [comment]
See https://docs.microsoft.com/en-us/sharepoint/manage-search-schema#refine-on-managed-properties for details :)

**Comment by Harshagracy** [comment]
> See https://docs.microsoft.com/en-us/sharepoint/manage-search-schema#refine-on-managed-properties for details :)

Thanks for explaining.. that helped me...
