### ISSUE TITLE
Can't perform NPM INSTALL

### ISSUE THREAD

**Issue by MrDrSushi** [SharePoint/sp-dev-solutions#28]
Just downloaded the solution by using the instruction through GIT CLONE.

Tried to install the dependencies by calling **NPM INSTALL** and got the following error:

C:\DEV\sp-dev-solutions\solutions\ContactManagement>npm i
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated es6-collections@0.5.6: not actively maintained anymore
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated @types/whatwg-fetch@0.0.30: fetch types are now provided by '--lib dom'
npm WARN deprecated @types/log4js@2.3.5: This is a stub types definition for log4js (https://github.com/nomiddlename/log4js-node). log4js provides its own type definitions, so you don't need @types/log4js installed!
npm WARN deprecated @types/chalk@2.2.0: This is a stub types definition for chalk (https://github.com/chalk/chalk). chalk provides its own type definitions, so you don't need @types/chalk installed!
npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
npm WARN deprecated browserslist@1.3.6: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.

> deasync@0.1.13 install C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\deasync
> node ./build.js

`win32-x64-node-8` exists; testing
Binary is fine; exiting

> node-sass@3.13.1 install C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> phantomjs-prebuilt@2.1.16 install C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at C:\Users\user\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\phantomjs-prebuilt\lib\phantom
Copying extracted folder C:\Users\user\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip-extract-1535946597025\phantomjs-2.1.1-windows -> C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\phantomjs-prebuilt\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe

> @microsoft/sp-loader@1.0.0 install C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\@microsoft\sp-loader
> node npm-install-script.js

> node-sass@3.13.1 postinstall C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\node-sass
> node scripts/build.js

Building: C:\nodejs\node.exe C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\nodejs\\node.exe',
gyp verb cli   'C:\\DEV\\sp-dev-solutions\\solutions\\ContactManagement\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@8.9.4 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\DEV\\sp-dev-solutions\\solutions\\ContactManagement\\node_modules\\which\\which.js:13:12)\n    at F (C:\\DEV\\sp-dev-solutions\\solutions\\ContactManagement\\node_modules\\which\\which.js:68:19)\n    at E (C:\\DEV\\sp-dev-solutions\\solutions\\ContactManagement\\node_modules\\which\\which.js:80:29)\n    at C:\\DEV\\sp-dev-solutions\\solutions\\ContactManagement\\node_modules\\which\\which.js:89:16\n    at C:\\DEV\\sp-dev-solutions\\solutions\\ContactManagement\\node_modules\\isexe\\index.js:42:5\n    at C:\\DEV\\sp-dev-solutions\\solutions\\ContactManagement\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (C:\\DEV\\sp-dev-solutions\\solutions\\ContactManagement\\node_modules\\which\\which.js:13:12)\n    at F (C:\\DEV\\sp-dev-solutions\\solutions\\ContactManagement\\node_modules\\which\\which.js:68:19)\n    at E (C:\\DEV\\sp-dev-solutions\\solutions\\ContactManagement\\node_modules\\which\\which.js:80:29)\n    at C:\\DEV\\sp-dev-solutions\\solutions\\ContactManagement\\node_modules\\which\\which.js:89:16\n    at C:\\DEV\\sp-dev-solutions\\solutions\\ContactManagement\\node_modules\\isexe\\index.js:42:5\n    at C:\\DEV\\sp-dev-solutions\\solutions\\ContactManagement\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\DEV\\sp-dev-solutions\\solutions\\ContactManagement\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\DEV\sp-dev-solutions\solutions\ContactManagement\node_modules\node-sass
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-09-03T03_50_05_787Z-debug.log

#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
running NPM I or NPM INSTALL would download all the modules into node_modules folder, enabling the execution of the solution through GULP SERVE

I'm using NODE 8.9.4 (Currently using 64-bit executable)

#### Observed Behavior
several errors - I don't know what went wrong

#### Steps to Reproduce
C:\DEV\ **git clone** https://github.com/SharePoint/sp-dev-solutions.git  {worked!]
C:\DEV\sp-dev-solutions\solutions\ContactManagement>**npm i** [partially failed]

**Comment by seaSide974** [comment]
Same issue here when trying to install ContactManagement : "gyp verb which failed Error: not found: python2"

`gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\jeff\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:275:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "c:\\DEV\\SPFX\\sp-dev-solutions\\solutions\\ContactManagement\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd c:\DEV\SPFX\sp-dev-solutions\solutions\ContactManagement\node_modules\node-sass
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jeff\AppData\Roaming\npm-cache\_logs\2018-09-18T15_19_04_499Z-debug.log`

Ive npm 5.5.1, node 8.11.4, typescript v1.0.3.0

**Comment by ryanmcdonough** [comment]
You'll need to install Python 2 and PhantomJS as suggested in the error message.

**Comment by ryanmcdonough** [comment]
Should be closed, not a bug.

**Comment by Ashutosh2019** [comment]
I was having problem with "PhantomJS not found on PATH" . It is more to do with proxy. I have switched to non proxy connection and it all works file.
This reported issue can be closed.
