### ISSUE TITLE
Question: Library Path

### ISSUE THREAD

**Issue by gristy58** [SharePoint/sp-dev-solutions#283]
#### Category
- [x ] Question
- [ ] Bug
- [] Enhancement

Hello,

Does anyone have a good way to return the library path when searching for documents?

I would like to link to the EditForm of the library with a little edit button - something like this:

<a id="link" href="{{SitePath}}/Forms/EditForm.aspx?ID={{ListItemID}}" target="_blank"><i class="ms-Icon ms-Icon--EditNote" aria-hidden="true"></i></a>

However unfortunately SitePath returns something not usable

**Comment by wobba** [comment]
The `ParentLink` managed property would for example give `https://contoso.sharepoint.com/Delte dokumenter/Forms/AllItems.aspx` which can be manipulated to a EditForm link. Does that help?

**Comment by gristy58** [comment]
Thanks Wobba.

This is what i was thinking and was trying it with SitePath as everything after ; can be removed.

I was just struggling to figure out how to do it and then use it in the items loop for each item in the handlebars.

**Comment by gristy58** [comment]
Can you provide a example please

**Comment by wobba** [comment]
I'm not a handlebar expert but you might can use the `replace` function to replace AllItems.aspx with the right string. See https://github.com/helpers/handlebars-helpers#replace

**Comment by gristy58** [comment]
thank you, unfortunately, ParentLink does not provide that output, but it provides a link to the folder of the document.

**Comment by gristy58** [comment]
my page only has 3 librarys so for now i have just done a contains statement that should work ok :)

**Comment by wobba** [comment]
Folders.. aghhh... that complicates matters. Googled a bit and you can use this which is an old gem from 2008 - https://weblogs.asp.net/jan/copyutil-aspx-a-little-sharepoint-gem :D

`{SPWebUrl}/_layouts/15/copyutil.aspx?Use=id&Action=editform&ItemId={ListItemID}&ListId={ListID}&InThisWeb=1`

**Comment by gristy58** [comment]
Perfect!
