### ISSUE TITLE
Modern search: transform date-managed property

### ISSUE THREAD

**Issue by RicoNL** [SharePoint/sp-dev-solutions#284]
#### Category
- [ ] Question
- [ ] Bug
- [x] Enhancement

#### Expected or Desired Behavior

I have a managed property, RefinableDate01, linked to a site column which contains a Date without Time. After a search, inspecting the retrieved value for this managed property using the debug-render template is, the value returned is "10/21/2019 10:00:00 PM", while the date  entered in the item is '10/22/2019. 2 hours difference is caused by West European Daylight Saving Time.

I would like to be able to transform the value back to 10/22/2019 (as entered in the item) when the value of this managed property is retrieved and displayed in the Details list-template. 

Handlebars expression I tried for this in 'Manage columns' to no avail is : 

{{getDate RefinableDate01 'l' 3}}

Subsequently it would be great if sorting on this column in the Details-list would be possible.

Thanks!

**Comment by RicoNL** [comment]
Close this issue, same problem as discussed in this issue: https://github.com/SharePoint/sp-dev-solutions/issues/192

Also used other crawled property in managed property which returns "2019-10-21T22:00:00Z" in search result. Then with above mentioned expression is getting the correct date.

**Comment by Fnu-Avi** [comment]
@RicoNL I'm also facing the same issue. Can you please tell me which managed property you ended up using?

**Comment by wobba** [comment]
`getDate` only works with the format mentioned by @RicoNL as stated in the docs (https://microsoft-search.github.io/pnp-modern-search/search-parts/templating/)

**Comment by RicoNL** [comment]
I used a <fieldname>OWSDATE-text managed property.

**Comment by wobba** [comment]
If it doesn't have the expected format, log an issue at https://github.com/microsoft-search/pnp-modern-search for improved date handling. We also accept PR's for solving this :)
