### ISSUE TITLE
Search managed metadata refiner values with GUID

### ISSUE THREAD

**Issue by muges01** [SharePoint/sp-dev-solutions#285]
#### Category
- [ ] Question
- [x] Bug
- [] Enhancement

#### Expected or Desired Behavior

The search refiner should only display the managed metadata values **without** the GUID.

#### Observed Behavior

The search refiner displaying managed metadata values **with** GUID.

![image](https://user-images.githubusercontent.com/22563887/64213639-99657680-cea5-11e9-9f76-d04e2c07dbb3.png)

#### Steps to Reproduce

1. Created custom taxonomy metadata called 'Business Area' in terms store
2. Create custom site column for managed metadata called 'Business Area' and mapped the 'Business Area' taxonomy metadata
3. Create site content type called 'My Document'
4. Add custom site column which was created in step 2 to the site content type ('My Document')
5. Create document library on the site called 'My library'
6. Add the site content type ('My Document' to the newly created document library 'My Library'
7. Upload documents to the library and set the document content type to 'My Document'
8. Update the metadata property to each document accordingly
9. Add the refinable crawled property for this newly created taxonomy metadata under Search Schema - eg. RefinableString01 and mapped to 'ows_BusinessArea'
10. Wait couple of minutes or hours to make sure the contents are crawled
11. Create a page and add the 'Search Refiner', 'Search Box' and 'Search Results' webpart.
configure the webparts accordingly 
**Note**: Make sure add the custom taxonomy metadata property under the 'Search Refiner' configuration and save
12. Save the page and try to search for the document which was uploaded in My library

I hope someone could help me or point me to the right direction.
Thank you in advanced.

**Comment by wobba** [comment]
Hi,
See the documentation at https://github.com/SharePoint/sp-dev-solutions/tree/master/solutions/ModernSearch/react-search-refiners#miscellaneous-taxonomy-values-dynamic-translation on how to get taxonomy values to work.

If you only want the text and no translation, map the ows_columnname (as long as the field is set to show the label only), and that will also work.

**Comment by muges01** [comment]
Hi @wobba ,

I have mapped to ows_taxId_BusinessArea. It's now removed the GUID but I'm getting duplicate values.
![image](https://user-images.githubusercontent.com/22563887/64295709-bf544f00-cf69-11e9-9f40-e0c01b790c8c.png)

What am i missing?

**Comment by muges01** [comment]
Hi @wobba ,

Thank you very much. It is working now.

**Comment by Mario4272** [comment]
@wobba Can you point me to the directions for this again please.  The link you posted above is no longer working "404 error"

**Comment by wobba** [comment]
@Mario4272 it's in the docs https://microsoft-search.github.io/pnp-modern-search/v3/search-parts/search-results/#miscellaneous-taxonomy-values-dynamic-translation
