### ISSUE TITLE
How do I change the display templates for cards from the tiles layout and add managed properties?

### ISSUE THREAD

**Issue by colonelclaypoo** [SharePoint/sp-dev-solutions#286]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

Hi there,
I have a question if I may: How do I change the display templates for cards from the tiles layout?
The default tiles layout template has code I'm not familiar with, e.g.:

`                        {{#> resultTypes item=item}}
                            {{!-- The block below will be used as default item template if no result types matched --}}
                            {{#eq item.contentclass 'STS_ListItem_851'}}
                                <video-card item="{{JSONstringify item}}" fields-configuration="{{JSONstringify @root.documentCardFields}}" enable-preview="{{@root.enablePreview}}" show-file-icon="{{@root.showFileIcon}}" is-compact="{{@root.isCompact}}"></video-card>
                            {{else}}
                                <document-card item="{{JSONstringify item}}" fields-configuration="{{JSONstringify @root.documentCardFields}}" enable-preview="{{@root.enablePreview}}" show-file-icon="{{@root.showFileIcon}}" is-compact="{{@root.isCompact}}"></document-card>
                            {{/eq}} 
                        {{/resultTypes}}
`

I noticed that some managed properties such as title will be displayed in the card based on whether or not I pick it in the 'select properties' menu no page two of the search results webpart.
However, almost no other properties will be added to the card that I choose from there. How do I manage to add a managed property to the card?

Thanks a lot.

**Comment by FranckyC** [comment]
Hi @colonelclaypoo did you use the "Manage card fields" builder from the property pane to map your managed properties?

**Comment by colonelclaypoo** [comment]
> Hi @colonelclaypoo did you use the "Manage card fields" builder from the property pane to map your managed properties?

Hi @FranckyC, no I had not seen it. Just noticed that I had the template on "custom" right from the get go but choosing "tiles" shows the button. Thanks!
