### ISSUE TITLE
Search Results Web Part: "Error making HttpClient request in queryable[500]"

### ISSUE THREAD

**Issue by CameronWThomas** [SharePoint/sp-dev-solutions#287]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Should be returning search results as per usual.

#### Observed Behavior

Search results inexplicably changed from returning results to a red error box stating the following:

> Error making HttpClient request in queryable [500]  ::> {"odata.error":{"code":"-1, Microsoft.Office.Server.Search.REST.SearchServiceException","message":{"lang":"en-US","value":"An unknown error occurred."}}}

No changes, that i was aware of, were made to our site. It just suddenly stopped working as expected.

#### Steps to Reproduce

Simply attempt to use a Search Results Web Part. Any query returns this same error and is unable to pull any content

**Comment by FranckyC** [comment]
Hi @CameronWThomas Can you open the browser console and see if there are more details about the issue?

**Comment by CameronWThomas** [comment]
Looks like im getting a 500 server error at this request URL 

> https://mysite.sharepoint.com/sites/mysubsite/_api/search/postquery

**Comment by FranckyC** [comment]
Do you have any details? What was the request? What was the response?

**Comment by CameronWThomas** [comment]
I set up a blank search result webpart with the query of "*" and this is what i got

Request:
`{
  "__metadata": {
    "type": "Microsoft.Office.Server.Search.REST.SearchRequest"
  },
  "ClientType": "ContentSearchRegular",
  "Properties": {
    "results": [
      {
        "Name": "EnableDynamicGroups",
        "Value": {
          "BoolVal": true,
          "QueryPropertyValueTypeIndex": 3
        }
      },
      {
        "Name": "EnableMultiGeoSearch",
        "Value": {
          "BoolVal": true,
          "QueryPropertyValueTypeIndex": 3
        }
      }
    ]
  },
  "Querytext": "*",
  "EnableQueryRules": false,
  "QueryTemplate": "{searchTerms} Path:{SiteCollection}",
  "RowLimit": 10,
  "SelectProperties": {
    "results": [
      "Title",
      "Path",
      "Created",
      "Filename",
      "SiteLogo",
      "PreviewUrl",
      "PictureThumbnailURL",
      "ServerRedirectedPreviewURL",
      "ServerRedirectedURL",
      "HitHighlightedSummary",
      "FileType",
      "contentclass",
      "ServerRedirectedEmbedURL",
      "DefaultEncodingURL",
      "owstaxidmetadataalltagsinfo",
      "UniqueID"
    ]
  },
  "TrimDuplicates": false,
  "SortList": {
    "results": [
      {
        "Property": "Created",
        "Direction": 0
      },
      {
        "Property": "Size",
        "Direction": 1
      }
    ]
  },
  "Culture": 1033,
  "Refiners": "",
  "HitHighlightedProperties": {
    "results": []
  },
  "RefinementFilters": {
    "results": []
  },
  "ReorderingRules": {
    "results": []
  }
}`

And got a response with the error code 500. This was the response header:

`cache-control: private, max-age=0
content-type: application/json;odata=nometadata;streaming=true;charset=utf-8
dataserviceversion: 3.0
date: Thu, 05 Sep 2019 18:22:22 GMT
expires: Wed, 21 Aug 2019 18:22:17 GMT
last-modified: Thu, 05 Sep 2019 18:22:17 GMT
microsoftsharepointteamservices: 16.0.0.19228
ms-cv: nwFNaHTQAABD6utEGZTRqg.0
p3p: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
request-id: 684d019f-d074-0000-43ea-eb441994d1aa
set-cookie: rtFa=p40ZS2enQ+WNECGxN80PxUBRhzPbNddmjOjdZ3Ni7n8mMTdERkVERTQtNUQwMS00QjgwLTlFRkEtQzJFRTg5NTg1QzQyTbIrsNr3YRAJ2dkMLvl8enQmol0Ic7CEAkkc1DnQBEF9XPal5JoE55wxHMijTAPsJvlHT8bqXrF61aFdsujNg0TOm+5UqjYlNLx9JBqQSCWVPH+eSjHQp/DpjUNHiUXDRrWqv5DCNPLAnurgSCYkbJfZDdEqQsD6JpabB4xIAKQuGCKt3xVWsWPOMoR5+KLOhKM5LmrLytgfa+AC0Xnvq8B/XIHT3YedeOpxNSHEHl3XG55fznNlk/GOoS7qldOWp2u6DdmThJvBqwKsWAF79kHVxZVPvFmH8Gqk6j/VE6nfJduVTTlJ9HByfVxVZ6UmHUr4317IdXlwALpejLJH40UAAAA=; domain=sharepoint.com; expires=Tue, 10-Sep-2019 17:47:47 GMT; path=/; secure; HttpOnly
set-cookie: FedAuth=77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48U1A+VjYsMGguZnxtZW1iZXJzaGlwfDEwMDMyMDAwNGFkZjNkYjBAbGl2ZS5jb20sMCMuZnxtZW1iZXJzaGlwfGN0aG9tYXMxQHVuZGVyYXJtb3VyLmNvbSwxMzIxMDA5MDg1NjAwMDAwMDAsMTMyMDQ2NzEzNTYwMDAwMDAwLDEzMjEyNjExMjY3MTA4NDcyMywyMTYuMjMwLjEwOS4yMzgsMywxN2RmZWRlNC01ZDAxLTRiODAtOWVmYS1jMmVlODk1ODVjNDIsLFYyITEwMDMyMDAwNEFERjNEQjAhMTMyMTAwOTA4NTYsYzk4M2Y5OWUtNDAzMi0wMDAwLTQ2ZTgtZjg5ZjFjNGVhYTZlLDZlNGIwMTlmLTEwYzEtMDAwMC00M2VhLWUwNTRlOGUwYzU3YiwsMCwxMzIxMjE4Mjg2NzEwODQ3MjMsMTMyMTI0Mzg0NjcxMDg0NzIzLCwsLFlMa1BkaCtOdVFWeUVxMWxydnlZRkV3L2tKNnFSRUg0em9EcG04NUlmRkhMbkFyQm1xTndBWDloaVptbjdBekI0RDB6Nm9KYUFPMUtkcmZlU3lPdDllVDAwcUR6MjJwV1hRM1g3ZURtbHBUL2lFNkdyNWs0V2x2K1BkY1ZwWE1YWWpBZWJsWnNTdDJ2N1RrWTRMMmVoMnFDT1ZEa3gxUm9sakl5QW1BTGROcWJoWlI2V2phQ0crMjByWEh5TjBUY0RLcGNzRmpvb0ZQaFZMNDNIc0t5Sk5NV1IyY1VmRVhPWG5sa0JIYU5mSmlXMFN5ZTlwcldmelk2b1pEWHZIZkx1dFIrMHhSY0I4dkhGTE52U2xtRjgyWEhBMTNXZHZkMmh4Sm9DZGhwdFVmeVdNUkdMSHZ6UUhqWWV5cW1CaFhXZG1yRmloOHdwTjdoWEVLMW95Qno3UT09PC9TUD4=; expires=Tue, 10-Sep-2019 17:47:47 GMT; path=/; secure; HttpOnly
spclientservicerequestduration: 5322
sprequestguid: 684d019f-d074-0000-43ea-eb441994d1aa
status: 500
strict-transport-security: max-age=31536000
x-aspnet-version: 4.0.30319
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-ms-invokeapp: 1; RequireReadOnly
x-msedge-ref: Ref A: E0A183451A5345F891A6F5ACC4BE253C Ref B: BL2EDGE0812 Ref C: 2019-09-05T18:22:18Z
x-powered-by: ASP.NET
x-requestdigest: 0xE4B3A8065AF8D114390594ECDE633243E60CC8354363990CDFDF7A63F8EDA3E2C1A0B6B7DECB6F37F9A5B6A1AE6D79FF73F064B55F253881F475A479CC42EEFF,05 Sep 2019 18:22:17 -0000
x-sharepointhealthscore: 3
x-sp-serverstate: ReadOnly=0`

Thats the best i could find with the response. I'll keep looking to see if i can find anything more.

**Comment by wobba** [comment]
Query looks ok to me. If you change the query, or which mp's to get back, always 500?

**Comment by CameronWThomas** [comment]
@wobba Thats correct. I also just tested it on a different SharePoint domain entirely, to ensure that it wasn't just the server i was operating on, and i am getting the same issue there as well.

**Comment by FranckyC** [comment]
So you run the default WP configuration? What if you remove/add the WP again on a page?

**Comment by CameronWThomas** [comment]
@FranckyC Gave it ago, but still having the same issue.

**Comment by FranckyC** [comment]
Weird, could be something with the SharePoint search itself since the query seems OK. You could try to make the same query using Search Query Tool to see if it is the same issue.

**Comment by wobba** [comment]
...or another tenant if you can.

**Comment by CameronWThomas** [comment]
Oddly enough, it's working fine today. I tried it in 2 different tenants yesterday too and had the same issue. I'm wondering if maybe it was on SharePoint's side and there was some issue in my region. Nonetheless it seems to be working fine now, thanks for the assistance!

**Comment by yakubmohd** [comment]
Can any one please help me in resolving the above mentioned issue.
