### ISSUE TITLE
Custom Refiners not available 

### ISSUE THREAD

**Issue by Harshagracy** [SharePoint/sp-dev-solutions#289]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

####  Behavior in classic site

In the classic page, I have added the search web part with refiners. In the refiners, I have selected my RefinableString00 which points to the managed properties for a status column. The refiner works absolute fine and shows the value as per the search result web part. 
![classic](https://user-images.githubusercontent.com/14230498/64509291-055c3a80-d2fd-11e9-82df-cb5546b7a464.PNG)

This is the refiner configured: 
![refiner](https://user-images.githubusercontent.com/14230498/64509383-389ec980-d2fd-11e9-81ad-0c462b330dd0.PNG)

#### Behavior in Modern site

I am using PnP modern search solution. In the refiners' web part, I selected the properties that I wanted to be refinable. I have selected the status column(same one as shown in classic webpart) which appears in the managed properties dropdown. I did not find any refinablestrings in that dropdown.  After configuring, it is not getting displayed. I have 'created by' as another refiner (which comes by default), which is rendering in the UI without any issue. I have noticed that this issue is happening for the custom site columns, even though they are refinable. 

#### Expected Behavior in Modern site

Like the classic refiner web part, I am expecting the refinable strings should be displayed in the modern search refiners web part. else, the selected managed properties should be refinable.

**Comment by wobba** [comment]
If you configure the connection to/from the web parts it should work if the query you have setup includes values for the refiner.

What is the query and query template you are using - are they correct for the scenario you are setting up?

![image](https://user-images.githubusercontent.com/51104/64527608-aa2f4580-d306-11e9-9d1d-12793bb597e5.png)

**Comment by FranckyC** [comment]
Hi @Harshagracy Just in case, remove the `Path:{Site}` expression in the query template property pane field. It is a frequent cause of 'missing' data.

**Comment by wobba** [comment]
@FranckyC maybe we should remove that as a default filter?

**Comment by FranckyC** [comment]
Probably because there is a lot of confusion and maybe too technical for lambda users :(.

**Comment by Harshagracy** [comment]
Hi @wobba , @FranckyC , 
Thanks for your respose. @wobba : I have tried that as well before reporting in github. Please find the screenshot. To show you, i tried again.  Still, it didn't work. :'(
![refiner1](https://user-images.githubusercontent.com/14230498/64587324-a100b000-d3bc-11e9-98be-55182c8f0288.PNG)

@FranckyC : I have custom query to search in the site collection level. This is my query : {searchTerms} (ParentLink:{/Libname/} AND (ContentTypeId:{0x0120D*}))

It works as expected and returns the proper result. 

I even added RefinableString00 in the selected properties at the end. 
I am just stuck with this issue for the past week. Hoping you guys could help.

**Comment by wobba** [comment]
@Harshagracy Can you use the SharePoint Search Query Tool, add RefinableString00 as a refiner and see if you get data back. If not, then you've missed something on getting values into the refiner - and it's not an error on these web parts. :)

**Comment by Harshagracy** [comment]
I marked the thread as question instead of bug. :)  I am getting values in search query tool as well. I will explore further to fix my issue. thank you.

**Comment by wobba** [comment]
@Harshagracy If you configure the result wp to send refiner values to the refiner wp, and configure the refiner wp to interact with the result wp. Then add RefinableString00 as you have configured, I don't really see why it shouldn't work if you get values from the other refiners. I'm testing with custom RefinableString props right now with no issues - all mapped at the tenant level.
