### ISSUE TITLE
Parentheses Breaking Search Results

### ISSUE THREAD

**Issue by MattSyntaxError** [SharePoint/sp-dev-solutions#292]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
I want to search through a single document library. The search box webpart works great for placing the results I expect into the search results webpart. Except when I start using single parentheses.

#### Observed Behavior

It returns what seemingly looks like the majority of my site's contents. It seems like my query template has no affect to these particular results. I can mitigate this problem by using the Synonyms in the Search Results webpart, but this method won't work for every combination that breaks the search. If a user inputs a single parentheses, they can attach any number of characters afterwards and the results will be identical. 

![image](https://user-images.githubusercontent.com/52333755/64630240-8a049280-d3a9-11e9-8773-bfe8e088a4a5.png)
I have two pages of content total to search through because my list contains 11 items and the results show 10 per page.

Clicking the filter shows the filetypes
![image](https://user-images.githubusercontent.com/52333755/64630548-36df0f80-d3aa-11e9-8e95-0aaa28586b0e.png)

![image](https://user-images.githubusercontent.com/52333755/64630464-07c89e00-d3aa-11e9-9cf9-5fff5e79d38e.png)
Now I have more than 5 pages? Wrong! I have over 2000 pages. 

![image](https://user-images.githubusercontent.com/52333755/64630641-5fffa000-d3aa-11e9-9a0f-4b74fd80e274.png)
The filter shows that I have over 15 thousand items showing up. What?!

Known queries that cause this problem:
(
)
()
)(
(asdfasdfasdf
)adfasdfasdfas

#### Steps to Reproduce

1. Set up a page with the Box and Search webparts and connect them. 
2. Connect the search to a document library.
3. Set up the doc lib with some test data so you can test the search
4. Type a single parentheses into the search box and press enter

**Comment by wobba** [comment]
Parenthesis will break the parsing most likely. Two options. Create a parser to validate matching () as they are part of KQL operators/syntax and not treated as a letter.

Or... leave as is - intended. Try in the OOB search box and my guess is you can mess up the totalt query.

What does your query template look like?

**Comment by mmohamedbasith** [comment]
Hi @MattSyntaxError , i am facing issue with pagination. Clicking on any number in paginzation loads only the first page (rarely loads the correct page) . Is it working for you?
