### ISSUE TITLE
{Page.<FieldName>.Label} or {Page.<FieldName>.TermID} Issue in Search webpart for Modern Pages.

### ISSUE THREAD

**Issue by NeoLegolas** [SharePoint/sp-dev-solutions#293]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

{Page.FieldName.Label} or {Page.FieldName.TermID} not working in Query Template In Pnp Search Webpart. I'm trying to use a Taxonomy Field and using its internal name with Label and TermID but it returns no value. {Page.Title} works fine.

#### Observed Behavior

No results are available when trying to modify the query using Page Properties for Taxonomy field.

#### Steps to Reproduce
{searchTerms} ContentTypeId:0x0101009D1CB255DA76424F860D91F20E6C4118* {searchTerms}  Path:{Site.URL}  returns 9 results but this returns no resut:
{searchTerms} ContentTypeId:0x0101009D1CB255DA76424F860D91F20E6C4118* {searchTerms}  Path:{Site.URL} {SearchTerms} {Page.Topic.Label}  
I have a Taxonomy field with Internal name Topic and have items many items with same tag as current page. Even using {Page.Topic.TermID} returns no results.

Thanks for your contribution! Sharing is caring.

**Comment by wobba** [comment]
I'll close this one as a duplicate.
