### ISSUE TITLE
Proper results are not fetching from the Events Calender list

### ISSUE THREAD

**Issue by Ranjan131** [SharePoint/sp-dev-solutions#294]
Can anyone please suggest how to fetch the events from the events calendar list using search refiners webpart.

**Comment by wobba** [comment]
Map the field you wants crawled property to a refinable managed property, and reindex your data.

You question is a bit vague as to what you are trying to accomplish.

**Comment by Ranjan131** [comment]
I have used the managed property as RefinableDate00 and Crawled property is ows_q_DATE_StartDate. The query i have used is 
ContentTypeId:0x0102006232E0BC8AE0244CB070474711252920*  RefinableDate00>={Today} AND -RefinableString02:Public* -RefinableString02:Cultural*

Tha above query is working in classical experience which is used by content search webpart but its not fetching proper results in modern experience by using search refiner webpart.

can you please suggest me that how to use refinable in search refiner webpart.

**Comment by wobba** [comment]
So you are using RefinableDate00 as a refiner in the refiner web part? What are you seeing or not seeing? Compared to classic search or the sharepoint search query tool, when using the same query.

**Comment by Ranjan131** [comment]
Please look into the below screen shots for both classical(results coming from content search webpart) and modern experience(results coming from react search refiners webpart).

Classical experience (using content search webpart)
![image](https://user-images.githubusercontent.com/55277316/65014849-732be600-d93d-11e9-8755-3fcfe64b2943.png)

Modern Experience(using React search refiner webpart)
![image](https://user-images.githubusercontent.com/55277316/65014895-9a82b300-d93d-11e9-8a80-1de7f541ca16.png)

Actually i dont know exactly to add refiners in search refiners webpart. can you please suggest me that how to add refiners in react search refiner webpart.

Thanks in advance.

**Comment by wobba** [comment]
@Ranjan131 Ah.. you're using the result web part, not the refiner web part (which is also the project name). My mistake. You can target the list by a `contentclass` or `path` query I guess. I'll close this for now as it's not related to the web part itself, but to how you write the query.

Basically, copy the query used in the classic web part, and create a html template to render it the way you want using the handlebar templates we provide.

**Comment by Ranjan131** [comment]
@wobba 
When we deploy and install this app to sharepoint tenant we will find both Search results and Search refiners. can you please suggest me that how to fetch the proper results by using Search Results and Search Refiners webpart.

**Comment by wobba** [comment]
@Ranjan131 unfortunately not, as I don't have time for consulting. I suggest reaching out on tech community or a search course. The concepts of crawled/managed properties and configuring in classic search web parts and PnP modern search are very similar.
