### ISSUE TITLE
multliple keywords does not work

### ISSUE THREAD

**Issue by sergeluca** [SharePoint/sp-dev-solutions#295]
Hello,
I’m using the PnP search web part s(2.4.0.1) according to my app catalog.
I’ve added a search text box in my home page and it calls a result page. Everything works well. If I type "SharePoint" in the textbox , the result page get SitePages/search-results.aspx#sharepoint . In the search result I have a textbox and I can see the keyword sharepoint
However if in my homepage textbox I type several parameters (like “sharepoint+global”), even though the parameters are sent to the result page SitePages/search-results.aspx#sharepoint%20%2B%20gobal
And are visible in the result page textbox, the search is not automatically triggered like it was wth only 1 keyword. Any idea how to fix this ?
Thank you

Serge Luca

**Comment by wobba** [comment]
@sergeluca we only support the latest release ;) Seems like a bug we have solved. I recommend installing the latest version, but you might have to re-configure the web parts as I'm not sure it's config compatible 100%. https://github.com/SharePoint/sp-dev-solutions/releases/latest  I'll probably get v3.7 out next week (a bit behind as I'm travelling).

**Comment by sergeluca** [comment]
absolutely normal. I'll be waiting for the next version. Thank you @wobba  !

**Comment by wobba** [comment]
I'm pretty sure the bug is fixed after the version you are using, so will close thise one.
