### ISSUE TITLE
Data loading and throttling issues

### ISSUE THREAD

**Issue by joelfmrodrigues** [SharePoint/sp-dev-solutions#298]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Display results and complete loading

#### Observed Behavior

Searching for some word will display some results but never stop loading.
With dev tools open, I can see fetch errors being logged after some time and the account get's throttled by O365, so really hard to get more details. Even the  browser get's extremely slow during this time.

Sorry but as this is throttling the account, I am unable to test further, at least at the moment. 

#### Steps to Reproduce

Install latest dev version (as of today, 16 September).
Add web parts to a page, configure the connections and perform a search.

**Comment by wobba** [comment]
Hi,
the latest dev version should also do less queries if you have a searchbox and refiner. If you get throttled, that is due to too many requests on your tenant from 3rd party. We might can check for this and wait. Or give a better message. Are you getting 429 or 503 back?

**Comment by joelfmrodrigues** [comment]
Hi Michael,

I had to install a previous stable release (June) as this was blocking some work and unfortunately I had no chance to dedicate any time to it as the project is close to go-live date, but believe the error was 429.

**Comment by wobba** [comment]
v3.6 does fire off unneeded queries depending on the setup you have. v3.7 which is in the dev branch has fixed this. Outside of that, throttling happens due to high tenant wide usage of 3rd party calls - so it could have been you experienced this by chance.

Will close this as throttling is not just caused necessarily directly by this web part, and as I've added work to remedy the number of calls made.

**Comment by joelfmrodrigues** [comment]
Hi @wobba , just tried the latest release yesterday and still getting the same issue. After a search query, search results loads for a moment and then I get a huge amount of 429 errors on the console. And while this happens the browser (chrome) just goes crazy in memory as well. After a bit account gets throttled.
I'm 100% sure this is not caused by some other 3rd party solution.
Using a search box, search verticals, search results, paging and refiners.

I will investigate the issue and try to provide more info/help.
Can you please reopen this?

**Comment by FranckyC** [comment]
Hi @joelfmrodrigues, could be an infinite loop due to wrong dynamic data connections. How Web Parts are connected in your setup? Also, are you able to see the requests (/postquery, etc.) in the browser console?

**Comment by joelfmrodrigues** [comment]
Hi @FranckyC, thanks for the quick reply!
I will check that

**Comment by joelfmrodrigues** [comment]
Hi @FranckyC , not really sure what happened, but I removed all the web parts from the page and added again - now everything works!
I think I configured everything exactly the same, but maybe I did something different this time. Anyway, it's working :)

Thanks a lot!
