### ISSUE TITLE
Search Box is missign

### ISSUE THREAD

**Issue by kabrider** [SharePoint/sp-dev-solutions#300]
Hello, 
I installed the pnp-react-search-refiners-sp2019.sppkg on the sharepoint farm of our customer but we don't have the search box webpart only the search result webpart

I missed somethings ? 

Best regards
Bastien

**Comment by wobba** [comment]
@appieschot any ideas?

**Comment by bbass50** [comment]
Is there a new version of pnp-react-search-refiners-sp2019.sppkg that contains the Search Box web part?

**Comment by roscherm** [comment]
I miss the search box too

**Comment by wobba** [comment]
I checked the package, and today the 2019 version do not have a search box web part - so expected. I'll close for now. And we have moved repository to https://github.com/microsoft-search/pnp-modern-search
