### ISSUE TITLE
react-search-refiners small dutch localization typo

### ISSUE THREAD

**Issue by PieterTemmerman** [SharePoint/sp-dev-solutions#301]
#### Category
- [ ] Question
- [ ] Bug
- [x] Enhancement

I noticed that when in the refinement panel the 'Created' property is visualized as a date range that it says 'Van/Tog'. The correct dutch term would not be 'Tog' but 'Tot'.

![image](https://user-images.githubusercontent.com/8397358/65435175-581b1380-de20-11e9-9284-f2709c7c08a9.png)

Greetings,
Pieter

**Comment by wobba** [comment]
Thank you, fix made and will be pushed soon :)
