### ISSUE TITLE
Search refiners (v 3.6.3.0): managed metadata duplication

### ISSUE THREAD

**Issue by sergeluca** [SharePoint/sp-dev-solutions#302]
Hello,

I've noticed a duplication of managed metadata in the refiners: (it is the same metadata, because when a user select one, the other one is selected as well)
![searchduplication](https://user-images.githubusercontent.com/11420607/65494813-d70e5b80-deb5-11e9-98a4-fd0d412fbb60.png)

Thank you

Serge Luca

**Comment by wobba** [comment]
This means you have two terms which to your eye look similar, but they are not. My guess is one of them has a space at the end. Go check your term store and report back :)

**Comment by wobba** [comment]
@sergeluca can I close this one?

**Comment by sergeluca** [comment]
oh yes @wobba , I should have asked you to do it before, sorry. Some values have a space, but others don't. I will double and triple check when I will be back at the customer site. But you can close it. Thank you for your help. Serge
