### ISSUE TITLE
List item properties template/preview

### ISSUE THREAD

**Issue by ritavage** [SharePoint/sp-dev-solutions#305]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

I want to mimic the List + List properties web parts by using ModernSearch, so that when a user clicks on a search result, it's properties are shown in a separate web part. Currently the list web part can't be searched and that is what my users want.

I tried to set it up by using two Search results web parts with one showing the list of search results and the other showing 1 element, but I can't hook into what element is selected in an elegant way. Closest thing I've found is to make search result point to the current page with a querystring element with ListItemID to what element the second search result web part should show. This causes the whole page to reload and the search to reset.

Is there a nice way to achieve this by config, handlebar, spfx?

**Comment by wobba** [comment]
Hi,
That's the closest I can get as well. Two parts, and have one link to for example `https://contoso.sharepoint.com/sites/TestTeam/SitePages/Home.aspx?xid=1861` where the other part picks up the query param. I tried using fragment instead, but that didn't seem to work.

You dot get a full page load, but a smart page load so the whole screen won't flicker, but both search parts will re-render.

If you want something else you need to develop a custom renderer which can send an event to another part using dynamic data for example.

I guess it should be possible to add dynamic data triggering from the result webpart on click which another wp can subscribe to as well. Add it as an enhancement idea, and maybe someone will pick it up :)

**Comment by FranckyC** [comment]
Hi @ritavage, using an URL fragment should work to avoid a whole page refresh. Make sure you bypass the SPFx page router when you create your HTML link by using the `data-interception=off` attribute. More info here https://julieturner.net/2018/08/spfx-anchor-tags-hitting-the-target/

**Comment by wobba** [comment]
@FranckyC how do you specify which fragment to pick? If I want #q for one part and #myid=123 for the other? Url param lets you pick, didn't see that for fragment.

**Comment by FranckyC** [comment]
@wobba you can't. You can use only one value in the URL fragment.

**Comment by wobba** [comment]
So fragment might not work for this scenario with two(more) parts.

**Comment by ritavage** [comment]
Thank you both for your replies, but none work as expected.

By query param the second web part get the correct data, but I get a full page load and I loose the search box query.

By fragment I get the url updated, but it's not picked up by the second web part. data-interception=off has no impact on this.

The page will be very clean so having just the fragment is no problem if I get it to work.

**Comment by wobba** [comment]
Take a look at https://github.com/SharePoint/sp-dev-solutions/issues/328 That's the closest you get today.
