### ISSUE TITLE
Custom renderer - Query a list for additional information

### ISSUE THREAD

**Issue by ritavage** [SharePoint/sp-dev-solutions#307]
- [x] Question
- [ ] Bug
- [ ] Enhancement

I'm creating a custom result renderer to show information from a specific list and want to show lookup information related to the returned items. The fields I want to show are not available as additional fields to the lookup column, so is it possible to run a query from within the renderer?

I tried to create a new service, but the onInit() is not triggered in SearchResults.tsx so I don't have the context.

**Comment by wobba** [comment]
Sure you could. Haven't looked too much into this but if you look in `onChangeHappened` on the two sample render customizers you can run any code here before you render results. (https://github.com/SharePoint/sp-dev-solutions/blob/960f75acbb8e36e009a1fee0108d3844c617a2cd/solutions/ModernSearch/react-search-refiners-renderer/src/extensions/personRenderer/PersonRendererApplicationCustomizer.ts#L46)

Maybe @taraldga has some pointers.

**Comment by ritavage** [comment]
The onChangeHappened did the work. 

My code now runs an async/await Promise.all where the additional data is collected and sent to the renderer as part of the SearchResult element.  Works like a charm 👍 

![image](https://user-images.githubusercontent.com/16385429/66637944-5b7e0f80-ec14-11e9-86d7-98a6894c55e1.png)
