### ISSUE TITLE
File viewer web part source

### ISSUE THREAD

**Issue by robiharid** [SharePoint/sp-dev-solutions#312]
Not sure where to ask this - I want to extend the 'File Viewer' web part with my own functionality (by displaying related documents to the right hand of the file currently being viewed).

How can I download the spfx source data for me to work on?

**Comment by YannickRe** [comment]
That file viewer webpart is first party, closed source. Microsoft hasn't shared to code with us, so there is nothing to extend, I'm afraid.

**Comment by robiharid** [comment]
> That file viewer webpart is first party, closed source. Microsoft hasn't shared to code with us, so there is nothing to extend, I'm afraid.

Hi, the file viewer web part here is open source (https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-documents-detailslist) but does not work without disabling https (in serve.json) and so does not work in the tenant. Could you kindly npm install and quickly take a look?

**Comment by YannickRe** [comment]
That isn't the official file viewer webpart, it's one that has been developed separately by someone in the community. The source code exists in a separate repository too, so I suggest you log a ticket in there.
