### ISSUE TITLE
Request to add query variables (Like Classic search)

### ISSUE THREAD

**Issue by PeterVos111** [SharePoint/sp-dev-solutions#318]
#### Category
- [ ] Question
- [ ] Bug
- [x] Enhancement

I would like a query variable to pick up params like the classic search function. 
This way, i can both search in the searchbox, and use queries from different sources. Currently i can choose either to use the searchbox or a http query.

**Comment by YannickRe** [comment]
I assume you are referring to the {QueryString.<ParameterName>}? It shouldn't be too difficult to implement, I'll add it to the list of potential improvements.

**Comment by PeterVos111** [comment]
Great! would love to see this function. 

For now i created a workaround by using the 'Send the query to a new page' and sending it to the same page. That way, i can use the query from the searchbox, but also from another source, since it will put the Querystring in 'q={QueryString}'.
