### ISSUE TITLE
SP ModernSearch webpart displaying column data

### ISSUE THREAD

**Issue by bgdbgd** [SharePoint/sp-dev-solutions#319]
Hi, 

Any ideas on how to display share point list column data when search is done? 

I've created a site column but no luck with showing the results

https://imgur.com/a/jkp0AIk

**Comment by wobba** [comment]
You need to read into how a sharepoint column makes it's way into the index. Column -> crawled property -> managed property. Take a look at https://docs.microsoft.com/en-us/sharepoint/manage-search-schema for starters.
