### ISSUE TITLE
react-search-refiners: Unable to get Managed properties

### ISSUE THREAD

**Issue by theibrahimi** [SharePoint/sp-dev-solutions#324]
#### Category
- [x] Question
- [x] Bug
- [ ] Enhancement

#### 
Hello Gyus, I have  a SharePoint List with text fields, I've used Managed properties RefinableString to retrieve them using modern search query webpart.
 In the configuration panel I've add my managed properties to the properties list, and add them to my template but they aren't shown in the SharePoint Page.
Note : I've tried both : to create my own managed properties and use the RefinableString , same behiavor.

**Comment by wobba** [comment]
@theibrahimi do they show if you use the debug template? If not, maybe you did the mapping after the content was indexed. If so, you need to re-index the list to populate the fields.

**Comment by theibrahimi** [comment]
thanks @wobba for your ractivity!

I reindex the list and it work propertly !
