### ISSUE TITLE
Query {Page.<FieldName>.Label} from MultiValueTaxonomyField not working

### ISSUE THREAD

**Issue by SnappyFPV** [SharePoint/sp-dev-solutions#325]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

I use Search Result Web Part.
I want create a related content search in context of the current page. The Modern Page has a Multi-Value Taxonomy Column. In the Query i want to retrieve this page field (Display and Internal Name EC_Topic) and use it for the Query. Also add a RefinableString that receive the ows_EC_Topic.

A page was tagged with "Test 3, General" another with "General".

For Testing:
{searchTerms} Path:{Site} owstaxIdECTopic:General --- works fine 
{searchTerms} Path:{Site} RefinableString20:General --- works fine 

{searchTerms} Path:{Site} owstaxIdECTopic:{Page.EC_Topic} --- not found
{searchTerms} Path:{Site} owstaxIdECTopic:{Page.EC_Topic.Label} --- not found
{searchTerms} Path:{Site} RefinableString20:{Page.EC_Topic} --- not found
{searchTerms} Path:{Site} RefinableString20:{Page.EC_Topic.Label} --- not found

#### From Documentation
`{Page.<FieldName>} | The value of a field on the page from where the query was issued. For example, if the page from where the query was issued contained a site column named "ContentOwner," specifying {Page.ContentOwner} would allow you to query for the value of "ContentOwner." FieldName is the internal name of the field. When used with taxonomy columns, use {Page.<FieldName>.Label} or {Page.<FieldName>.TermID}`

**Comment by SnappyFPV** [comment]
> We debugged the code on our end and found that the data coming in item was in lowercase. So {Page.topic.Label} return the correct value instead of {Page.Topic.Label}.

... Solved my problem

**Comment by wobba** [comment]
This has been fixed in the upcoming 3.7 release as well.

**Comment by mohandivraniya** [comment]
Testing with version 3.7 Or using lowercase column name solves the issue for single value taxonomy fields. 

If you are using MultiValueTaxonomy field to get related data for any of those terms, it should create a query with OR for all currently tagged taxonomy values, which current code is not doing. 

For example: For a page, if your MultiValueTaxonomy column has values of Value 1, Value 2, Value 3, it should generate a query "owstaxIdMultiValueTaxonomy:Value+1 OR owstaxIdMultiValueTaxonomy:Value+2 OR owstaxIdMultiValueTaxonomy:Value+3" to get all related items for this page. 
Right now, it is generating a query like below:
owstaxIdMultiValueTaxonomy:"Value 1,Value 2,Value 3".

I will fix it if i get some time next week.

**Comment by wobba** [comment]
@mohandivraniya can you log a new issue over at https://github.com/microsoft-search/pnp-modern-search to request expansion as a feature.
