### ISSUE TITLE
Search results web part based on query string parameter not showing results when page is published

### ISSUE THREAD

**Issue by AnitaBoerboom** [SharePoint/sp-dev-solutions#328]
### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
On a page a search box web part and two search results web parts are configured.
The first search results web part is adding a query string parameter to the url where the second search results web part is getting results based on that query string parameter.

#### Observed Behavior
The second search result web part isn't showing any result based on the query string parameter when the page is published.
The second search result web part is showing the expected results when the page is in Edit mode.

#### Steps to Reproduce
Create a blank page and add a search box web part and two search results web parts.
Configuration of the web parts:
**Search box**
No specific configuration
**Search results web part 1**
Page 1
Connect to source: Search Box
Search box's properties: Search query
Search query's properties: Raw user search query
Page 3
Manage columns:
Add one column with handlebar expression:
`<a style="color:{{@themeVariant.palette.themePrimary}}" href="{{SPSiteUrl}}/SitePages/Modern-Search.aspx?selected={{Path}}">Open</a>`
**Search results web part 2**
Page 1
Connect to source: Page environment
Page environment's properties: Query string
Query string's properties: Query parameter
Query parameter's properties: _selected_
Page 2
Query template: Path:{QueryString._selected_}

Perform a search query by entering it in the search box. The first search results web part shows results and the custom column with the handlebar expression; select that link.
The second search results web part doesn't change the results based on the query string parameter added to the url.
Put the page in Edit mode and perform the same steps: the second web part shows the desired results.

Tried the code of the master branch (3.6.3) as well as the modern-search-dev (3.7.0) branch. The behavior is the same.

**Comment by wobba** [comment]
@AnitaBoerboom can you add `data-interception="off"` to the a tag. See https://julieturner.net/2018/08/spfx-anchor-tags-hitting-the-target/ for more details.

**Comment by AnitaBoerboom** [comment]
@wobba thanks, now the second search result web part shows the expected results, but unfortunately the search box lost its initial search term and the first search results web part its results based on that.
Do you have a suggestion for that?

**Comment by wobba** [comment]
@AnitaBoerboom pass in a param for the first web part as well. Something like:

```
<a href="{{SPSiteUrl}}/SitePages/Modern-Search.aspx?selected={{Path}}&q={{keywords}}">
```

and pick up the q param for the first part/box.

**Comment by AnitaBoerboom** [comment]
@wobba Tried that, but `{{keywords}}` are always empty in a column, only filled when used in the template itself.
Or am I missing something?

**Comment by AnitaBoerboom** [comment]
@wobba Thanks, it works now!
