### ISSUE TITLE
react-search-refiners: can't add onclick event to display template

### ISSUE THREAD

**Issue by theibrahimi** [SharePoint/sp-dev-solutions#332]
#### Category
- [X] Question
- [ ] Bug
- [x] Enhancement

_

#### 
Hello Guys, I'm trying to add onclick event to my custom display template to call a fucntio with pamamétre.

this is my syntaxe from my classic sharepoint display template:
`<a clicktype="Result" id="NameFieldLink" onclick="GetProfile('_#= ProfileUrl =#_');return false;" title="_#= encodedName =#_" target="_blank">_#= displayName =#_</a>`

is there any way to achieve that in modern search directly in the custom template?

Regards,

**Comment by wobba** [comment]
You need to modify the source and register your method as a handlebar helper method. This is my design to avoid random DOM and function injection. You might want to look at the custom renderer project we have which allows you to develop anything you want for rendering and script.

**Comment by theibrahimi** [comment]
Thanks for your answer.
To inject my csutom js script I'm converting it to react and add it to new tsx file in the source code, I see that there's another way to achieve it using PnP project to add script editor in modern ui.

**Comment by wobba** [comment]
@theibrahimi don't use my script ed wp please :)

If you are converting it into the source already, then adding a helper method to call it is the right approach. Check the file `react-search-refiners\spfx\src\services\TemplateService\BaseTemplateService.tsx` for other helpers already added.
