### ISSUE TITLE
Trying to get Path, Title to appear as a Refiner selection

### ISSUE THREAD

**Issue by ssomu-ms** [SharePoint/sp-dev-solutions#333]
#146 ## Category
- [X] Question
- [ ] Bug
- [] Enhancement

#### Expected or Desired Behavior

I am trying to use the Search Refiners webpart and am attempting to get the Path and FileName of the results coming back. When I add OriginalPath, SitePath, Title managed properties, I expect to see them be available in the refiners list along side the Created, Size, and FileExtension properties already added.

#### Observed Behavior

I am only seeing the Created, Size and FileExtension refiners and nothing related to the path, even though when checking the results with he SearchQueryTool, I am able to see the OriginalPath, SitePath and Title properties show up fine for the same results coming back in the SearchResults webpart connected to the refiner web part.

**Comment by YannickRe** [comment]
It feels like you are confusing the terminology a bit:
- All search properties that are returned for a search result are **managed properties**, you can use this to visualize the search result on a page. 
- **Some** of these managed properties are marked as **refinable** and can thus be used in the Search Refiners Web Part

In your specific case, this means the following: OriginalPath, SitePath and Title aren't **refinable** and that is why they don't show up in the refiners web part. You can still use them in the search results web part templates to visualize the data.
For these properties, it also doesn't particularly make sense for them to be refinable. A refiner is supposed to **group** results based on **common** values. Like 100 results, of which 50 are ppt's and 25 are docx and 25 are xlsx. The 3 managed properties have unique values for each result, so it would show 100 values in the search refiners web part for SitePath.

Hope this clears up some confusion.

**Comment by ssomu-ms** [comment]
Yannick, thanks for the reminder about refinable check here... was trying to replicate a site based refiner I worked with in OnPrem search before.. Found SPSiteUrl that I could use here instead.
