### ISSUE TITLE
How to get this.context inside onChangeHappened method in react-search-refiners-renderer

### ISSUE THREAD

**Issue by mohandivraniya** [SharePoint/sp-dev-solutions#335]
I am creating a custom search result renderer inside react-search-refiners-renderer. 
I need to pass this.context (ApplicationCustomizerContext) to the SearchResult.tsx component. 
SearchResult is rendered from onChangeHappened method.
I am struggling to get a reference to this.context in this method. 
I also tried to set a private variable in onInit method and then use it inside onChangeHappened method. However, that also doesn't work as this is not available inside onChangeHappened method.

**Comment by wobba** [comment]
You can use a static wrapper similar to what I did using the Graph: https://www.techmikael.com/2018/09/example-of-wrapper-to-ease-usage-of.html

I'll close this one as it's more a general React/JavaScript question - and not related to the solutions themselves.
