### ISSUE TITLE
Managing search dictionaries: Spelling Suggestion is not working

### ISSUE THREAD

**Issue by Rambabu2020** [SharePoint/sp-dev-solutions#338]
Hi Team,

Sharepoint Online "Did you mean?"  spelling correction is not showing?

**Comment by wobba** [comment]
Hi, good idea so I added this just now. In the v3.7 upcoming release you you can add something like the below your your handlebar template to show and handle suggestions:
```
{{#if spellingSuggestion}}
	Did you mean <a href="#q={{spellingSuggestion}}">{{spellingSuggestion}}</a>?
{{/if}}	
```

as long as you configure the logic to pick up the query parameter when clicking.

If you get a query suggestion in classic search, then you should get one back now as well.

**Comment by wobba** [comment]
As a note - currently it won't show if there are 0 results. Will see if I can fix this as well.

**Comment by wobba** [comment]
Right now it won't show suggestion on 0 results - looking to see how that logic can be joined with the "show blank" switch.

**Comment by ravinleague** [comment]
Hi @wobba, is this feature included in the version 3.7 ? Because I still cannot see "Did you mean ?" .. Please advise

**Comment by wobba** [comment]
You need to add it to the template yourself. See `{{spellingSuggestion}}` https://github.com/microsoft-search/pnp-modern-search/blob/master/docs/search-parts/templating.md

**Comment by ravinleague** [comment]
Thanks @wobba , However, I don't see any suggestions ?

**Comment by wobba** [comment]
Add some hard coded ones to test. It's based on curated dictionaries and learning, so hard to test out. https://docs.microsoft.com/en-us/sharepoint/manage-search-dictionaries#manage-query-spelling-correction
