### ISSUE TITLE
Office Documents have a preview and icon but not the other documents like zip, msg etc. Is there any way to accomplish this?

### ISSUE THREAD

**Issue by gauti786** [SharePoint/sp-dev-solutions#340]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

**Comment by wobba** [comment]
![image](https://user-images.githubusercontent.com/51104/67939534-107f6880-fbd2-11e9-8a25-1a8d1389108a.png)

v3.7 has pretty nice icons for most file types :) Released yesterday.

**Comment by wobba** [comment]
@gauti786 did this solve your issue?
