### ISSUE TITLE
GroupedList list - grouping results by a managed property

### ISSUE THREAD

**Issue by allafridman** [SharePoint/sp-dev-solutions#344]
In the description it says: **Integrate multiple Office UI Fabric components (DocumentCard, Panel, GroupedList...**

Could you please point to an example of displaying results as grouped list - grouping results by a managed property

**Comment by wobba** [comment]
It's currently used in the refiners internally, not exposed. We should probably clean up the docs a bit as this part is left over from when this was a sample on how to do SPFx bits.

To group you would need to use handlebars to work on the data per page.

**Comment by allafridman** [comment]
Thank, it worked out very nicely:
{{#group items by="RefinableString00"}}
    <h1>{{ value }}</h1>
       {{#each items as |item|}}
       <li...
                </li>
 
    {{/each}}
{{/group}}
