### ISSUE TITLE
document preview - table view

### ISSUE THREAD

**Issue by bezua** [SharePoint/sp-dev-solutions#348]
- [x] Question
- [ ] Bug
- [ ] Enhancement

Hi guys,
I’m happy to use modern search web part. I appreciate your hard work.
I have a question related to search results webpart and “Details list” results layout.
It there a way to present document preview in a dedicated column? Bases on simple list, I was able to present image preview, however I’m not able to get interactive preview pane for documents like pdf or doc – I mean document preview with scrolls. Is this achievable using handlebars in details list layout? 
Thanks and Regards,
Bezua

**Comment by FranckyC** [comment]
Hi @bezua, did you try this [https://microsoft-search.github.io/pnp-modern-search/search-parts/templating/#elements-previews](https://microsoft-search.github.io/pnp-modern-search/search-parts/templating/#elements-previews)?

**Comment by bezua** [comment]
@FranckyC , yes, I did.
It looks almost good. Preivew image is there, but there is no callback after clicking it. 
data-src, data-url attributes are set, 
class document-preview-item img-preview
but not callback raising it up.

I will try with custom template one, not "Details list".
Btw. Simple list works well.

**Comment by FranckyC** [comment]
@bezua I tested with the latest version using the following snippet on a new column and it works.
```
<img class="document-preview-item img-preview" width="120" src="{{ServerRedirectedPreviewURL}}" data-src="{{ServerRedirectedPreviewURL}}" data-url="{{ServerRedirectedEmbedURL}}" /> 
```

![image](https://user-images.githubusercontent.com/5659122/68692478-9345e300-0543-11ea-98fd-a52a4af8c661.png)

Can you try with the latest version? Also for other issues, please use the new repo here [https://github.com/microsoft-search/pnp-modern-search](url)

**Comment by bezua** [comment]
@FranckyC 
Thanks for your support!
Finally it figured out, that other webpart on this page brought invalid css styles. Preview was always there but displayed off the stage. Thank you.
