### ISSUE TITLE
react-search-refiners: Default search query doesn't work when target specific fields

### ISSUE THREAD

**Issue by theibrahimi** [SharePoint/sp-dev-solutions#349]
Hello,
I'm using search results with search box to retrieve items from a specific list.
the first scenario below work properly ( I have default results and when I type something in the search box I have also results):

My default query :
`Path:https://mytenant.sharepoint.com/sites/mysite/Lists/mylist/* ContentType:"Contact"`

My query model:
`{searchTerms} Path:https://mytenant.sharepoint.com/sites/mysite/Lists/mylist/* ContentType:"Contact" 
`
But once I'm try to target a specific field in my query template like title making change only in the query model I have results when I search an item by title but my default results disappear  (scenario below) :

My default query :
`Path:https://mytenant.sharepoint.com/sites/mysite/Lists/mylist/* ContentType:"Contact"`

My query model:
`{searchTerms} Path:https://mytenant.sharepoint.com/sites/mysite/Lists/mylist/* ContentType:"Contact" Title:{SearchBoxQuery}
`
Any help please ?
#### Category
- [X] Question
- [X] Bug
- [x] Enhancement

Regards

#### Observed Behavior

> _If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

#### Steps to Reproduce

> _If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

#### Submission Guidelines

> - All suggestions or bugs are welcome, please let us know what's on your mind.
> - If you are reporting an issue around any of the samples, please ensure that you have clear reference on the sample and possibly code file, which should be fixed.
> - If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and #spfx-tooling on (SharePoint StackExchange)> [http://sharepoint.stackexchange.com/]. You can also alternatively submit your question to (SharePoint Developer group)> [https://network.office.com/t5/SharePoint-Developer/bd-p/SharePointDev] at Office Network.
> - Remember to include sufficient details and context.
> - If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

Thanks for your contribution! Sharing is caring.

**Comment by FranckyC** [comment]
Hi @theibrahimi. You don't need to duplicate your query in both default query and query template.

You can try `*` as default query. This will will your `{searchTerms}` in your query template. Then use `{searchTerms}` instead of `{SearchBoxQuery}` in your template:

```
{searchTerms} Path:https://mytenant.sharepoint.com/sites/mysite/Lists/mylist/* ContentType:"Contact" Title:{searchTerms} 
```

**Comment by theibrahimi** [comment]
Hi @FranckyC . Thanks it work very well
