### ISSUE TITLE
react-search-refiners: TemplateService - missing results layouts

### ISSUE THREAD

**Issue by lrolseth** [SharePoint/sp-dev-solutions#352]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

Hi All,

The [Templating documentation](https://microsoft-search.github.io/pnp-modern-search/search-parts/templating/) says that by default the search results Web part comes with multiple layouts.  However, when I deploy the package, I can only see the Results Layouts of "List", "Tiles", "Custom".

I can even see in the code that under src --> services --> TemplateService that there are several other components such as DocumentCardComponent and DetailsListComponent.  

Why I can't see all of these other renderers in my property pane when I add the search results Web part?

Thanks~

**Comment by wobba** [comment]
List, detailed list, card, carousel, people and custom should all be available to choose from. Never had an issue with this so unsure what you are seeing after installing it.
