### ISSUE TITLE
Clear Filter Search Refiner Icon Not Loading

### ISSUE THREAD

**Issue by j3rowan** [SharePoint/sp-dev-solutions#354]
#353 ## Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

The clear filters icon loads and displays correctly after filtering results.

#### Observed Behavior

An unknown character is shown instead (shown by [] character).

#### Steps to Reproduce

Add a search box part, filter part, and results part to a page.  Search for something and then filter on an available filter.

#### Possible Solution
Note: other icons may be impacted if they use the old ms-Icon ms-Icon--[IconName] way of loading fabric icons.

In spfx\src\webparts\searchRefiners\components\Layouts\LinkPanel\LinkPanel.tsx

Add the following to imports:
import { getIconClassName } from '@uifabric/styling';

Replace line 61 with:
                    <i className={getIconClassName('ClearFilter')} onClick={() => {

**Comment by ashiqf** [comment]
Icons on the Paging webpart does not work either. None of the icons on the Refiner filter webpart works, this has be fixed as early as possible.

**Comment by ashiqf** [comment]
I see the Up/Down arrows, seems there was an update. You can ignore my last message. Thanks
