### ISSUE TITLE
Does not work for SharePoint 2019 On Premises 

### ISSUE THREAD

**Issue by billfredtom** [SharePoint/sp-dev-solutions#355]
#### Category
- [x] Question
- [ ] Bug
- [x] Enhancement

#### Expected or Desired Behavior

Attempting to install the search web parts in SharePoint 2019 On Premises does not work due to the SPFx version difference (1.4.1 in on prem, 1.8.2 here at the time of writing). Are you able to advise if it's possible and if so, what steps are necessary to get it working?

**Comment by wobba** [comment]
We have a build for 2019 at the August release - https://github.com/SharePoint/sp-dev-solutions/releases/tag/ms-2019-08-14

It's not identical to the latest online release, but a snapshot in time which works provided by @appieschot .

The features we use to connect web parts today, using dynamic data, is not available for on-prem or older SPFx versions.

**Comment by limcysam** [comment]
I deployed the .spkg package successfully to the SharePoint 2019 app catalog site, but I get a error when adding it to the site collection. 

![image](https://user-images.githubusercontent.com/42954663/69194246-c3613780-0b7c-11ea-9e77-41b49664f630.png)

Are you able to advise what could I be doing wrong?

**Comment by wobba** [comment]
You need to deploy the 2019 package. If it's failing check the event log.

**Comment by limcysam** [comment]
I have deployed the 2019 package. When I check the log I see the below error:

![image](https://user-images.githubusercontent.com/42954663/69196013-5f8d3d80-0b81-11ea-98b4-d27e481aec89.png)

**Comment by wobba** [comment]
@limcysam are you able to deploy other 2019 SPFx packages?

**Comment by limcysam** [comment]
@wobba I was able to successfully deploy the 2019 package and add the app to the site. However, I do not see the option to add a search box but just search results webpart with refiners. I am not sure if I am missing anything. Can you please advise? 

![image](https://user-images.githubusercontent.com/42954663/69776564-e761f000-11f0-11ea-9556-e2914f96689a.png)

**Comment by wobba** [comment]
The 2019 version does not have a search box web part. It's based off an early version of the current online parts.

**Comment by Zanaqi** [comment]
> We have a build for 2019 at the August release - https://github.com/SharePoint/sp-dev-solutions/releases/tag/ms-2019-08-14
> 
> It's not identical to the latest online release, but a snapshot in time which works provided by @appieschot .
> 
> The features we use to connect web parts today, using dynamic data, is not available for on-prem or older SPFx versions.

hi, can we get the source code for this release?

**Comment by appieschot** [comment]
@Zanaqi The build is done against this repo: https://github.com/appieschot/sp-dev-solutions feel free to clone it or let me know what could be improved :)

**Comment by Matej4386** [comment]
@appieschot please, i was looking at the source code in that repo and it does not seems to be targeted at on-prem 2019, it looks different than the result in package. Could you please point me on the source code used for on-prem 2019 version?

**Comment by appieschot** [comment]
Hmm looks like I have a done a rebase and lost the feature branche.. Will check if i I can find it somewhere else.

**Comment by Matej4386** [comment]
@appieschot och, fingers crossed, it would save me a looooot of time

**Comment by appieschot** [comment]
@Matej4386 real sorry but can't seem to find the old version. I am more than happy to carve out some time to get a new version out there, but that will take me one or two weeks.

**Comment by Matej4386** [comment]
@appieschot don't worry ;-) I have already made a SP2019 on-prem version of modern search with searchbox, results, refinements. I thought it would more be time consumming. :-) Just making small improvements for templates (OUIFR 5 :-() and some small changes because of React 15...

**Comment by Zanaqi** [comment]
@Matej4386 Hi, could you kindly share the repo for this? Been trying to find a way to get it to work...

**Comment by Matej4386** [comment]
@Zanaqi Hi, of course, here is the link - https://github.com/Matej4386/SP2019-search . Please be aware - it is initial version :-) I am still working on it, testing, ...

**Comment by subgressive** [comment]
@appieschot Have you been able to "carve out some time to get a new version" , i am a SPFx newb and not able to get @Matej4386 one running. Happy to admit that the problem is no doubt my ability and dev setup.

As SP2019 is being run up a lot now these PnP Search web-parts , even unconnected , are becoming crucial. Thanks for any help.

**Comment by David74000** [comment]
Hello,
@Matej4386 thank you very much for this release ! I was searching for a way to use the modern search webpart in SP 2019. You saved me a lot of work to developp a webpart that already exists for SP Online.
All the best
David

**Comment by wobba** [comment]
@Matej4386 do you want a branch or repo on the pnp modern search site and provide releases?

**Comment by David74000** [comment]
I was wondering what is the purpose of the modern_search_**results** ? It seems it's an application customizer but I cannot figure out how to make it work with the modern_search webpart ?
Thank you for your help

**Comment by Matej4386** [comment]
> I was wondering what is the purpose of the modern_search_**results** ? It seems it's an application customizer but I cannot figure out how to make it work with the modern_search webpart ?
> Thank you for your help

Hi, please be more specific. I made a new version, hopefully tomorrow i will manage to upload it github. It has many bug fixes, carousel support ... 

Solution has 1 webpart made on results webpart. Other parts like search box, filters are under the results webpart.

**Comment by Matej4386** [comment]
> @Matej4386 do you want a branch or repo on the pnp modern search site and provide releases?

Hmm i have no idea - if you want i have no problem but be aware - some obstacles to make it work on react 15, ouifr 5 ... are not very nice 🤗

**Comment by David74000** [comment]
Hi Matej,
in the solution I have downloaded, there were 2 folder:
- modern_search
- modern_search_results

I finaly figured it out : the **modern_search** is indeed the main webpart. The **modern_search_results** folder contains a spfx extension that use CustomEvent (eventlistener) to communicate with the modern_search webpart.

@Matej4386 : if you have a more recent solution, I would be more than happy to test it. Again, thank you for your work and help.
David

**Comment by Matej4386** [comment]
@David74000 yes i have it but it is quite difficult to upload it on github from my network ... bunch of protection but as i wrote i will do my best to upload it tomorrow... 

The most recent version is build from more recent original version - i have made it again from scratch...

**Comment by mikedockray** [comment]
@Matej4386 @David74000 i would still be keen to give this another crack if u can upload a newer version. Am i correct in thinking that as SP2019 uses such an old version of SPFx that u cannot have two web-parts on the one page. ie. a search box and a search results web-part on the same page. Also that search results cannot be configured to take the search term from the url, or have you gotten around this limitation somehow ?

**Comment by Matej4386** [comment]
@wobba @David74000 @mikedockray 
Hello all,
here you can find a new version of Search web part based on this great project but for Sharepoint 2019 on premise
https://github.com/Matej4386/SP2019-search/ 

I think it is based on version pnp-modern-search-3.13.0 - i made it from scratch (so it is not update from previouse release)

@mikedockray yes SP2019 uses - framework 1.4. and react 15 and ouifr 5. 
You can have as much webparts on one page as you want but they cant communicate with each other - you cant use Dynamics connectors because of version of framework on SP2019.

So i made 1 webpart with Search results, Searchbox, pagination and filters - main webpart is search results webpart so you cant turn it of (serach box, refiners and pagination can be turned off).

Hmm search term from url - to be exact i did not test it, but i tried to take everything from original solution and just delete/modified as little as possible.

**Comment by David74000** [comment]
Hi @Matej4386,
thank you again very much for this release !
I have a small question, did you manage to display a refiner with the Container Tree template ? Do you know what kind of managed property should the container tree works with ?
David

**Comment by FranckyC** [comment]
Hi @David74000 , maybe this could help: https://web.archive.org/web/20201014031829/https://microsoft-search.github.io/pnp-modern-search/search-parts/search-filters/#container-tree.

You must use the `ParentLink` managed property.

**Comment by David74000** [comment]
Thank you @FranckyC ,is this template supposed to work with taxonomy property ? in other words having a hierarchical refiner to display taxonomy parent term at first level, then child term at level below, and so on... .

**Comment by FranckyC** [comment]
Not designed to work with taxonomy but only with URLs. The main purpose of this template is to give you a way to filter by folders hierarchy using SharePoint search, just like a regular library. This is useful, for instance, if your organization doesn't take advantage of taxonomy and when folders are, basically, your only available metadata to leverage. If you already use taxonomy, you probably don't need this.

**Comment by David74000** [comment]
Ok I understand. I am trying to display the refiner in a similar way than this : https://social.technet.microsoft.com/Forums/getfile/1016077 but for modern.
I will try to create a new refiner template to achieve that, by using term and term set GUID... 
Will let you know if I find something, do not hesitate if you have some advices :)
David

**Comment by FranckyC** [comment]
@David74000 I already did this for an other solution and what I could say, is this is not so easy to implement. You must distinguish static filters vs refiners (you can see this as reference https://bit.ly/36LaOdS). Building a logic to extract a hiearchy from taxonomy guids could be very tricky. The current PnP Modern Search code is not so flexible to integrate this kind of change.

**Comment by David74000** [comment]
@FranckyC
I have managed to add a Taxonomy refiner template in the modern search webpart that @Matej4386 provided.
It works on an older version of modern search webpart but I guess refiners logic is more or less the same.
Do you think we can integrate this template in the new modern search webpart ?
David

**Comment by FranckyC** [comment]
@David74000 Filters implementation between v3 and v4 is totally different. In v4, filters has to be implemented via web components. In the case of a taxonomy picker, the state management can be very tricky. However, you can try but you couldn't migrate your code as is.

**Comment by Hussain-maker** [comment]
> @FranckyC
> I have managed to add a Taxonomy refiner template in the modern search webpart that @Matej4386 provided.
> It works on an older version of modern search webpart but I guess refiners logic is more or less the same.
> Do you think we can integrate this template in the new modern search webpart ?
> David

Hi @David74000 ,

Could you share the version you have modified of @Matej4386? Or another branch on his project would be good

Would be really useful for everyone who's looking for an on prem solution for the modern search

**Comment by David74000** [comment]
Hi @Hussain-maker ,
I need to clean the code a little bit before publishing the solution. Will do it next week.
@Matej4386 : Can I send you my source code and you will integrate it to the solution you shared with me ?
Cheers
David

**Comment by Matej4386** [comment]
@David74000 Hello, that would be great, but I have a lot of work so I am not sure when it would be integrated.

**Comment by David74000** [comment]
Hi all, I will shortly publish a version of SP2019 modern search webpart based on @Matej4386 solution. This version is the same than Matej shared with me, with just an additionnal Taxonomy refiner. I will finish cleaning it for next week and push it to a new repo.
See you soon. 
David

**Comment by David74000** [comment]
Hi all, please find the solution that @Matej4386 shared with me. I added additionnal taxonomy refiner template. The two main files are TaxonomyTemplate.tsx and TermTreeView.tsx. I used pnp treeview component to display taxonomy refiners in a hierarchical way.
I hope you will enjoy :
https://github.com/David74000/SP2019-modern-search-webpart-with-taxonomy-refiner.

@Matej4386 Thank you again for sharing with me the modern search webpart for sp2019, it save me a lot a time !
@FranckyC please let me know if you want to add this template to the modern search webpart
