### ISSUE TITLE
User Profile SPS-Skills only Showing 1 item

### ISSUE THREAD

**Issue by westerdaled** [SharePoint/sp-dev-solutions#356]
#### Category
- [X] Question
- [ ] Bug
- [ ] Enhancement

#### Observed Behavior

Not sure if this a bug or not.  I want to show content that is tagged with my user profile skills on our test tenant. 

First, I set up some test skills - not all apply to me!

![User profile skills](https://user-images.githubusercontent.com/937208/69242798-8f483f80-0b99-11ea-8341-040f305dca6b.png)

I create a document library with a Skills choice field and Enterprise Key words.  Wasn't sure which one of these would be the most useful to the search crawler

![Skills documents](https://user-images.githubusercontent.com/937208/69243063-21504800-0b9a-11ea-8064-145e12726a23.PNG)

Drag my Search Results on the page and configure 
![Search Results Skills](https://user-images.githubusercontent.com/937208/69243279-a6d3f800-0b9a-11ea-889d-76c301b6eb12.png)

Looks like I am a one trick pony 😪! I should be seeing both documents.   

#### Steps to Reproduce
As above

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by wobba** [comment]
From your screenshot you query for items on the path:

https://contoso.sharepoint.com/sites/somesite **skill** 

It's very unlikely this is a valid path. You need to target skills for a managed property containing the skills value, not using path. This is basic KQL and outside the scope of the web part itself.

Take a look at https://www.techmikael.com/2014/03/s15e01-kql-basics.html and read up on how KQL works :) or see the official documentation.

**Comment by westerdaled** [comment]
OK I see what you are getting at. I had previously used a path to doc centre (instead of a result source) alongside page property value and got the desired results. However, you are right I need a better understanding of KQL. Thanks for the advice.

**Comment by westerdaled** [comment]
@wobba  Actually there is more to this than I first thought

I could change the query to 
```
{searchTerms}  
{?{|RefinableString103:Office 365}}

```
And happily bring back docs tagged with the Enterprise Keyword Office 365 

I can't use 
```
{searchTerms}  
{?{|RefinableString103:{SPS-Skills}}

```
So looking through the your links and a bit of Googling .   I think I need to create a term set, say 
User Skills and then use that term set:  mapped to the user profile Skills property and  in a metadata column, in my doc library.

Now this should work when searching for multiple skills values -  got to do a demo to our stake holders this afternoon,  so won't be able to test this out until afterwards:
`[{?{|owstaxUserSkills:{User.SPS-Skills}}}](url)`

Does this sound feasible ?
