### ISSUE TITLE
react-search-refiners: V3.7 Search results webpart disappeared in full page refresh 

### ISSUE THREAD

**Issue by mahmoudhamed** [SharePoint/sp-dev-solutions#357]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
When you refresh the page the webpart should load normally. 

#### Observed Behavior

If your just refresh the webpart is not loading just render white square but if you hit control+F5 the webpart get loaded okay. 

#### Steps to Reproduce

just refresh the page

![Issue 1](https://user-images.githubusercontent.com/7877441/69258574-1c50c000-0bbd-11ea-815b-0fcbae61f918.png)
![Issue 2](https://user-images.githubusercontent.com/7877441/69258593-21ae0a80-0bbd-11ea-99c8-0c2792e0b5ef.png)

**Comment by wobba** [comment]
Which layout are you using? Is it tied to a searchbox?

**Comment by wobba** [comment]
I created a new issue for this at the new repo, and I see this for the card view layout - but don't get the error.
