### ISSUE TITLE
How to add a link to people layout?

### ISSUE THREAD

**Issue by kongmengfei** [SharePoint/sp-dev-solutions#358]
## Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

Hello,

I add a search result web part on my SPO page like below:
![search - Google Chrome](https://user-images.githubusercontent.com/57654821/69607390-20b72600-1060-11ea-93e2-a26b031c9524.jpg)
However the people item is not clickable. Is that possible to add a link of people.aspx?  if i use other layouts, the item is clickable. I tried following methods but failed:
![search - Google Chrome](https://user-images.githubusercontent.com/57654821/69607635-991de700-1060-11ea-93ce-473ff44fbe8a.jpg)

Can someone help me?

**Comment by wobba** [comment]
Two options. We change the default people experince. Two, click the "custom" button and add a hyperlink in the overall template around the people rendering.

You can not do it in the UI per field.

**Comment by kongmengfei** [comment]
> Two options. We change the default people experience. Two, click the "custom" button and add a hyperlink in the overall template around the people rendering.
> 
> You can not do it in the UI per field.

Hi Wobba,
Where should i add the <a> ?   i tried the following but nothing changed: 

![search - Google Chrome](https://user-images.githubusercontent.com/57654821/69612967-b3a98d80-106b-11ea-8855-e55011afe521.jpg)

i cannot find any reference about <personal-card>, do not know how to add this link. 

Can you help more?

Thanks

**Comment by kongmengfei** [comment]
> Two options. We change the default people experience. Two, click the "custom" button and add a hyperlink in the overall template around the people rendering.
> 
> You can not do it in the UI per field.

Hi Wobba,
i have got it work. althought its style is not so good. but it work now.  
Thanks

**Comment by marting1010** [comment]
> > Two options. We change the default people experience. Two, click the "custom" button and add a hyperlink in the overall template around the people rendering.
> > You can not do it in the UI per field.
> 
> Hi Wobba,
> i have got it work. althought its style is not so good. but it work now.
> Thanks

hi there @kongmengfei  how did you get this to work in the end please? I want to do the same as a stop-gap measure until the enhancement is in place. I tried ` <a href="{{OriginalPath}}">{{Title}}</a>` but it didn't do  anything.
