### ISSUE TITLE
Show file icon option is ignored in tile layout

### ISSUE THREAD

**Issue by stevebeauge** [SharePoint/sp-dev-solutions#359]
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

When choosing Tiles template in the SearchResultWebPart, the file icon shouldn't render when Show file icon isn't checked.

#### Observed Behavior

When choosing Tiles template in the SearchResultWebPart, the Show file icon option is ignored.

#### Steps to Reproduce

1. Drop a Search Result Web part in a modern page. Set its query to `IsDocument=true`. 
2. Choose the Tile layout. 
3. Uncheck the Show file icon option

The icon is still rendered.

**Comment by wobba** [comment]
Can you re-file this issue at https://github.com/microsoft-search/pnp-modern-search

**Comment by stevebeauge** [comment]
Certainly. I missed the fact that the project moved. I'll repost. Thx

**Comment by stevebeauge** [comment]
Maybe you should state that in the readme of the modern search folder ?

**Comment by wobba** [comment]
@stevebeauge done :) completely forgot
