### ISSUE TITLE
PDF Preview is broken in tiles layout

### ISSUE THREAD

**Issue by stevebeauge** [SharePoint/sp-dev-solutions#361]
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

When preview is enabled, clicking on a pdf file should display its preview

#### Observed Behavior

When clicking on the tile, an error appears in a dialog:

![image](https://user-images.githubusercontent.com/184604/69721014-3554f600-1114-11ea-8776-ff8d73e6a0be.png)

#### Steps to Reproduce

1. Add a search result web part in a page. 
2. Set its query to `FileType:pdf` (ensure there are some pdf indexed)
3. Save the page and click on a tile.
4. The error appears

**Comment by stevebeauge** [comment]
Analysis: the handlebar template for the previewUrl field of the card is this one (indented for readability) :

````
{{#eq contentclass 'STS_ListItem_851'}}
{{{DefaultEncodingURL}}}
{{else}}{{#eq FileType 'pdf'}}
<!-- Documents from OneDrive sites can't be viewed directly due to SAMEORIGIN iframe restrictions-->
{{#contains Path '-my.sharepoint'}}
{{{ServerRedirectedEmbedURL}}}
{{else}}
{{{Path}}}
{{/contains}}
{{else}}
{{{ServerRedirectedEmbedURL}}}
{{/eq}}
{{/eq}}
````

The problem is that this template is used to render the value of an html attribute (dialog url), not an Html fragment. Thus, the `<!-- Documents from OneDrive .... -->` is actually included in the url :

    <iframe src="https://mytenant.sharepoint.com/sites/mysite/somelib/somefile.pdf" allowfullscreen="" frameborder="0"></iframe>

**Comment by stevebeauge** [comment]
Diving a bit more, I don't get the point of handling files from https://mytenant-my.sharepoint.com....

In my tenant, if I replace the handlebars template or the preview url field by simply ServerRedirectedEmbedURL property, everything works fine (both for results from team sites and onedrive).

Of maybe the SAMEORIGIN issue related is no more applicable ? and if yes, the webpart should revert to a simple property bind

**Comment by stevebeauge** [comment]
nevermind, I see the behavior with Chrome... I tested initially with Firefox. There is actually an issue

**Comment by wobba** [comment]
Can you refile this at https://github.com/microsoft-search/pnp-modern-search
