### ISSUE TITLE
Managed metadata refiners question

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-solutions#362]
When creating a managed metadata column refiners in search schema, should I map with ows_taxid_column or ows_column to refinablestring

Is there any difference?

**Comment by wobba** [comment]
There is a difference and use ows_taxid_column. This is mentioned in the templatating docs, but we should add it to the refiner docs as well. ows_taxid_column  includes the term id for one, which is needed to look up the term and do translation. ows_column only has whatever is set for the column to display, typically the label.

**Comment by harshdamaniahd** [comment]
@wobba   thanks..so this basically means that binding ows_taxid_column to refinablestring is helpfull if the term is 
1. Multilingual
2. Has synonyms

**Comment by wobba** [comment]
Multi-lingual. We're not using the alternate labels afaik.
