### ISSUE TITLE
Question of Search result webpart- Need to show the result from SC from where search query initiated

### ISSUE THREAD

**Issue by pradejain** [SharePoint/sp-dev-solutions#366]
#### Category
- [X] Question
- [ ] Bug
- [] Enhancement
@FranckyC @wobba @taraldga 
First of all, thank you for developing the amazing web part.

**I have a question on web part configuration-**

In my current environment, I have multiple modern site collections. I have set up a SharePoint search page using the modern search web parts in the root site collection and added a search box web part on other site collections home page. from the SC home page search box, I am redirecting to the Seach page and passing the query parameters. This current configuration is working fine but the issue is with the search result. I am only getting the search result from the site collection where my search page is located not from the site collection from where query initiated. I would like to show the search result from the site collection from where query initiated. 
Scenario
Site collection 1 - This has a search page
Site collection 2 - this has a search box on the home page
Site collection 3 - this has a search box on the home page

**Current behavior-** 
If I am searching from site collection 2, I am getting the result back from site collection 1. The same is happening with site collection 3.
**Expected behavior-** 
If I do search from site collection 2, I want the result back from site collection 2.

Maybe this is something simple fix that I am missing here. I would really appreciate it if someone can provide the guideline to implement my requirement using this web part.

Thanks in advance.

**Comment by wobba** [comment]
To understand properly. You have one search result page sc. And you have multiple other sc's. When searching on them, you want to redirect to the search result sc, and limit results to the sc from which you queried? Much like the `u=` param in classic search web.

You probably have `path:{site}` in the query template of the sc's in the web part config. If you want results from one specific sc, when page is on another, you need to send over the sc path from where you originated as a param, to be used in the query template on the result page sc. Don't think we really support this scenario.

If you configure the search box url to be `https://server/sites/searchsc/sitepages/results.aspx?u=https://server/sites/siteA` and on the result sc you have this as your query template `{searchTerms} path:{QueryString.u}` I think that should solve your case.

And please log issues over at https://github.com/microsoft-search/pnp-modern-search, which is the new repo :)

**Comment by pradejain** [comment]
Thank you for the quick response and the solution. I will try this solution
and let you know. The only issue I am seeing with this solution is to pass
the SC full URL.

Thanks,

+

**Comment by wobba** [comment]
You can hard code it...which works unless you have tons of sc's. Or log it as a feature request.

**Comment by pradejain** [comment]
Hi Mikael,

We have been using the modern search web part for 6 months without any
issues. Two days back, suddenly this web part stops working and not showing
up any result and search result web part.  I found only below error when I
debug the code. This App is very critical for our organization, immediate
help would be really appreciated.


[image: image.png]


   1. Request URL:

      https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-type=application%2Fbond-compact-binary&client-id=NO_AUTH&sdk-version=AWT-Web-JS-1.8.0&x-apikey=a387cfcf60114a43a7699f9fbb49289e-9bceb9fe-1c06-460f-96c5-6a0b247358bc-7238&client-time-epoch-millis=1593701274023&time-delta-to-apply-millis=33139
      2. Request Method:
      POST
      3. Status Code:
      403 All records were throttled.
      4. Remote Address:
      40.122.160.14:443
      5. Referrer Policy:
      no-referrer-when-downgrade
      1. Response Headersview source
      1. Access-Control-Allow-Headers:
      Accept, Content-Type, Content-Encoding, Client-Id
      2. Access-Control-Allow-Methods:
      POST
      3. Access-Control-Allow-Origin:
      *
      4. Access-Control-Expose-Headers:
      kill-tokens, kill-duration-seconds, time-delta-millis
      5. Collector-Error:
      All records were throttled.
      6. Connection:
      close
      7. Content-Length:
      0
      8. Date:
      Thu, 02 Jul 2020 14:48:26 GMT
      9. Server:
      Microsoft-HTTPAPI/2.0


Thanks,
Pradeep

>

**Comment by wobba** [comment]
See #325 and don't comment on old closed issues.

**Comment by FranckyC** [comment]
@pradejain Wrong repo, see https://github.com/microsoft-search/pnp-modern-search/issues/325 issue.

**Comment by pradejain** [comment]
Hi Mikael,

Thank you for the quick response. Really appreciate it. but I can't relate
my issue with  #325 <https://github.com/pnp/sp-dev-solutions/issues/325>.

Thanks,
Pradeep

**Comment by pradejain** [comment]
Thank you, Franck. In my case, I am not using a search query string. Even
page with Search box and Search result web part not showing up any result.

Thanks,
Pradeep

**Comment by wobba** [comment]
Please log a new issue on the right repo with repro steps.
