### ISSUE TITLE
Modern search: Web part results differ from query builder results

### ISSUE THREAD

**Issue by webbrewer** [SharePoint/sp-dev-solutions#367]
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Create a results source limited to a document library, only see results from that library

#### Observed Behavior
In the query builder the results look correct but the results web part returns results from completely different sources

#### Steps to Reproduce

- Create results source
{searchboxquery} path:"https://xxx.sharepoint.com/sites/xxx/Shared%20Documents/*"
Or
{searchTerms} path:"https://xxx.sharepoint.com/sites/xxx/Shared%20Documents/*"

- Enter results source GUID in results sources identifier box in web part properties

.

**Comment by webbrewer** [comment]
Just noticed I'd left sitecollection in the query template which was strangely overriding the results source configuration...

**Comment by webbrewer** [comment]
Reopening because when I enter a 2nd search I'm still getting random results  - all seem to be coming from geolocation site collections **definitely not included** in the results source configuration.

**Comment by FranckyC** [comment]
Hi @webbrewer. Do you use the latest version from the new repository https://github.com/microsoft-search/pnp-modern-search? This one is deprecated.

**Comment by webbrewer** [comment]
Thanks @FranckyC  I'll give it a try ....

**Comment by webbrewer** [comment]
@FranckyC  I added the latest version but am still seeing the same issue. The test results in the results source query builder are correct, but when I add the results source guid to the search results web part, they are not. 
One odd thing I notice is the results include documents in geolocation site collections - eg <tenantname>**eur**.sharepoint.com or <tenantname>**gbr**.sharepoint.com

**Comment by webbrewer** [comment]
Tested the same configuration using classic content search web parts and it works perfectly so there's something wrong with the solution or my tenant.

**Comment by webbrewer** [comment]
I removed a space in the library's url and added Path: library url to the query template and that seems to have resolved it.
Closing this....

**Comment by wobba** [comment]
@webbrewer do you have any more information as you re-opened the issue? Does it work as expected if you edit the query template directly instead of using a result source id? And the result source is defined globally or at the same sc which you are using the web part?

**Comment by webbrewer** [comment]
The results source alone _definitely_ doesn't work  - though it does in the query builder so I assume it's configured correctly. I have to add the path variable to the query template to limit results to a specific library.
The results source was defined in the site collection but also appears at the tenant level (?). Neither guid limits the search results.

**Comment by wobba** [comment]
I cannot reproduce the error with either 3.7 or 3.8. Created a result source with the template ` {searchTerms} (FileExtension:docx OR FileExtension:pdf) path:https://contoso.sharepoint.com/sites/TestTeam`. Added a search wp, set query to `*`, query template to `{searchTerms}` (or empty) and result source identifier to the guid of the sc result source. Results are as expected.

If you use dev tools and look at the _api/search/postquery calls, you can check the response and look for `QueryModification` and see what the final query looks like.
