### ISSUE TITLE
I could not run the site script for flows-formatters-pages-siteScripts

### ISSUE THREAD

**Issue by muges01** [SharePoint/sp-dev-solutions#37]
Hi everyone,

I try to create a team site using the provided site script 'UberSiteDesign.json' but the site script stuck on the initialising. I awaited for few minutes and it is still stick on that screen. 

![site-script-error](https://user-images.githubusercontent.com/22563887/46344023-a8a9c780-c637-11e8-9da5-0fe905e45cdf.png)

#### Category
- [ ] Question
- [x ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Expected to see the site script run successfully. 

#### Observed Behavior
I have done some testing and and i found out that if i remove some of the lines in the scripts than it successfully created. I have tested by removing some chuck from different sections. This shows that the site script has some line, or character or size limits. Can some one clarify on this?

#### Steps to Reproduce
1. Get the 'UberSiteDesign.json' from https://github.com/SharePoint/sp-dev-solutions/tree/master/solutions/flows-formatters-pages-siteScripts/site-designs.
2. $siteScript = Get-Content '[[pathToYourSiteScriptJsonFile]]' -Raw
3. $mySiteScript = Add-SPOSiteScript -Title "Classroom Site Script" -Description "Classroom Site Script" -Content $siteScript
4. Add-SPOSiteDesign -Title "Classroom site designs" -WebTemplate "64" -SiteScripts $mySiteScript -Description "classroom site design"

I hope someone could guide me on this issue.

Thank you in advanced.

**Comment by vivsunny10** [comment]
I am also facing same error. Any updates?

**Comment by muges01** [comment]
No, i didn't get any updates. Please post your comments on this https://github.com/SharePoint/sp-dev-docs/issues/2695 as well.

**Comment by muges01** [comment]
hi @vivsunny10  did find any solution?

**Comment by vivsunny10** [comment]
Hi @muges01 ,

Issue is   site scripts are limited to 30 cumulative actions (across one or more scripts that may be called in a site design. Please refer following issue:-https://github.com/SharePoint/sp-dev-docs/issues/2205

I belive we will have to wait for Microsoft to update the limit before we can use the UberSiteScript.json since in Ignite they might have shown a preview feature which is not yet released.

**Comment by muges01** [comment]
Thank you @vivsunny10. I guess we just have to wait.
