### ISSUE TITLE
Search web part doesn't transform space

### ISSUE THREAD

**Issue by dennishaxe** [SharePoint/sp-dev-solutions#371]
Hi, 

I have the search web part on a empty page and it sends the input to the standard SharePoint result page.

https://********/_layouts/15/search.aspx/siteall?q=

When I search 'Test Test' for example then the result url is https://********/_layouts/15/search.aspx/siteall?q=Test%2520Test

The result of this search is nothing can be found for test%20test

What am I doning wrong?

**Comment by wobba** [comment]
Seems like a double encoded issue. Could you please log the bug at https://github.com/microsoft-search/pnp-modern-search if still present in the latest version.
