### ISSUE TITLE
Source code for pnp-react-search-refiners-sp2019.sppkg

### ISSUE THREAD

**Issue by Matej4386** [SharePoint/sp-dev-solutions#373]
#### Category
- [X] Question
- [ ] Bug
- [] Enhancement

#### Expected or Desired Behavior
Could you please provide source code for pnp-react-search-refiners-sp2019.sppkg? I would really appreciate it ;-)

#### Observed Behavior
@appieschot pointed in #355 here https://github.com/appieschot/sp-dev-solutions but i cant see any difference from online solution :-(

Thank you in advance.

**Comment by wobba** [comment]
Answered in #355
