### ISSUE TITLE
Search Results Web Part: Error making HttpClient request in queryable [500] ::> {"odata.error":{"code":"-1, Microsoft.Office.Server.Search.REST.SearchServiceException","message":{"lang":"en-US","value":"An unknown error occurred."}}}

### ISSUE THREAD

**Issue by yakubmohd** [SharePoint/sp-dev-solutions#376]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Search results in the last page should be displayed when clicked on the >> in search pagination.

#### Observed Behavior

After configuring and connecting search box and search results web part, When I search for a query in search box, I can see 587726 results and the results are loading in the search results web part. But when I click on the >> in the search pagination to go the last page of search results, after few seconds I can see a red box stating the following,

![image](https://user-images.githubusercontent.com/56990277/75133944-a9e30500-5702-11ea-9f95-379fba29d4f3.png)

![image](https://user-images.githubusercontent.com/56990277/75133445-d7c74a00-5700-11ea-8fba-9075147933a5.png)

#### Steps to Reproduce

Configure and connect search box and search results web part and simply attempt a search query which returns large number of results. Search results will be displayed in the search results web part, now click on >> in the search pagination to go to the last page. After few seconds above error will be displayed.

**Comment by wobba** [comment]
Can you re-test with latest version v3.9 and re-log the issue at https://github.com/microsoft-search/pnp-modern-search if still a problem, as that is where active development is happening.
