### ISSUE TITLE
Search result web part is appending a .url extension to web links causing the link to be downloaded by the browser rather than opening the document when the link is clicked

### ISSUE THREAD

**Issue by bkwaz4** [SharePoint/sp-dev-solutions#377]
#### Category
- [ ] Question
- [x] Bug
- [] Enhancement

#### Expected or Desired Behavior
The url contained in a web link should have the link action mapped to the url field contained in the web link, not the name of the web link with a .url appended onto the end by default.
This prevents the users from creating multiple links to the same source doc but with different names that work in the modern search web part.  These links are always downloaded by the browser and you cannot open them.

#### Observed Behavior
Web link to a document named My web link.pdf that has URL="https://contoso.sharepoint.com/Shared Documents/sourcedoc.pdf"
will have a link named My web link.pdf in a search result with an action of https://contoso.sharepoint.com/My web link.pdf.url"
Clicking on this link downloads the link and the link cannot be opened because it is invalid.

#### Steps to Reproduce
(Optional) turn on the Document ID service and create links using the document IDs rather than the absolute urls so you can move the source documents around without affecting the links.
Configure the search result web part to display a document library.
Create a different document library for the source documents
Create a document called My web link.pdf in the source document library
Create a web link that uses the url https://contoso.sharepoint.com/sourcelib/My web link.pdf named My web link.pdf
Copy the web link to the target document library
Rename the target library web link to 01 My web link to remove the extension and facilitate sorting
Search for the link using the modern search web part
Click on the search result for the link which will be named 01 My web link
Link is downloaded
Link cannot be opened.

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by wobba** [comment]
If this is still an issue with the latest version v3.9, log the issue at https://github.com/microsoft-search/pnp-modern-search (where you can also find the latest release).
