### ISSUE TITLE
Question: Search Results Webpart, Results Template: Additional css class for first item

### ISSUE THREAD

**Issue by MarcoSPDeveloper** [SharePoint/sp-dev-solutions#380]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

First thanks for this great solution. 

I have a question regarding the  **Search Results Webpart - Results Template**

Is there a way to to let the first result look different like the all the others. I just want to apply a additional css class to the first element in the result list.

Do you have an hint, with which {{ }} operator this can be archieved. Is there an index in the {{#each items as|item|}}?

Thanks for any help.
Marco

**Comment by wobba** [comment]
You can take a look at https://github.com/helpers/handlebars-helpers/blob/master/README.md#each index for example. Google handlebars or handlebars helpers and you should fine somethibgy🙂
