### ISSUE TITLE
Search box & Result not working after refresh the page

### ISSUE THREAD

**Issue by lam01007** [SharePoint/sp-dev-solutions#389]
### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Search Result properly show.

#### Observed Behavior

No any response & result show.

#### Steps to Reproduce

1. Add Search Box & Search Result web part;
2. Edit the properties of Search Result web part, and connect to the Search Box:
![image](https://user-images.githubusercontent.com/10590442/79414120-65763600-7fdc-11ea-99bb-747f4628e1ab.png)
3. Save it as draft or Publish the page.
4. Press F5 to refresh the page.
5. Enter search term in search box and click search icon or press "Enter"
6. No response, and without any error on console

The function is work fine on yesterday. and I had tracing on the network tab in F12 of Chrome, and compare with the 2 cases:

After Save as Draft:
![image](https://user-images.githubusercontent.com/10590442/79414334-ee8d6d00-7fdc-11ea-8fe0-8778f2ef9d69.png)

Before Save as Draft:
![image](https://user-images.githubusercontent.com/10590442/79414521-71aec300-7fdd-11ea-929d-cfb689981a2a.png)

There are missing the "postquery" call after save the page.

And I got the similar issue on site search, not sure the issue is related to SharePoint Online or not.
https://techcommunity.microsoft.com/t5/sharepoint/error-in-site-search/m-p/1311493#M40167 

any idea?

Many thanks

**Comment by wobba** [comment]
If this is related to pnp modern search, head over to https://github.com/microsoft-search/pnp-modern-search for the latest version and log the issue there if still present.

**Comment by lam01007** [comment]
Thanks for redirect
