### ISSUE TITLE
Unable to show correct Percent Complete in task list Donut view

### ISSUE THREAD

**Issue by Willerz707** [SharePoint/sp-dev-solutions#42]
- [X ] Question
- [ ] Bug
- [ ] Enhancement

I must be dense, but I can't make the donut show the correct percentages for the default percentage complete column in my Task list?
What am I doing wrong?

![capture2](https://user-images.githubusercontent.com/44778642/48304317-b66f2a00-e4cc-11e8-98c3-feb537dbaf4b.PNG)
![capture1](https://user-images.githubusercontent.com/44778642/48304318-b66f2a00-e4cc-11e8-9234-33f853c42062.PNG)

**Comment by thechriskent** [comment]
When a field is set to percent, the value is from 0 to 1. So, in the wizard set the Range as **Low: 0** and **High: 1**. Thanks!

**Comment by Willerz707** [comment]
I’ll try that. Thanks

Sincerely,
William Hardwick

HumWebit.com
Be first in search.
Office 365 consultant.
________________________________

**Comment by Willerz707** [comment]
Do you also know how to show a person’s profile picture for any task assigned to right now it’s only showing the user that’s using it?

Sincerely,
William Hardwick

HumWebit.com
Be first in search.
Office 365 consultant.

________________________________

**Comment by thechriskent** [comment]
You can show a profile picture for a user field using this sample (also included as a template in Column Formatter): https://github.com/SharePoint/sp-dev-list-formatting/tree/master/column-samples/person-roundimage-format

Perhaps I'm not understanding the issue? I'm not sure what you mean by only showing the user that's using it.

**Comment by Willerz707** [comment]
It only shows the person that is logged in the current user all the rest are just default profile pictures?

Sincerely,
William Hardwick

HumWebit.com
Be first in search.
Office 365 consultant.

________________________________

**Comment by thechriskent** [comment]
Hmmm... I just checked in my environment and I'm not having that issue.

What value is being used for the `src` attribute of the `img` element? I have `='/_layouts/15/userphoto.aspx?size=S&accountname=' + @currentField.email` working just fine.

**Comment by Willerz707** [comment]
Duh, I was using the user profile template not the round image template.
Thanks for all the quick replies. This web part is great!
