### ISSUE TITLE
Erros with SPHttp

### ISSUE THREAD

**Issue by dheepai** [SharePoint/sp-dev-solutions#52]
#### Category
- [ ] Bug

#### Expected or Desired Behavior
_If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit._

#### Observed Behavior
Getting the following error on gulp serve
Error - [tsc] src/services/NlpService/NlpService.ts(43,74): error TS2345: Argument of type 'HttpClientConfiguration' is not assignable to parameter of type 'HttpClientConfiguration'.
Error - [tsc] src/webparts/searchBox/SearchBoxWebPart.ts(123,45): error TS2345: Argument of type 'HttpClient' is not assignable to parameter of type 'HttpClient'.
Error - [tsc] src/webparts/searchResults/SearchResultsWebPart.ts(193,57): error TS2345: Argument of type 'SPHttpClient' is not assignable to parameter of type 'SPHttpClient'.
Error - [tsc] src/webparts/searchResults/SearchResultsWebPart.ts(534,79): error TS2345: Argument of type 'SPHttpClientConfiguration' is not assignable to parameter of type 'SPHttpClientConfiguration'.

#### Steps to Reproduce
Download the code, browse to the spfx folder, rup npm install and gulp serve

**Comment by FranckyC** [comment]
Hi @dheepai, can you tell me the node.js version you use?

**Comment by dheepai** [comment]
Upgrading node.js fixed the error. Thanks @FranckyC
