### ISSUE TITLE
Search Refiners with Term Store Values

### ISSUE THREAD

**Issue by kachihro** [SharePoint/sp-dev-solutions#61]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [X] Question
- [] Bug
- [X] Enhancement

#### Expected or Desired Behavior
When configuring a refiner from 'RefinableString02', for example - which - is a field from a TAXONOMY (termstore) field - the refiner display should show as ;

Finance (2)

#### Observed Behavior
Instead, it shows with the full GUID - for the field value ;
4;#Finance|919f07ce-89cd-456e-97da-073d99cb1863 (2)

** It works, and refines the results - but - the display value isn't pretty

#### Steps to Reproduce
1. Create site column - based on a termstore value
2. Add to SP Doc Lib
3. Include documents, and set properties
4. Set Search Schema - eg. RefinableString02 - and add the crawled property
5. WIthin webpart setting - include the field - as a refiner

**Comment by tdwhite0** [comment]
@kachihro This goes away if you click "Localization enabled" on page 2 of the config, I had this happening to me today.

**Comment by FranckyC** [comment]
@tdwhite0 @kachihro correct this is due to an update that I've made to mainly improve performances. Sorry for that :(

**Comment by FranckyC** [comment]
@kachihro Does it work for you?

**Comment by vui211** [comment]
Hi @FranckyC 
It doesn't work for us even with "localization enabled" set to yes in Search result web part. 
I'm not sure this is problem related to our taxonomy field or search refiners web part.

![image](https://user-images.githubusercontent.com/23225932/55039187-1b947800-5088-11e9-84c4-833cccb0a405.png)

**Comment by FranckyC** [comment]
@kachihro It seems the taxonomy format differs from the implemented regex (we use L0#| ...) so it explains why this value is not recognized. Is there anything special with this term? What language are you using?

**Comment by vui211** [comment]
@FranckyC  I think you asked me not kachihro. We use English only. Only special thing with this term is it reuses many terms from another term set 
![image](https://user-images.githubusercontent.com/23225932/55042435-500f3080-5096-11e9-8c0a-7b878c803653.png)

**Comment by FranckyC** [comment]
@vui211 Yep sorry, picked up the wrong name ;). Ok maybe I should include this format as well in the regex. Never encountered before.

**Comment by vui211** [comment]
Thanks @FranckyC  If it helps refinable property for some documents has couple of values like this Produce;846;#Produce|b438b43d-666b-4ef4-a158-59215589b8a6  because there are multiple crawled properties mapped to refinable one. 
![image](https://user-images.githubusercontent.com/23225932/55042934-c1e87980-5098-11e9-88b4-f005956ca849.png)

**Comment by FranckyC** [comment]
It explains why! You should use a dedicated refinable managed property using the owstaxid... crawled property. Let me know.

**Comment by vui211** [comment]
Hi @FranckyC 
You are right, with correct mapping all works as it should.
Thanks
