### ISSUE TITLE
Can not build react-search-refiners

### ISSUE THREAD

**Issue by mukeshhope** [SharePoint/sp-dev-solutions#66]
Hi Team,

I was trying to use Modern search related webparts. 
I downloaded the code and as per instruction i run npm install and gulp serve however it shows blank screen.

When i create a project normally then it works fine.  please suggest what issues could be.
my node version is 8.11.3
npm version is : 5.6.0
i get a lot of errors in console as below. 
![reactsearchrefiner](https://user-images.githubusercontent.com/18657453/53974422-8fe29800-4128-11e9-814f-77e7e72dd0fd.png)

Thankyou in advance for your suggestions

**Comment by wobba** [comment]
Which SPFx version are you running?

**Comment by mukeshhope** [comment]
Hi Wobba,

I am sorry but how can i find what version of spfx am i using . i mean is there a command to find that out.
I think that it should be 1.5.1 but please tell me if there is some way to confirm this and how to upgrade then ? . Thankyou so much for your help

**Comment by wobba** [comment]
If you open .yo-rc.json in a new project you see the version. This webpart requires at least 1.7.0, so you can update your SPFx version with `npm install -g @microsoft/generator-sharepoint` where 1.7.1 is the latest.

**Comment by mukeshhope** [comment]
Hi Wobba,

Thank you so much for your help. i now have installed 1.7.0 version of yeoman generator by but i can not build the solution using gulp build.
please have a look on the error i am getting
![reactsearchrefiner1](https://user-images.githubusercontent.com/18657453/54023209-61150200-41ba-11e9-9081-481d71eba601.png)

**Comment by wobba** [comment]
@mukeshhope I noticed - just pushed a fix for this just 5 seconds ago :)

**Comment by wobba** [comment]
@mukeshhope I did a fresh clone of the repo just now, and that seems to build as expected with SPFx v1.7.1.

**Comment by mukeshhope** [comment]
Hi Wobba ,
Thankyou so much. it is now working.
I will now build and try it. but i am very happy with the help that you provided.
Thankyou once again
