### ISSUE TITLE
ColumnFormatter: gulp bundle --ship hangs on 'webpack' subtask

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-solutions#7]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
`gulp bundle --ship` works fine - the solution is built in release mode
#### Observed Behavior
`webpack` subtask hangs

#### Steps to Reproduce
`gulp bundle --ship`

**Comment by thechriskent** [comment]
It takes 30+ minutes to run. Which is why I've provided the package directly in the assets: https://github.com/SharePoint/sp-dev-solutions/raw/master/solutions/ColumnFormatter/assets/column-formatter.sppkg

**Comment by AJIXuMuK** [comment]
ouch... =) Have you investigated why it takes so long?

**Comment by VesaJuvonen** [comment]
Closing as no activities and not really an issue.
