### ISSUE TITLE
[ModernSearch] Search navigation Web Part should allow predefined queries

### ISSUE THREAD

**Issue by FranckyC** [SharePoint/sp-dev-solutions#70]
#### Category
- [ X] Enhancement

#### Expected or Desired Behavior

@taraldga Instead of relying on a search box, you could also add a mode where tabs correspond to predefined queries and use the URLFragment (or other configurable option like a query string parameter) to pass them. It could be very useful to enable single search page scenarios with query rules and result types depending the query.

Also add the sorting option on tabs (PropertyFieldCollectionData). It could useful as well.

Also use a placeholder on first configuration. Right now it feels like there is a bug or something since the Web Part shows nothing.

**Comment by taraldga** [comment]
@FranckyC  Thanks for the feedback, I will look into this in the coming week.

Just to clarify the first point: do you mean an option for the user to set a default search query for a navigation node instead of relying on the query that comes from the search box?

**Comment by FranckyC** [comment]
@taraldga Yes that's right the user could enter an arbitrary keyword instead and send it to the current page as an URL fragment.

**Comment by YannickRe** [comment]
@FrankyC is this still relevant now that you created the Search Verticals webpart? Functionality seems similar.

**Comment by FranckyC** [comment]
@YannickRe the concept quite different and I didn't want to refactored the search navigation component totally. The search verticals was needed for my project so that's why I created a new WP. @taraldga what do you think? Does it work for you if you replace the search navigation WP by the search verticals?

**Comment by taraldga** [comment]
Hi, 
There might be some implications on our projects if we remove the functionality, but this is a good and logical way to improve on the experience of the application as a whole. Lets go for it!
