### ISSUE TITLE
How to use Query String Parameters with Search Result WebPart

### ISSUE THREAD

**Issue by coupalm** [SharePoint/sp-dev-solutions#76]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [X ] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
I would like to use a URL querystring parameter in the search result web part but not sure how to do it.

In the first screen It is configured to use the page environment, querystring and my URL parameter is selected.

In my page URL I have ?ListItemId=1. So how do I use this querystring parameter?
I'v been trying in my search request: ListItemId={QueryString.ListItemId} but it does not work.
I know that ListeItemId=1 is working.

Thanks!

**Comment by FranckyC** [comment]
Hi @coupalm Does your WP configuration look like this?

![image](https://user-images.githubusercontent.com/5659122/54324233-47692580-45d3-11e9-82db-62a7e02f2d33.png)

The parameter is available in the Web part when your browse the page with *?Mode=Edit&ListItemId=1*

**Comment by coupalm** [comment]
Exactement.

So how do I use the url parameter value in the query? What is the token?

Thanks!

**Comment by wobba** [comment]
@coupalm If I understand you correct you want to pull arbitrary query params as variables in the query, correct? This has not been implemented afaik, but shouldn't be too hard to implement `{QueryString.<ParameterName>}` . @FranckyC has to correct me if I'm mistaken in how the dynamic query param works, but seems that only works to pull an arbitrary param to be used as the full query.

**Comment by FranckyC** [comment]
I confirm @wobba @coupalm you can't use the query string parameter as a `{QueryString.<ParameterName>}` token in your search query. The dynamic data source parameter will be use as `{searchTerms}` token so it means you can't use both search box and query string parameter at the same time for instance.

**Comment by wobba** [comment]
I'll leave this issue open as reference until we implement URL param query variables.

**Comment by coupalm** [comment]
Sorry for the late response. Yes that's exactly it (use query string parameters in my search query). Thanks!

**Comment by YannickRe** [comment]
FYI: I started working on this.

**Comment by YannickRe** [comment]
@wobba This one can be closed, I think.

**Comment by SrinivasVeepuri** [comment]
I need help on this topic

**Comment by SrinivasVeepuri** [comment]
I am unable to pass the Querystring parameter values to search results webpart
