### ISSUE TITLE
react-search-refiners handlebar helper getDate not working consistently

### ISSUE THREAD

**Issue by MichalExpP** [SharePoint/sp-dev-solutions#78]
#### Category
- [ ] Question
- [X] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Handlebar template using a handlebar helper {{getDate Created "D MMMM"}} to display a date from a SharePoint date field consistently.

#### Observed Behavior
The template displays a date correctly, but in every 5-10 page load, the date is not being displayed at all when {{getDate Created "D MMMM"}} helper is used. No errors in the browser are logged.
If I output just {{Created}}, this date will always display eg:
First output is using {getDate Created "D MMMM"}}, second {{Created}}

Start Date:
Start Date: 2019-03-04T00:00:00Z

#### Steps to Reproduce
I'm using react-search-refiners 2.5.1.0 & 3.0.0.0 with "skipFeatureDeployment": true, SharePoint Online.

Create a list and create few list items, then create a simple search results template and output the information:

`<div><div>Created Date:</div><div>{{getDate Created "D MMMM"}}</div></div>`
`<div><div>Created Date:</div><div>{{Created}}</div></div>`

Refresh browser few times, the date doesn't from time to time. Chrome and IE have been tested with the same result. The out of the box default template is also showing this behavior.

**Comment by wobba** [comment]
@MichalExpP tested with the latest code (shouldn't really matter as this hasn't changed) and can't reproduce on either IE or Chrome. Added a webpart, added * as the search, left everything else default and changed the default template to use "D MMMM" in the format.

Does it render blank or "invalid date", and if you inspect the DOM, is the field blank - also would be interesting if you could check the network trace for `/_api/search/postquery`  and see if created date is part of the response coming back or not.

**Comment by MichalExpP** [comment]
@wobba Hi Mikael, I've just noticed this happens only, only if more than one search web part is the page. I don't have many pages with only one web part, I do apologise for the commitment.
- Postquery does give correct date
- DOM displays a blank (space) value

I've reproduced this with 2 Lists, 3 items in each (You can use one list, the same outcome). Create List1 and List2, add 2 web parts to the page and display exactly the same thing, but each from a different list.
- Search query keywords: *
- Query template List1: Path:https://xxxxxx.sharepoint.com/sites/xxx/Lists/List1/
- Query template List1: Path:https://xxxxxx.sharepoint.com/sites/xxx/Lists/List2/
- All other properties are set to default
It takes 2-5 page refreshes to get the issue.

In my real life scenario, I have e.g. "News" web part displays pages & "New Starters" web part displays list items. Both web parts have different data source, templates and different managed properties for dates being displayed. Hopefully, you will be able to reproduce with two lists.

**Comment by wobba** [comment]
@MichalExpP I've reproduced it - let's see if I can figure out what happens.

**Comment by wobba** [comment]
@MichalExpP seemed to be a weird race condition where the a helper variable wasn't set, even though it should have. Moved it to a global variable, which is also shared among all web parts. This seems to have solved the issue. `v3.0.4.0` has the updated code.
