### ISSUE TITLE
Modern search refinable result open document in client application

### ISSUE THREAD

**Issue by stridsbr** [SharePoint/sp-dev-solutions#79]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

Is there a way to open documents in the client application from the resultwebpart? Or how do I tell SharePoint to open the document in the client application instead of office online? Is there a parameter to the page _layouts/15/Doc.aspx like openInWeb=false or some other simple solution?

I have configured the library to open documents in client application and enabled the feature Open documents in client application by default.

When I click on documents in the library it opens in the client but not from search. Both from a old classic searchcenter and the refinable result webpart it opens in office online.

**Comment by wobba** [comment]
If the library has default to open in the client you should be able to use a direct linke `https://someurl.sharepoint.com/sites/site1/Shared%20Documents/WordDoc1.docx`. If you want to force it you can try `ms-word:ofe|u|https://someurl.sharepoint.com/sites/site1/Shared%20Documents/WordDoc1.docx` which will prompt the user first I believe.

**Comment by stridsbr** [comment]
Thanks for the quick reply. When I use the full url the document is downloaded and don't open directly. The other works nice.

Found the schema documented here:
https://docs.microsoft.com/en-us/office/client-developer/office-uri-schemes

thanks :-)
