### ISSUE TITLE
Pnp search not showing MS Teams data

### ISSUE THREAD

**Issue by Ashutosh2019** [SharePoint/sp-dev-solutions#88]
#### Category
- [ ] Bug

#### Expected or Desired Behavior
The Pnp Search result spfx web-part should show result from MS Teams as there is no change in result resource. If you try default modern search, in organization search result page the document appears. 

#### Observed Behavior
The Pnp Search result spfx web-part doesn't show result from MS Teams. If you try with same key word/text in OOTB modern search, in organization search result tab of the page, the document appears but it doesn't appear in PnP search result web-part.

#### Steps to Reproduce
1- Create a Teams in MS teams. It will create SharePoint site.
2- Upload a document.
3- Create a modern Communication site. Configure PnP search box and Search result web-part. 
4- Try searching for the document uploaded to MS Teams. It doesn't appear.

**Comment by wobba** [comment]
I'm pretty sure I know what this is. To be sure do you see this on both public and private teams?

**Comment by Ashutosh2019** [comment]
I am the owner of the MS Teams and the document uploaded in it doesn't appear for me only in PnP search result webpart.  

But the same result shows in classic Search page, default modern search page as well.  As I understand it points to same result source as classic search page or default modern search page.  Just curious what can be reason behind it.

**Comment by wobba** [comment]
@Ashutosh2019 get the latest code and it should be fixed.

**Comment by wobba** [comment]
@Ashutosh2019 for some groups/teams we need to add a specific property named `EnableDynamicGroups=true` to the query to get results. The oob search adds this by default, but it's not really documented anywhere, but we know that it's there. I've had it on my mind to add it for a while, but never got around to it as it hasn't been an issue in my usecases.

I also added the param to make multigeo search work - in case someone needs that.

**Comment by Ashutosh2019** [comment]
Thank you Mikael. I encounter another challenge after pulling the latest code, I don't see refiner, paging and search navigation webpart in my web-part inventory.

**Comment by wobba** [comment]
They are separate web parts in v3.
