### ISSUE TITLE
How to fetch user photo in blog post dynamically using react search refiner??

### ISSUE THREAD

**Issue by Rajrup-net** [SharePoint/sp-dev-solutions#89]
I have a blog widget where I have used react search refiner to fetch all the blog post. But only thing is author's profile picture is not coming. I want All the posts by users needs to be accompanied with their profile picture. Can anyone help me out please ???

**Comment by FranckyC** [comment]
Hi @Rajrup-net what managed property are you using? I think you have to make a subsequent call to get the picture based on the author info because it does not surface up in search I guess.

**Comment by wobba** [comment]
@Rajrup-net you need to create a render template which has a working link along the lines of `/_layouts/15/userphoto.aspx?size=M&accountname=<accountName>`. So if you have account name/login as your refiner (UPN without claims), then you can put that as the `src` in an image tag. You could for example include `AuthorOWSUSER` as a managed property and use something like the sample template below.

```html
<style>
    /* Insert your CSS here */
</style>

<div class="template_root">
    <ul class="ms-List">
        {{#each items as |item|}}
            {{#> resultTypes}}
                {{!-- The block below will be used as default item template if no result types matched --}}
                <li class="ms-ListItem ms-ListItem--image" tabindex="0">
                    <span class="ms-ListItem-primaryText"><a href="{{getUrl item}}">{{Title}}</a></span>
                    <img src="{{webUrl}}/_layouts/15/userphoto.aspx?size=M&accountname={{first (split AuthorOWSUSER '|')}}">
                </li>
            {{/resultTypes}}
        {{/each}}
    </ul>
</div>
```

**Comment by Rajrup-net** [comment]
@wobba   Thanks a ton.. It's worked a like a charm  :)
