### ISSUE TITLE
ModernSearch (react-search-refiners package) web-part package doesn't have refiner, paging and search navigation webaprt included.

### ISSUE THREAD

**Issue by Ashutosh2019** [SharePoint/sp-dev-solutions#92]
#### Category
- [ ] Question

#### Expected or Desired Behavior
As described in the PnP blog video and description in ModernSearch web-part has refiner, paging and search navigation included. I was using a older version and pulled the latest, I don't see those in my web-part  inventory.

#### Observed Behavior
ModernSearch web-part package doesn't have refiner, paging and search navigation included. I was using a older version and pulled the latest, I don't see those in my web-part  inventory.

If possible, please put the details about, how to get Search refiners, Search Navigation, Search paging web-part.

**Comment by FranckyC** [comment]
@Ashutosh2019 Try to uninstall your app completely from your site and then resintall it
