### ISSUE TITLE
[ModernSearch] Regression with pagination

### ISSUE THREAD

**Issue by YannickRe** [SharePoint/sp-dev-solutions#95]
#### Expected or Desired Behavior
If you have multiple pages of search results and select a page, when selecting a refiner I expect to be returned to the first page of search results.

#### Observed Behavior
The selected page "sticks", and when there aren't any search results on that page it will show the no results message and no page selected in the pages webpart.

#### Steps to Reproduce
Steps to be executed in the local workbench:

- Add a searchbox, search results, search refiners and search pagination web part on the page and connect them.
- Show only 1 search result per page
- Switch to page 4
- Apply refiner on Type, and select "Document"

Result: paging webpart shows 2 available pages, but no results are shown.

#### Reason
@FranckyC the changes you made in #94 cause this regression, specifically those done in componentWillReceiveProps of SearchResultsContainer.tsx. Can you look at this?

**Comment by wobba** [comment]
@YannickRe  @FranckyC  A thought, should I create a dev branch, and we can merge to master on regular intervals?

**Comment by wobba** [comment]
Ok, I created `modern-search-dev`, so please target PR's to this branch :)

**Comment by FranckyC** [comment]
@wobba definitely yes for the 'dev' branch! @YannickRe yes I refactored this method because I had an issue when a default keyword was present in the URL fragment. The query wasn't executed. Ideally the fix should be in the pagination control itself avoiding to overload the componentWillReceiveProps method.

**Comment by YannickRe** [comment]
@FranckyC I had something that didn't impact componentWillReceiveProps but it triggered the search request two or three times:
- User enters a query, search request executed
- Updated pagination, search request executed
- Updated refiners, search request executed with previously selected page. Pagination webpart notices that it's a different query (different filters), resets pagination. Search results webpart picks up the new pagination and re-issues he same query with the page == 1

My implementation made sure that each update to connected webparts would only trigger one search request. I don't see how the changes you made to SearchResultsContainer would fix that a query doesn't execute with a default keyword in the querystring.

**Comment by FranckyC** [comment]
@YannickRe my change does not fix that. Like I said, I had an issue using URL fragment. I can revert to old version but we have to make sure this scenario is covered. My point is simply we could probably simplify the logic because the componentWillReceiveProps becomes overloaded and hard to read with lot of conditions and exceptions.

**Comment by YannickRe** [comment]
@FranckyC I agree that the componentWillReceiveProps is rather difficult to understand and might need some attention to improve :) But at least now, all the logic to re-render exists in one place :D
If/When we refactor this, we need to be careful to not introduce regressions in functionality.

**Comment by FranckyC** [comment]
Yes of course, I will revert this change until I found a better way to handle this.

**Comment by FranckyC** [comment]
Should be back to previous version now @YannickRe
